gallery-so/go-gallery

.gitignore
scripts/migration.py

Migration script

---

persist/collection.go
persist/nft.go
server/collection.go
server/handler.go

Changes:
- **Added** update endpoint and persist update func

update endpoint and persist update

---

persist/collection.go
server/collection.go

Changes:
- **Added** delete coll func
- **Changed** delete endpoint to use delete func

delete collection persist func

---

persist/collection.go
server/collection.go
server/user.go

Changes:
- **Changed** collections and user get endpoints to handle auth status differently such as showing or not showing hidden collections or returning a list of addresses or not for a user

users and collections scenarios

---

.gitignore
server/middleware.go
server/server.go

Closed #74 in favor of this one. 
Instead of installing and using the official Gin CORS middleware, this pr just adds the headers we need (for now)

Add CORS middleware to set response headers and handle OPTIONS method

---

persist/auth.go
persist/collection.go
persist/gallery.go
persist/nft.go
persist/t__persist_test.go
persist/user.go
server/auth.go
server/handler.go
server/jwt.go
server/middleware.go
server/t__auth_jwt_test.go
server/t__auth_user_test.go
server/user.go

authentication adjustments and additions

---

persist/collection.go
persist/gallery.go

Changes:
- **Added** new filter expressions in match aggregation cases for filtering out deleted entities

aggregations handle deleted entities

---

server/validate.go

Small PR with title describing changes.

validators don't check empty fields, thats for required validator to do

---

server/middleware.go

abort with status JSON

---

copy/errorMessages.go
go.mod
go.sum
persist/mongo.go
persist/nft.go
runtime/runtime.go
server/collection.go
server/middleware.go
server/nft.go
server/t__auth_user_test.go
server/t__main_test.go
server/t__opensea_test.go
server/t__routes_health_test.go
server/t__routes_nft_test.go
server/t__test_utils_test.go

- created global `TestConfig` for fixtures when running tests (user, jwt, etc)
- handle various `TestUpdateNftById` cases
- created `copy` package for stable copy strings
- fixed silent error with `c.GetString` (should be improved later)

Update nft by id test

---

server/collection.go
server/middleware.go

Changes:
- **Added** helper func for getting userid from gin context
- **Changed** funcs that manually got user id from context to use helper func
- In the funcs that have the jwtRequired middleware, do we need to use the ok bool with the helper function since we can guarantee that the userId will be there?

get user id from context

---

persist/collection.go
persist/nft.go
server/collection.go
server/nft.go
server/t__routes_collection_test.go

Changes:
- **Added** Collection Update Route test
- **Changed** collection update to accept an interface and added multiple update structs for updating specific parts of a collection, each corresponding to an endpoint
- **Changed** collection update endpoint to bind query not json

collection update route test and fixes

---

persist/collection.go
server/collection.go
server/handler.go
server/t__routes_collection_test.go

Changes:
- **Changed** collection get func and input struct to also accept getting by id

collections get by id

---

server/handler.go
server/jwt.go

Changes:
- **Added** endpoint for getting jwt validity
- Currently gets jwt from headers using the jwt optional middleware, do we want to use query instead?

jwt_valid endpoint

---

persist/mongo.go
persist/user.go
runtime/runtime.go
server/user.go

Changes:
- **Added** username unique/collation index
- **Changed** update user func to take in generic param and allow for specific fields to be updated without adjusting other fields
- Still needs a good test to ensure collation works as expected

username indexing

---

persist/collection.go
server/collection.go
server/handler.go

Changes:
- **Changed** update name endpoint and func and structs to update info, including both name and collectors note

update collectors note

---

go.mod
go.sum
server/server.go
server/user.go
server/validate.go

Changes:
- **Added** username validator
- **Added** sanitization library and policy to sanitize bio on update
- Any other fields need sanitizing on any other struct?

sanitize bio and set username requirements

---

server/collection.go
server/nft.go
server/response.go
server/user.go

Changes:
- **Changed** status responses to json responses

success output

---

persist/user.go
runtime/runtime.go
server/user.go

Changes:
- **Changed** index for username to not use collation
- **Added** field on user for idempotent username
- **Changed** getting and updating to respect new field

new field for idempotency

---

persist/collection.go
persist/gallery.go
runtime/runtime.go
server/gallery.go
server/handler.go
server/t__routes_gallery_test.go
server/validate.go

Changes:
- **Added** endpoints for creating, updating, and getting galleries
TODO:

gallery endpoints

---

cmd/server/main.go
copy/errorMessages.go
persist/auth.go
persist/collection.go
persist/gallery.go
persist/mongo.go
persist/nft.go
persist/t__persist_test.go
persist/t__unassigned_test.go
persist/user.go
runtime/config.go
runtime/projectpath.go
runtime/runtime.go
runtime/util.go
server/auth.go
server/collection.go
server/gallery.go
server/handler.go
server/jwt.go
server/middleware.go
server/nft.go
server/opensea.go
server/server.go
server/t__auth_jwt_test.go
server/t__auth_sig_test.go
server/t__routes_collection_test.go
server/t__routes_gallery_test.go
server/t__test_utils_test.go
server/user.go

Changes:
- **Added** comments to exported entities throughout application

add comments to exported entities

---

persist/mongo.go

Changes:
- **Changed** mongo low level funcs to use reflection to turn struct into a bson map and use the map when inserting, making adding, adjusting, removing, etc. fields super easy

bson marshalling

---

persist/user.go
server/handler.go
server/t__auth_user_test.go
server/t__routes_user_test.go
server/user.go

Changes:
- **Changed** update user endpoint to update info and no longer take in addresses or a user ID
- **Added** update addresses endpoint to take in a signature and address to verify and push onto a user's list of addresses

add address endpoint

---

server/collection.go

no hidden required

---

persist/collection.go
persist/storage.go

Changes:
- **Changed** collection update func to delete cached user unassigned
- **Added** a cache delete function

cache delete

---

server/collection.go

Changes:
- **Added** optional fields to coll create input for creating with name and collectors note

optional coll fields

---

server/t__routes_collection_test.go

Changes:
- **Added** collections hidden tests for getting one's own hidden collections and not getting another user's hidden collections

hidden tests

---

persist/auth.go

Changes
- **Changed** `persist.AuthNonceGet` to get the latest nonce by `created_at`

get most recent nonce to sign

---

server/handler.go
server/health.go

Changes:
- **Added** endpoint to drop DB only on local and dev environment

nuke endpoint

---

server/auth.go

Changes:
- **Added** a prepended string to nonce when signing and verifying signature

nonce prepend

---

persist/collection.go
server/t__main_test.go
server/t__routes_collection_test.go
server/t__test_utils_test.go

Changes:
- **Changed** collection aggregation to keep order of nfts
- **Added** test to updating nft order

fix aggregation to keep nft order

---

go.mod
scripts/migration.py
scripts/pull-supabase.js

Changes:
- **Changed** migration to take in a third csv file for getting creation times
- **Changed** supabase script to get users into a csv file along with nfts
- **Changed** sort function to compare position as an int not a string
- **Added** error logging to migration

migration sort and logs

---

persist/collection.go
persist/nft.go
server/nft.go

Changes:
- **Added** struct representing an NFT in a collection that has less return fields
- Did I choose the right fields?

add collection nft

---

persist/auth.go
persist/nft.go
persist/user.go
scripts/migration.py
server/auth.go
server/opensea.go
server/t__test_utils_test.go
server/user.go

Changes:
- **Changed** persist find funcs to lowercase address
- **Changed** funcs in server package that create a new entity in the database with an address to create that struct with a lowercase address
- **Changed** migration to lowercase all addresses
- Did I catch em all?

lowercase addresses in persist and server

---

go.mod
go.sum
persist/history.go
persist/nft.go
persist/storage.go
server/handler.go
server/middleware.go
server/nft.go
server/opensea.go
server/rate.go

Changes:
- **Added** a rate limiter middleware and used it for opensea sync
- **Changed** opensea sync to be an authed endpoint
- **Changed** bulk upsert func to use async (cut average test time down to 1/3 of what it was)

rate limit, faster sync, auth only

---

server/user.go

Include user created_at time in Get User response

---

persist/collection.go
persist/user.go
server/handler.go
server/user.go

Changes:
- **Added** remove addresses endpoint
- **Added** func to ensure that user does not remove all of their addresses
- **Added** persist func to pull addresses from their addresses list

remove addresses endpoint

---

server/auth.go
server/handler.go

Changes:
- **Added** jwtOptional middleware to preflight endpoint
- **Added** check for already authed during preflight to skip the NFT check

authed preflight no NFT check

---

Makefile
contracts/IENS.go
contracts/abi/IENS.json
contracts/sol/IENS.sol
server/eth.go
server/user.go
server/validate.go

Changes:
- **Added** func that checks if address resolves to ENS address
- **Added** check in username change to see if a user is trying to change their name to an ENS and if so ensure that it resolves to one of their addresses

ens support

---

go.mod
go.sum
persist/collection.go
persist/nft.go
persist/storage.go
server/opensea.go
server/t__opensea_test.go

Changes:
- **Added** update to remove NFTs that are no longer in wallet

remove nfts that are not in claimed

---

persist/collection.go
persist/nft.go
persist/storage.go
runtime/runtime.go

Changes:
- **Added** redis clients to runtime
- **Changed** persist storage funcs to use redis clients specified by the RDB number

long live redis

---

server/middleware.go

Changes:
- **Added** check in cors middleware for request origin starting with a vercel generated git link

loosen cors for vercel

---

server/collection.go

Changes:
- **Added** check to see if a user is trying to update a collection to have more than 100 NFTs

coll nfts cap

---

persist/auth.go
server/auth.go
server/collection.go
server/nft.go
server/t__auth_test.go
server/t__opensea_test.go
server/t__routes_auth_test.go
server/t__routes_collection_test.go
server/t__routes_gallery_test.go
server/t__routes_health_test.go
server/t__routes_nft_test.go
server/t__routes_user_test.go
server/t__test_utils_test.go
server/user.go

Changes:
- **Added** more tests cases for users and auth

failure test cases

---

persist/nft.go
server/opensea.go

Changes:
- **Added** fields to gallery NFT structs and opensea asset struct to get opensea collection name from api request
- Front end will have to use new field instead of contract name

token collection name

---

server/auth.go
server/eth.go
server/t__auth_test.go
server/t__routes_auth_test.go

block signups

---

server/auth.go
server/handler.go

Changes:
- **Added** endpoint for checking if a user is a member (has a membership card)

is member endpoint

---

middleware/jwt.go
server/server.go

Update JWT TTL

---

.circleci/config.yml
memstore/t__tasks_test.go
persist/mongodb/collection_token.go
server/gallery_token.go
server/t__auth_test.go
server/t__membership_test.go
server/t__opensea_test.go
server/t__routes_auth_test.go
server/t__routes_collection_test.go
server/t__routes_collection_token_test.go
server/t__routes_gallery_test.go
server/t__routes_gallery_token_test.go
server/t__routes_health_test.go
server/t__routes_nft_test.go
server/t__routes_token_test.go
server/t__routes_user_test.go
server/t__routes_user_token_test.go
server/t__test_utils_test.go
server/token.go

Changes:
- **Changed** test files for v2 tests to be uncommented and fixed them to work with most recent backend changes

uncomment and fix v2 tests and allow them to run as well as v1

---

server/gallery_nft.go
server/handler.go
service/persist/gallery_nft.go
service/persist/mongodb/gallery_nft.go

Changes:
- **Added** a bust cache endpoint for galleries

bust cache galleries

---

service/auth/auth.go

Changes:
- **Changed** preflight to check for a nonce in the case that the user does not exist so that nonces can be reused until used once

use nonce if it exists in case user does not exist for preflight

---

service/persist/access.go
service/persist/accounts.go
service/persist/auth.go
service/persist/backups.go
service/persist/collection_nft.go
service/persist/collection_token.go
service/persist/contracts.go
service/persist/features.go
service/persist/gallery_nft.go
service/persist/gallery_token.go
service/persist/history.go
service/persist/membership.go
service/persist/mongodb/mongodb.go
service/persist/persist.go
service/persist/user.go

Changes:
- **Changed** date time decoding to decode on an individual type basis
- **Added** JSON marshalling and unmarshalling to custom time types that represented creation time and last updated time

correctly  marshall/unmarshall/encode/decode times from db

---

service/auth/auth.go
service/user/user.go

Changes:
- **Added** new nonce prepend
- **Changed** nonce validations in signature and login/address change pipelines so that it will first check new nonce prepend then check old nonce prepend
- **Changed** preflight to use new nonce prepend

new nonce prepend

---

server/membership.go
service/membership/membership.go

Changes:
- **Added** functions for updating a single membership tier
- **Changed** endpoint for membership tiers to get all tiers that are missing and update tiers that have not been updated recently individually

check to ensure all tiers are accounted for

---

indexer/indexer.go
indexer/metadatas.go

Changes:
- **Added** an ENS handler for producing an SVG metadata for ENS names

ENS handler

---

server/t__opensea_test.go
service/persist/mongodb/collection_nft.go
service/persist/mongodb/collection_token.go
service/persist/mongodb/gallery_nft.go
service/persist/mongodb/gallery_token.go
service/persist/postgres/collection_nft.go
service/persist/postgres/collection_token.go
service/persist/postgres/gallery_nft.go
service/persist/postgres/gallery_token.go
service/persist/postgres/t__collection_nft_test.go
service/persist/postgres/t__galleries_nft_test.go

Changes:
- **Added** checks to ensure when a user updates or creates a gallery or collection that they own the collections or tokens they are using in the update

ensure that user owns what they are using in their updates and creates

---

service/membership/membership.go

Changes:
- **Added** a check to ensure that membership tiers are not duplicated because a user has two membership cards of the same tier in their multiple addresses

no duplicate users

---

indexer/core.go
indexer/handler.go
indexer/server.go
server/t__routes_collection_token_test.go
server/t__test_utils_test.go
service/opensea/opensea.go
service/persist/token.go
util/random.go

Changes:
- **Added** processing for unaccounted for NFTs from the check against opensea

validate and update nfts if not accounted for

---

server/handler.go
server/membership.go
service/membership/membership.go

Changes:
- **Changed** membership endpoint to return in specific order
- **Changed** membership update process to grab the first 3 NFTs that can be found from a user's ordered collections

order tiers and get first nfts

---

server/auth.go
server/user_nft.go
service/auth/auth.go

Changes:
- **Changed** cookies to use not secure, not http only on dev and local

make cookies relaxed on dev and local

---

service/auth/auth.go

this allows the local frontend to make authenticated requests

relax cookies if localhost

---

middleware/middleware.go
server/auth.go
server/handler.go

Changes:
- **Added** logout endpoint that removes jwt from cookie

logout endpoint

---

server/collection_token.go
server/gallery_token.go
server/handler.go
server/server.go
server/token.go

if service key is unset locally, app will still run instead of crashing

Ignore unset local service key

---

service/membership/membership.go

Changes:
- **Added** the contributor card to the membership endpoint

contributor card for membershop tiers

---

cmd/migration/main.go
cmd/migration/t__migration_test.go
service/persist/postgres/collection_token.go

Changes:
- **Added** an indexer migration script
- **Added** a test for this script
Wrote the script instead of python this time because I am very familiar with go and postgres and thought it wouldn't be worth my time to learn how to use postgres on python for a relatively simple script like the one I wrote.

indexer migration script

---

server/collection_nft.go
server/collection_token.go
server/nft.go
server/server.go
server/t__routes_collection_test.go
server/token.go
service/user/user.go
validate/validate.go

Changes:
- **Added** validators for bio and collectors notes
- **Added** test for validation

char limit

---

cmd/migration/main.go

Changes:
- **Added** some helpful logs for us to keep track of things during the indexer migration and ensure that nothing goes wrong.

some more logging for the indexer migration

---

service/persist/postgres/postgres.go

Changes:
- **Added** a max connection count for environments that are not local
- Should the max connection count apply locally as well?

max conns 100 on dev and prod

---

admin/collection.go
admin/db.go
admin/handler.go
admin/nft.go
admin/user.go

Changes:
- **Added** collection getting, updating, and deletion endpoints to the admin backend
TODO:

collections admin endpoints

---

service/persist/postgres/gallery_nft.go
service/persist/postgres/gallery_token.go

Changes:
- **Changed** gallery get functions to not accidentally add an NFT that does not exist in a collection to a collection

fix empty collection showing nft

---

server/nft.go
service/persist/nft.go
service/persist/postgres/nft.go

Changes:
- **Changed** update NFT by ID endpoint to take in data from JSON post

update collectors note with post JSON

---

service/persist/nft.go
service/persist/postgres/collection_nft.go
service/persist/postgres/gallery_nft.go

Changes:
- **Added** animation url to collection NFT

animation url in collection nft

---

service/persist/postgres/gallery_nft.go
service/persist/postgres/gallery_token.go

Changes:
- **Changed** get gallery DB to skip iteration over deleted colls with empty IDs

skip deleted collections

---

admin/handler.go
admin/nft.go
admin/snapshot.go
service/opensea/opensea.go
service/persist/nft.go
service/persist/postgres/nft.go

Changes:
- **Changed** refresh opensea admin func to take in arrays of addresses or userIDs to refresh a lot of opensea wallets at once
- **Added** opensea refresh for wallet func
- **Changed** bulk upsert to not user userID

opensea just by address

---

admin/snapshot.go

Changes:
- **Changed** snapshot update endpoint to delete, write, then update ACL

snapshot write

---

server/handler.go
server/proxy.go
server/server.go

Changes:
- **Added** endpoint for proxying snapshot at `glry/v1/proxy/snapshot`

proxy snapshot endpoint

---

admin/nft.go
cmd/refresh/refresh.go

Changes:
- **Added** script for refreshing opensea locally for a large amount of users so I don't have to worry about HTTP timeouts when using the admin UI for thousands of refreshes

script for refreshing opense

---

server/collection_nft.go
server/collection_token.go
server/handler.go
server/t__integration_utils_test.go
server/t__server_integration_test.go
service/persist/collection_token.go
service/persist/postgres/collection_nft.go
service/persist/postgres/collection_token.go

**Changes**
* Adds `Whitespace` to Layout
* Adds integration test for collections
* Fixes a small bug where missing collections returned an internal error instead of a not found

Add whitespace

---

service/persist/postgres/gallery_nft.go
service/persist/postgres/gallery_token.go

Changes:
- **Changed** add collections func in gallery postgres package to add collections to the front of the gallery

add collection to front of gallery

---

admin/snapshot.go

Changes:
- **Added** a header to writing the snapshot that ensures it will not be cached

do not cache snapshot

---

graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.helpers.go
graphql/schema/schema.graphql
publicapi/collection.go
publicapi/gallery.go
publicapi/nft.go
publicapi/publicapi.go
publicapi/user.go
server/server.go
validate/validate.go

Start doing validation and sanitization at the public API level. Still some TODOs to handle in a future pass, but this PR covers the basics.

Initial validation for public API functions

---

publicapi/publicapi.go
publicapi/user.go
server/handler.go
server/membership.go
server/server.go
server/t__routes_token_test.go
server/token.go
service/membership/alchemy.go
service/membership/membership.go
service/persist/postgres/gallery_nft.go
service/persist/postgres/gallery_token.go

Changes:
- **Added** an endpoint for refreshing a token's metadata (URI, JSON metadata, and Media)
TODO:

refresh metadata endpoint

---

admin/handler.go
admin/nft.go
cmd/migration/main.go
cmd/refresh/main.go
server/backup.go
server/handler.go
server/nft.go
server/t__opensea_test.go
service/nft/nft.go
service/opensea/opensea.go
service/persist/backup.go
service/persist/gallery_nft.go
service/persist/nft.go
service/persist/postgres/backup.go
service/persist/postgres/collection_nft.go
service/persist/postgres/gallery_nft.go
service/persist/postgres/nft.go
service/persist/postgres/t__backup_test.go

Changes:
- **Added** backup repo functions for getting backups and restoring backups
- **Added** tests for backup repo additions
- **Changed** claim NFTs step in opensea to not remove NFTs that are transferred between addresses

backups and opensea claiming

---

indexer/server.go
server/t__opensea_test.go
service/opensea/opensea.go

Changes:
- **Changed** opensea fetch to use cursors instead of offset
- **Changed** update assets for account to skip wallet if there are no assets for a wallet
- **Added** test for ^

opensea api update

---

publicapi/user.go
server/handler.go
server/user_nft.go
server/user_token.go
service/user/user.go

Changes:
- **Changed** create user and add address funcs for users in v2 endpoints to ensure that any new addresses call the indexer validate functions to ensure they have all of their NFTs as well as have all of the media content for their NFTs

validate new address NFTs

---

graphql/resolver/schema.resolvers.helpers.go

Include whitespace in collection layouts

---

graphql/resolver/handlers.go

Without a JSON formatter, each line of a query is treated as a separate log entry, which makes the query difficult to read and
much harder to do anything with.

Use a logrus JSON formatter to log GraphQL queries on GCP

---

admin/db.go
admin/handler.go
admin/user.go

Changes:
- **Added** address input for get user admin

address user admin

---

service/membership/membership.go

Changes:
- **Changed** membership endpoint to not include members that have no NFTs displayed. We determine this by looking at whether or not they have any preview NFTs.

no previews, no membership

---

service/persist/postgres/community.go

Filter out duplicate usernames in Community results. This isn't an ideal long-term solution, as we're only returning one address even for users who hold community NFTs in several addresses. It's a good short-term solution, though, since it stops us from showing duplicate usernames and doesn't have any negative implications for the frontend (nor is it a breaking change).

Quick fix: don't include a username in Community results more than once

---

feedbot/collection.go
service/event/cloudtask/cloudtask.go
service/event/cloudtask/collection.go
service/event/cloudtask/nft.go
service/event/cloudtask/user.go
service/persist/postgres/nft_event.go

**Changes**
* Fixes the issue where tasks are sent to the backend rather than the feedbot
* Fixes nil pointer error that's caused when there is no previous collection token added event
* Fixes errors in retrieving NFT events because of type mismatch
**Testing**
* Tested changes locally and also deployed backend to sandbox

Fixup - various feedbot bugs

---

graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.helpers.go
graphql/schema/schema.graphql

Allows us to dedupe by opensea ID on frontend

[GAL-144] Return opensea IDs with NFTs

---

graphql/generated/generated.go
graphql/model/models_gen.go
graphql/model/remapgen_gen.go
graphql/resolver/schema.resolvers.go
graphql/resolver/schema.resolvers.helpers.go
graphql/schema/schema.graphql

**Changes:**
* Adds query `userById`
* Sneaking in a few small name changes for the following resolvers

Add userById query

---

graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.go
graphql/schema/schema.graphql

**Changes**
* Adds `user` field to the following mutations for the user that was unfollowed/followed

Add user field to follower mutations

---

service/membership/alchemy.go
service/persist/token.go

Changes:
- **Changed** alchemy calls to indexer calls for membership page

use indexer membership

---

validate/validate.go

Quick PR to add `community` to reserved list

Add community to reserved list

---

db/queries/query.sql
db/sqlc/batch.go
db/sqlc/query.sql.go
graphql/dataloader/dataloaders.go
graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.go
graphql/resolver/schema.resolvers.helpers.go
graphql/schema/schema.graphql
publicapi/token.go

This field returns all of a user's tokens, without duplicates.

Add tokens field to GraphQL GalleryUser type

---

service/membership/alchemy.go

Changes:
- **Changed** hard-coded indexer URL to an env var.

indexer host env

---

feed/event.go

Small change to add a span to the feed service.

Add trace to feed

---

feed/event.go
feedbot/post.go
graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.go
graphql/resolver/schema.resolvers.helpers.go
graphql/schema/schema.graphql
service/persist/event.go

**Changes**
* Adds `isPreFeed` flag when we can't determine what tokens were added. The `newTokens` field will always be empty when `isPreFeed` is `true`
* Updates the feedbot
* Cleanup: removes extra struct forwarding calls

Add isPreFeed flag

---

service/persist/postgres/user.go

As part of the multichain migration, we ended up breaking the functionality that stops users from changing their username to something that's already taken. This is a quick fix for that bug.
Follow-up steps:
- Handle the 14 users who do have duplicate usernames
- Once that's done, set a unique constraint on the `users.username_idempotent` column as another layer of protection against this scenario occurring

Bug fix: don't allow users to pick already-taken usernames

---

publicapi/user.go

**Changes**
* Moves UserCreated trigger from `UpdateUserInfo` to `CreateInfo`

Move user created trigger

---

indexer/nfts.go
service/media/media.go

**Changes**
* Adds custom errors for token updates
* Skips reporting errors to Sentry for tokens with generic handlers
* Skips reporting errors for image URLs missing in GCP

Add custom errors for updates

---

indexer/nfts.go

**Changes**
* Suppresses throttle errors to sentry

Change log to warn

---

indexer/nfts.go
service/persist/postgres/token.go

Changes: (super duper small PR)
- **Updated** upsert function to match new indexes
- **Updated** `manualIndex` func in refresh token step to upsert into DB

upsert token from manual indexing

---

graphql/generated/generated.go
graphql/model/models_gen.go
graphql/model/remapgen_gen.go
graphql/resolver/schema.resolvers.go
graphql/schema/schema.graphql
indexer/metadatas.go
indexer/nfts.go
publicapi/token.go
service/media/media.go
service/multichain/opensea/opensea.go
service/persist/postgres/token.go
service/persist/postgres/token_gallery.go
service/persist/token.go

Changes:
- **Changed** gif handling to work similarly to images
- **Changed** manual index step to work for ERC-1155 tokens

handle gifs separately, manually index with non-indexed tokens of owner

---

Makefile
contracts/Cryptopunks.go
contracts/abi/Cryptopunks.abi
contracts/sol/Cryptopunks.sol
docker/postgres/02_init.sql
go.mod
go.sum
indexer/nfts.go
service/media/media.go
service/persist/token.go
service/rpc/rpc.go
util/helpers.go

Changes:
- **Added** support for BMP as well as IPFS html pages
- **Changed** utf8 svg handling because it was not caching the image data correctly

new metadata's, minor fixes

---

indexer/indexer.go

Skips copy of the uri to a new variable

Skip copy of uri

---

indexer/indexer.go

Scaling down to lower amount of memory needed

Scale down from 4 to 3

---

indexer/indexer.go

Changes:
- **Changed** indexer to only make RPC calls in prod

process tokens in dev env with no RPC

---

publicapi/token.go

One-line fix for a bug I introduced in my previous "refresh collections" PR

[GAL-429] Collection refresh fixes, part 2

---

README.md
indexer/core.go

**Changes**
* Points local indexer and the indexer server to the dev buckets by default

[GAL-424] Point indexer to dev buckets

---

.circleci/config.yml

Small change to wait longer for the backend to startup

Bump CircleCI post-deploy sleep interval

---

server/server.go
service/multichain/multichain.go

Just wanted to make a small contribution to this repo. Seemed sensible to share a type here.

Use type alias for chain overrides

---

service/multichain/tezos/tezos.go

Changes:
- **Changed** tezos multichain provider functions to paginate tzkt requests

paginate tzkt

---

db/migrate.go
docker/docker.go
indexer/core.go
indexer/indexer.go
indexer/t__integration_test.go
indexer/t__utils_test.go
service/media/media.go
service/multichain/multichain.go
service/persist/postgres/t__utils_test.go
service/persist/postgres/token_gallery.go
service/rpc/rpc.go

Changes:
- **Added** integration testing for indexer covering a lot of cases, more cases to come
- **Changed** some code causing refresh issues

start integration testing and some fixes

---

service/multichain/tezos/tezos.go

Changes:
- **Changed** tez metadata fields to use interface so that unmarshalling does not error out

more generic tez metadata

---

indexer/core.go

Also removing a debug line I left in

Use websocket client

---

service/rpc/rpc.go

Changing log level to WARN so it doesn't spam Sentry

Change IPFS log level to WARN

---

.circleci/config.yml
README.md
server/handler.go

looks like we killed off our healthcheck endpoint

Healthcheck endpoint

---

indexer/nfts.go
mediaprocessing/handler.go
mediaprocessing/mediaprocessing.go
mediaprocessing/process.go
middleware/middleware.go
service/media/media.go
service/multichain/eth/eth.go
service/multichain/multichain.go
service/multichain/opensea/opensea.go
service/multichain/poap/poap.go
service/multichain/tezos/tezos.go
service/persist/postgres/token_gallery.go
service/persist/token.go
service/persist/token_gallery.go
util/helpers.go

Changes:
- **Changed** processing handler to only process unservable medias
- **Changed** image purging to only images that already exist in the bucket
- **Changed** video thumbnailing to pipe directly into the storage bucket
TODO:

some tez adjustments [GAL-477 GAL-475 GAL-473 GAL-469]

---

service/rpc/rpc.go

Changes:
- **Added** an http fallback to receiving data from arweave
- The issue occurring was that when trying to receive data from the `*goar.Client` (arweave client) using the path that follows the `ar://` prefix of an arweave URI, the client was unable to find anything for a specific [token](https://arweave.net/9bZA99oEuS16nnBdPotlC9HAcTrL-fJau48lKCUBj80/56). Oddly enough though, if you go to `arweave.net/{uri}` the token media was there. I tried every function the arweave client had available with different versions of prefixed and unprefixed URIs for this token and the client could never find it, so this might be an issue with the internals of the client. Given this, I just added a fallback that will try to retrieve the media directly from the arweave HTTP URL and …

arweave fix [GAL-513]

---

db/gen/coredb/batch.go
db/queries/core/query.sql
publicapi/pagination.go
service/media/media.go
service/rpc/rpc.go
util/helpers.go

Changes:
- **Changed** remap paths to remap arweave as well
- **Changed** subquery for owners to limit outside of subquery

hotfix sql subquery

---

service/multichain/poap/poap.go
service/multichain/tezos/tezos.go

Changes:
- **Added** limit defaults so that we can safely set a limit as 0

limit defaults

---

db/gen/coredb/query.sql.go
db/migrations/core/000032_users_wallets_index.down.sql
db/migrations/core/000032_users_wallets_index.up.sql
db/queries/core/query.sql
server/server.go
service/multichain/multichain.go
service/persist/postgres/user.go
service/persist/user.go
service/task/cloudtask.go
tokenprocessing/process.go
tokenprocessing/tokenprocessing.go

Changes:
- **Changed** create users step in refresh tokens in collection step to get all users for wallets up front to avoid expensive queries

get all users up front

---

graphql/resolver/schema.resolvers.go
graphql/resolver/schema.resolvers.helpers.go
publicapi/contract.go
service/task/cloudtask.go
tokenprocessing/process.go
tokenprocessing/tokenprocessing.go

Changes:
- **Changed** throttle time to 12 hours
- **Changed** resolvers to use force refresh if provided

get every 12 hours

---

debugtools/debugtools_common.go
debugtools/debugtools_enabled.go
graphql/resolver/schema.resolvers.helpers.go
publicapi/auth.go
service/auth/auth.go
service/persist/postgres/user.go
service/user/user.go

Changes:
- **Changed** authenticate step to remove universal users so that in any place where a wallet might authenticate with a nonce, we prepare ahead of time by removing the universal user

add address universal delete

---

cmd/notifications_prepop/main.go

Changes:
- **Added** cases for comments, admires, and follow backs in notification prepop script

more cases

---

service/multichain/multichain.go

Fixes the 404 errors we're seeing when refreshing individual tokens.

Fix token process endpoint

---

.dockerignore

Changes:
- **Changed** docker ignore to allow root certs

quick change

---

db/gen/coredb/batch.go
db/gen/coredb/query.sql.go
db/queries/core/query.sql
graphql/generated/generated.go
graphql/model/models_gen.go
graphql/model/remapgen_gen.go
graphql/resolver/schema.resolvers.go
graphql/resolver/schema.resolvers.helpers.go
graphql/schema/schema.graphql
publicapi/user.go

Another bite sized chunk of email progress
Changes:
- **Added** mutations for updating email notification settings and resending verification emails
- **Added** update email

update email, notification settings, and resend verification

---

service/logger/logger.go

Some very minor tweaks to GCP logging
- Adding a `time` field actually clashed with logrus' existing `time` field, so our field got moved to `fields.time`. As it turns out, we can just specify a format for logrus' time field instead of making our own.
- After looking more closely at logrus' `JSONFormatter` options, I realized we could rename the default message field from `msg` to `message`, which is another thing GCP looks for when parsing logs

Fix "time" field clash in logrus, and remap "msg" to "message"

---

graphql/resolver/schema.resolvers.helpers.go

We had to convert these to the value type and then take a reference

Fix casting of notifications in node resolver

---

emails/emails.go
emails/handlers.go
emails/send.go

Changes:
- **Changed** notifications handler to only be in dev env (so it cannot be accessed by http in prod)
- **Added** pubsub subscription for kicking off the notifications email

subscribe to pubsub for notifs

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
emails/handlers.go
emails/send.go
emails/subscriptions.go
graphql/resolver/schema.resolvers.helpers.go
publicapi/notifications.go
publicapi/user.go
service/emails/emails.go
service/notifications/notifications.go

Changes:
- **Added** a new emails endpoint just for updating unsubs by user ID
- **Changed** unseen count to use DB (bug fix)
- **Changed** window for grouping views vs other grouped events

unsub adjustments/bug fixes

---

feed/event.go

Skips saving user created events to the feed because they aren't supported on the global feed and to free up pagination results.

Remove user created events from feed

---

graphql/resolver/schema.resolvers.helpers.go
graphql/schema/schema.graphql
publicapi/user.go

Changes:
- **Added** a validation check on getting users by users IDs for there having to be at least first or last

error on no first or last [GAL-655]

---

docker/docker.go
emails/t__unit_test.go
emails/t__utils_test.go

Changes:
- **Added** basic unit tests for emails service templating

templating test start

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
service/notifications/notifications.go

Changes:
- **Changed** update notif func to tie count to length of actors for action

tie count to length of actors [GAL-698]

---

feed/server.go

Noticed that `UserCreatedEvent` events were gunking up the queue since they're no longer supported. Returning a `200` will treat them as handled so they don't get retried.

Feed- clear unsupported events from queue

---

server/server.go
service/media/media.go
service/multichain/multichain.go
service/multichain/tezos/tezos.go

This PR adds a condition to fallback to objkt in the case where the tzkt API still returns the placeholder metadata for FxHash tokens.

Fix fxhash tokens stuck in "Waiting to be signed" state

---

service/redis/redis.go

Changes:
- **Changed** redis clear db func to just flush one DB

just flush db

---

cmd/allowlist/main.go

Changes:
- **Added** script for turning a list of user IDs into a list of the first ethereum address they each have

allowlist script

---

indexer/indexer.go

Use a different context for RPC calls and saving logs to GCP. The former context is cancellable, whereas the other is not (the root context which doesn't get cancelled).

Indexer - Use different context for RPC calls

---

emails/emails.go
indexer/cmd/root.go
indexer/core.go
indexer/t__utils_test.go
server/server.go
tokenprocessing/tokenprocessing.go
util/helpers.go

Changes:
- **Added** cmd flag for setting which local env file to use

allow running server with env

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
go.mod
go.sum
graphql/generated/generated.go
graphql/schema/schema.graphql
publicapi/admin.go
service/auth/auth.go
service/auth/t__auth_test.go
service/persist/user.go

This PR adds the `EARLY_ACCESS` role which is given to users if they own a membership card based on if a user owns a relevant NFT based on the `tokens` table.

Add Early Access role

---

graphql/generated/generated.go
graphql/model/models_gen.go
graphql/schema/schema.graphql

Changes:
- **Added** `ID` to `MerchToken` type

graphQL ID

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
graphql/generated/generated.go
graphql/model/gqlidgen_gen.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.helpers.go
graphql/schema/schema.graphql
publicapi/merch.go

Changes:
- **Changed** `MerchToken` to implement node to have correct ID generation

merch token implements node

---

cmd/merch_prepop/main.go

Changes:
- Title captures it all

more timeout, ssl env, good logs

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
graphql/resolver/schema.resolvers.go
publicapi/admin.go
publicapi/user.go
server/server.go

**Changes**
* Check if email is verified before granting early access role
* Moved `GetUserRolesByUserID` to user api instead of admin

[GAL-1704] Check if email is verified for early access

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql

Changes:
- **Changed** unique number check from 0 to 1 (typo)
- **Added** deleted check to galleries position unique check

update sql typo

---

emails/emails.go
emails/verify.go
publicapi/user.go

Changes:
- **Changed** list id
- **Changed** where list addition occurs (moved to the end of email verification so it does not block the actual result of verification)
TODO:

list id and move list add

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql

Changes:
- **Changed** create collection query to set version to 1

set version

---

db/migrations/core/000051_user_experiences.down.sql
publicapi/feed.go

Increasing trending user report size from 20 to 24.

Increase user trending to 24

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
graphql/generated/generated.go
graphql/generated_test.go
graphql/graphql_test.go
graphql/model/models_gen.go
graphql/model/remapgen_gen.go
graphql/resolver/schema.resolvers.go
graphql/schema/schema.graphql
graphql/testdata/operations.graphql
publicapi/collection.go

Changes:
- **Added** mutation for moving a collection to a new gallery
- **Added** test for this functionality

Move collection

---

util/helpers.go

Changes:
- **Changed** generic util func to use for loops correctly

stupid go for loops

---

secrets/dev/backend-env.yaml
secrets/dev/feed-env.yaml

Changes:
- **Changed** env vars that need to stay in sync for feed buffering on dev

buffer secs and window to same amount

---

db/migrations/core/000057_drop_unused_tables.up.sql
service/persist/postgres/auth.go

We don't use any of these tables! I've been meaning to drop them for a while. Let's drop them now!

Drop unused tables

---

service/auth/auth.go

Changes:
- **Updated** authenticate for magic link to return a more generic error for not found users

more generic err for auth

---

service/media/media.go

This PR adds back tracing to the storage client so we can see trace reports on Sentry. Tested by running syncs and confirming that new objects are written to the dev token bucket.

Add back tracing to storage

---

event/event.go
secrets/dev/backend-env.yaml
secrets/prod/backend-env.yaml
server/server.go

Changes:
- **Changed** feed bot send to only use not nil feed events to prevent panics

only send to feedbot if not nil

---

publicapi/card.go
server/server.go

Changes:
- **Changed** default twitter redirect URI to localhost
- **Changed** card address to the already created env var

default twitter and fix card address

---

secrets/dev/backend-env.yaml

Changes:
- **Added** twitter env vars to dev

twitter env on dev

---

graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.helpers.go
graphql/schema/schema.graphql

Changes:
- **Added** `newCollectorsNote` to the created event and groups new collectors note first at the created step

add new collectors note to collection created

---

db/gen/coredb/query.sql.go
db/migrations/core/000060_add_gallery_update_to_gallery_edit_idx.up.sql
db/queries/core/query.sql

Adds "GalleryInfoUpdated" action to trending user criteria.

Add gallery edit to trending user criteria

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
go.mod
go.sum
graphql/generated/generated.go
graphql/generated_test.go
graphql/graphql_test.go
graphql/model/models_gen.go
graphql/model/remapgen_gen.go
graphql/resolver/schema.resolvers.go
graphql/schema/schema.graphql
graphql/testdata/operations.graphql
publicapi/socials.go

Changes:
- **Added** a mutation for disconnecting a social account

disconnect social

---

go.mod
go.sum
graphql/generated/generated.go
graphql/generated_test.go
graphql/model/models_gen.go
graphql/schema/schema.graphql

Changes:
- **Added** some new user experience enum values

new experiences

---

secrets/dev/backend-env.yaml
secrets/prod/backend-env.yaml

Changes:
- **Added** twitter auth secrets

new secrets

---

cmd/data/farcaster/farcaster.go
cmd/data/farcaster/gallery_cards/farcaster.go
cmd/data/lens/lens.go
util/helpers.go

Changes:
- **Removed** concurrency (for rate limiting sake)
- **Added** new return fields 
- **Fixed** bugs

improve data scripts

---

cmd/migrate/main.go

Setting the default script role to `gallery_migrator`

Set default migrate role

---

indexer/metadatas.go
indexer/nfts.go
secrets/prod/local/app-prod-tokenprocessing.yaml
secrets/prod/tokenprocessing-env.yaml

Changes:
- **Changed** indexer host for token processing to the correct live one

wrong indexer host

---

indexer/nfts.go

There are a handful of contracts that have custom metadata handlers (CryptoPunks, ENS, etc). For those contracts, it's fine if there's no token URI data since we can pull the metadata in other ways. For CryptoPunks, there isn't a `tokenURI` function to call anyways.

Fix missing CryptoPunk

---

secrets/dev/backend-env.yaml
secrets/prod/backend-env.yaml
server/server.go

Changes:
- **Added** feedbot url to backend

set feedbot url on backend

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
publicapi/socials.go
secrets/dev/local/app-dev-backend.yaml

Changes:
- **Changed** connection count query to match fetching query

match count with fetch query

---

graphql/generated/generated.go
graphql/generated_test.go
graphql/model/models_gen.go
graphql/model/remapgen_gen.go
graphql/resolver/schema.resolvers.go
graphql/resolver/schema.resolvers.helpers.go
graphql/schema/schema.graphql
publicapi/socials.go
service/twitter/twitter.go

Changes:
- **Added** a new error that signals when a user's refresh token is no longer valid
- Requires the frontend to support redirecting to the connect login flow again

possibly invalid refresh token

---

cmd/twitter_prepop/main.go

Changes:
- **Added** script for prepopulating twitter followers to random users for testing purposes

script for populating twitter followers

---

db/gen/coredb/models_gen.go
db/gen/coredb/token_gallery.sql.go
db/queries/core/token_gallery.sql
indexer/nfts.go
indexer/plugin.go
secrets/local/local/app-local-tokenprocessing.yaml
service/membership/alchemy.go
service/multichain/eth/eth.go
service/multichain/multichain.go
service/persist/postgres/token.go
service/persist/postgres/token_gallery.go
service/persist/token.go
service/persist/token_gallery.go

Changes:
- **Changed** indexer to no longer return any media
We currently don't use the indexer for media but there is a possibility that the indexer could return some outdated media that would override media created by token processing.

use dimensions when available

---

graphql/resolver/schema.resolvers.helpers.go

Changes:
- **Changed** env var

update env var

---

service/multichain/alchemy/alchemy.go
util/numbers.go

Changes:
- **Added** token ID conversion

correct token id madness

---

event/event.go
feed/event.go
publicapi/collection.go
publicapi/gallery.go
publicapi/publicapi.go
publicapi/socials.go
service/multichain/alchemy/alchemy.go
service/multichain/multichain.go
service/persist/contract_gallery.go
service/persist/event.go
service/persist/postgres/contract_gallery.go
service/socialauth/socialauth.go
util/helpers.go

Changes:
- **Added** a workaround for question mark contract names

workaround for question marks

---

indexer/indexer.go

Changes:
- **Removed** a channel that was blocking endlessly because there was no receiver

remove chan that was blocking listening and being unused

---

service/multichain/alchemy/alchemy.go

Changes:
- **Added** workaround for major alchemy bug

workaround for order by bug

---

service/multichain/infura/infura.go

Changes:
- **Added** infura metadata so that infura can retrieve metadata  as well as the indexer

infura metadata

---

secrets/dev/local/app-dev-tokenprocessing.yaml
service/multichain/alchemy/alchemy.go
service/multichain/infura/infura.go

Changes:
- **Added** pagination fix for url cursors

fix pagination with URLs and cursors

---

service/media/media.go
service/multichain/infura/infura.go
service/rpc/rpc.go
tokenprocessing/process.go

Changes:
- **Added** a fallback to opensea if we cannot get the reader for a given token at the media processing step

opensea media fallback

---

service/multichain/infura/infura.go

Changes:
- **Changed** token metadata request to request the latest metadata

resync infura NFT API

---

graphql/generated/generated.go
graphql/generated_test.go
graphql/model/models_gen.go
graphql/schema/schema.graphql

Added new announcement Gallery Select

Gallery Select User Experience

---

secrets/prod/backend-env.yaml
secrets/prod/local/app-prod-tokenprocessing.yaml
server/server.go
service/multichain/eth/eth.go
service/multichain/tezos/tezos.go
service/task/cloudtask.go

Changes:
- **Removed** any code calling the `wallet-validate` queue
- **Changed** task for token processing to use the max request time (30 min)

remove code calling unused queues, increase token process deadline

---

service/media/media.go
service/persist/token.go
service/rpc/rpc.go

Changes:
- **Added** support for base64 png image media processing

base64 png support

---

secrets/local/local/app-local-backend.yaml
service/multichain/alchemy/alchemy.go
service/multichain/infura/infura.go
service/multichain/multichain.go

Changes:
- **Changed** providers (except for opensea) to not return fallback media
- **Changed** fallback media determination step to ensure that the valid fallback media is used for the token despite using another providers other token fields

ensure opensea fallback is used

---

service/rpc/rpc.go

Changes:
- **Added** an attempt to use different base64 decoding schemes for metadata like we do for raw data
Future todo: Share more code here

attempt different encodings

---

.github/workflows/openai-pr-reviewer.yml

**Release Notes**
- New Feature: Added a GitHub workflow that uses an OpenAI-based bot to review pull requests and pull request review comments.
> "Code reviews made easy,
> With OpenAI's help, it's breezy.
> Bugs and issues, we'll catch them all,
> Thanks to this new bot, we'll never fall."

OpenAI PR Reviewer

---

util/retry/retry.go

- New Feature: Added support for retrying on status code `429` in GCS.
- Refactor: Refactored `RetryQueryWithRetry` to use `RetryFunc`.
- Refactor: Added the original error to retry error.
- Refactor: Added a custom error type `ErrOutOfRetries` and modified `RetryRequestWithRetry` and `RetryFunc` functions to return this error type instead of the previous `errors.New("tried too many times")`.
- Chore: Improved reliability and maintainability of the code.
> "Retry, retry, we will not cry.\
> 429 won't make us sigh.\
> With custom errors and refactored code,\
> Our reliability has surely glowed."

Add retry error

---

.github/workflows/openai-pr-reviewer.yml

**Release Notes**
- New Feature: Added a new input parameter `summary_only` to a job in the workflow file, providing an option to only generate a summary of changes instead of running the entire job.
> "A new input parameter has arrived,
> Summary-only option is now alive.
> Workflow flexibility has increased,
> With this change, PR reviews are eased."

Summary only for AI bot

---

service/media/media.go
tokenprocessing/tokenprocessing.go

Release Notes:
- Bug fix: Updates error messages in `service/media/media.go` and `tokenprocessing/tokenprocessing.go` to provide more information about the errors. The changes do not affect the logic or functionality of the code.
> "Errors, errors, go away,
> With better messages, we'll save the day.
> Media and tokens, now more clear,
> Our users will have nothing to fear."

Update Sentry error message and title

---

.github/workflows/deployer.yml

Bug fix: Fixed a data race issue in the `process` function of `my_module.py`. 
> "Data races no more, 
> Our code is now secure. 
> With this fix in place, 
> We can now keep up the pace."

Autodeploy graphql gateway

---

.github/workflows/deployer.yml
.github/workflows/openai-pr-reviewer.yml

Release Notes:
- New Feature: Added three new jobs to the deployer workflow for deploying a GraphQL gateway to dev and prod environments. 
> "Deploying code with ease,
> GraphQL gateway now a breeze.
> Jobs added, bugs evaded,
> Deployments safe, success celebrated."

AI bot take 3: disable_review

---

graphql/resolver/schema.resolvers.helpers.go

Changes:
- **Changed** fallback resolver to always include fallback media

always have fallback

---

secrets/dev/local/app-dev-backend.yaml
secrets/local/local/app-local-backend.yaml
service/multichain/alchemy/alchemy.go
service/persist/postgres/user.go

**Changes**
* Adds check to catch when the user owns no merch tokens
* Replaces the underlying API endpoint of the Alchemy provider's `GetTokensByContractAddressAndOwner` method from /getNFTsForCollection to /getNFTs. The former requires fetching the entire collection and then fetching the owner of each token to see if it matches the user's address which was causing slow load times
* Adds `RPC_URL` to local env

Merch store fix

---

tokenprocessing/tokenprocessing.go

This was causing the service to panic if the assert failed

Check Sentry spam interface assertion

---

cmd/reprocess/main.go

Changes:
- **Added** metrics reporter to reprocess

use metrics in reprocess script

---

secrets/prod/backend-env.yaml

Whoops forgot to actually add this

Add v3 url to backend

---

db/gen/coredb/models_gen.go
db/migrations/core/000085_add_migration_dashboard_view.up.sql

Small change to the dashboard view so that sqlc can generate a model for it.

Fix dashboard query so sqlc can generate models

---

db/migrations/core/000086_unschedule_migration_refresh.up.sql
db/migrations/core/000087_add_tokenprocessing_dashboard_idxs.up.sql
db/migrations/core/000088_add_media_validation_rules.up.sql

Changes
* Unschedules the migration view because we're done with the migration 🚀 
* Adds indexes to `token_medias`
* Adds validation table for the dashboard

Add dashboard indexes and tables

---

service/multichain/multichain.go

Changes:
- **Added** owner address temporarily to refresh request to support v2 token processing

backwarts compatibility for refresh v2

---

event/event.go

Caught this error via Sentry. `UpdateFeedEventCaptionByGroup` returns a `FeedEvent`, not a `*FeedEvent`, which causes a type assertion error later on when we try to assert `*FeedEvent`.
This PR fixes the line in question to return `*FeedEvent`. It seems we always expect `handleImmediate` and `handleGroup` to return `*FeedEvent` types, so I also changed the signature of feed handler methods to use `*FeedEvent` instead of `interface{}` so the compiler will catch similar errors in the future.

Fix invalid type assertion

---

graphql/plugin/remapgen/remapgen.go
graphql/resolver/schema.resolvers.go
tokenprocessing/media.go

Changes:
- **Added** thumbnail to hic tokens

use thumbnail uri

---

tokenprocessing/media.go

Changes:
- **Added** priority for svgs

prioritize svg for primary objects

---

tokenprocessing/media.go

Turns off retrying to write data to the token bucket. The storage client itself does have a retry policy, but this should reduce the number of retries alone by 12x.

Turn off write retries

---

service/multichain/opensea/opensea.go
service/persist/token_processing_jobs.go
tokenprocessing/pipeline.go
tokenprocessing/process.go

**Changes**
* Catches OpenSea expired API key
* Adds parent pipeline step to logs
* Adds pipeline step `CreateMedia`

More pipeline tweaks

---

service/multichain/multichain.go
tokenprocessing/process.go

Chore - lower log lines to warn

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql

Query was still using the v2 media, updated to use v3

Fix gallery previews

---

tokenprocessing/media.go

Changes:
- **Changes** correct object type

correct object type

---

go.mod
go.sum
tokenprocessing/media.go
util/helpers.go

Changes:
- **Added** log messages for reads/writes to GCP

print writes and reads for reader

---

tokenprocessing/media.go

Changes:
- **Removed** `thumbnail_uri` from hic et nunc tokens (black circle)

remove thumbnail uri for hic

---

service/multichain/multichain.go
tokenprocessing/media.go

Same PR as https://github.com/gallery-so/go-gallery/pull/1005

Pipeline fixes part 4

---

db/migrations/core/000091_add_token_media_id_idx.up.sql

Speeds up the token QC dashboard

Add token_media_id idx

---

service/multichain/multichain.go
service/persist/postgres/token_gallery.go

Fixes a bug where syncing would sync all of a user's tokens instead of only the new ones

Fix syncing all tokens

---

server/inject.go
server/wire_gen.go
service/multichain/eth/eth.go
service/multichain/multichain.go

Changes:
- **Added** multichain interfaces and implementations for fetching all contracts owned by a given owner address from the indexer server

fetch contracts by owner

---

graphql/graphql_test.go
graphql/resolver/schema.resolvers.helpers.go

Apparently, we were flipping the height and width for awhile now!

Flip height and width

---

secrets/local/local/app-local-backend.yaml
service/multichain/multichain.go

Changes:
- **Added** priority checking to fetching metadata for result consistency

prioritize metadata

---

service/multichain/multichain.go

Changes:
- **Changed** get contracts owned by address to a sync that first checks for providers that return contracts owned by an address (just indexer), then uses the already in place sync for getting contracts with parent/child relationships (opensea)
- Right now the function for getting parent/child relationships is called `SyncTokensCreatedOnSharedContracts` but it currently does not do any syncing for tokens. Will it in the future?
- I opted for not implementing a `GetContractsOwnedByAddress` for the `*opensea.Provider` because that functionality is already encompassed in `GetChildContractsCreatedOnSharedContract`. I feel like it makes sense to do this to separate which providers only know the creator of a contract and which providers are capable of determining …

combine sync for parent/child with just parents

---

graphql/generated/generated.go
graphql/generated_test.go
graphql/model/models.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.go
graphql/resolver/schema.resolvers.helpers.go
graphql/schema/schema.graphql
publicapi/gallery.go
service/mediamapper/mediamapper.go
service/persist/collection.go

Changes:
- **Added** token settings for high definition at the graphQL and DB level
- **Added** fields to preview URL set for high definition variations

high def fields

---

graphql/resolver/schema.resolvers.helpers.go

Changes:
- **Changed** media mapper options to append not set so as not to send nil values in slice

append not set

---

graphql/graphql_test.go

Changes:
- **Added** a small test for syncing multichain

small test for multichain syncing

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.go
graphql/schema/schema.graphql
publicapi/user.go
secrets/local/local/app-local-backend.yaml

**Changes**
* Moves `ensProfileImageByUserId` query to `potentialEnsProfileImage` field on `GalleryUser`
* Fixes bug where non-ethereum addresses are checked for PFPs

ENS pfp schema changes

---

graphql/graphql_test.go
graphql/resolver/schema.resolvers.go
graphql/stub_test.go
tokenprocessing/pipeline.go

**Changes**
* Fixes broken sync tests
* Turns back on tokenprocessing tests that were turned off during the v3 migration

Fix sync test and turn back on tokenprocessing tests

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
graphql/graphql_test.go

Changes:
- **Changed** SQL preview query to check `token_medias` media fields instead of `tokens` db media fields (which are empty now)

preview fix

---

service/media/media.go
tokenprocessing/media.go

Fixes issue where gzipped objects aren't unzipped by GCP: https://cloud.google.com/storage/docs/transcoding
**Changes**
* Adds `Content-Encoding: gzip` to gzipped objects
* Adds options to `newObjectWriter`: `WithCustomMetadata`, `WithContentEncoding`, `WithContentType`
* Changes `contentType` from a string pointer to a string since GCP treats empty string as no content type

Add Content-Encoding header to gzip objects

---

cmd/contract_refresh_opensea/main.go
db/gen/coredb/contract_gallery.sql.go
db/queries/core/contract_gallery.sql
graphql/graphql_test.go
service/multichain/multichain.go
service/multichain/opensea/opensea.go
service/multichain/tezos/objkt.go
service/persist/postgres/contract_gallery.go

Changes:
- **Changed** contract dedupe to check for all metadata fields across all contracts received
- **Added** collection image url support to opensea and objkt providers
- **Added** script for refreshing contracts

refresh and fetch description and profile image

---

graphql/generated/generated.go
graphql/generated_test.go
graphql/schema/schema.graphql
publicapi/token.go
secrets/dev/backend-env.yaml
secrets/dev/local/app-dev-backend.yaml
secrets/dev/local/app-dev-tokenprocessing.yaml
secrets/dev/tokenprocessing-env.yaml
secrets/local/local/app-local-backend.yaml
secrets/local/local/app-local-tokenprocessing.yaml
secrets/prod/backend-env.yaml
secrets/prod/local/app-prod-tokenprocessing.yaml
secrets/prod/tokenprocessing-env.yaml
server/inject.go
server/server.go
server/wire_gen.go
service/multichain/multichain.go
service/multichain/zora/zora.go
service/persist/token.go

Changes:
- **Added** token syncing and creator token/contract syncing for a new chain, `ChainZora`, in a new `*zora.Provider` multichain provider
- **Added** `Zora` to graphQL
- **Added** address mapping of eth address to zora chain so that you can use any evm address to refresh zora tokens

syncing tokens and created contracts/tokens

---

publicapi/token.go
service/multichain/zora/zora.go

Changes:
- **Added** support for nil transports in zora custom transport

support nil transport for custom transport

---

cmd/contract_refresh_opensea/main.go
service/multichain/multichain.go

Changes:
- **Added** profile pic field to contract in dedupe, should have been there so was upserting empty urls

include profile pic

---

graphql/resolver/schema.resolvers.go
service/multichain/alchemy/alchemy.go

Changes:
- **Changed** media resolver to use syncing if there is no media

include syncing if fallback exists

---

graphql/resolver/schema.resolvers.go
graphql/resolver/schema.resolvers.helpers.go

Changes:
- **Changed** resolvers for collection tokens to correctly use the collection ID in the helper data

collection tokens need collectionID

---

graphql/resolver/schema.resolvers.go

Only refresh gallery users by default for community syncs.

Only sync users by default

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql

Changes:
- **Added** check for universal users in optimistic sync so we don't optimistically sync them.

no universal users for optimistic

---

indexer/hook.go
tokenprocessing/process.go

Changes:
- **Added** logs to token processing and indexer for tracking usage of optimistic syncing

some logs for tracking optimistic syncing

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
publicapi/feed.go

Changes:
* Replaces the query that pulls recent feed entities into a more performant one
* Refactors the feed pagination query to not use `LIMIT` by slicing the ids based on the cursor and limits before - this also means there are less IDs that the db has to join on
This should be faster in theory, but it was hard to get consistent timings locally. Gonna play around on dev after merged

Optimize trending feed query

---

graphql/resolver/handlers.go
service/logger/logger.go

Will test on dev to make sure this works

Fix logging: no more struct keys

---

publicapi/feed.go

Noticed I totally busted pagination with my most recent changes to feed pagination, this fixes it.

Fix feed paginator

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
graphql/fixture_test.go
graphql/generated/generated.go
graphql/generated_test.go
graphql/graphql_test.go
graphql/resolver/schema.resolvers.go
graphql/schema/schema.graphql
graphql/testdata/operations.graphql
publicapi/feed.go

This PR adds `includePosts` param to the trending feed, the global feed, and the user activity feed.

Add include posts param

---

publicapi/feed.go
secrets/dev/local/app-dev-backend.yaml

This PR handles an edge case where the cursor was first fetched to include posts, but then following page requests exclude posts.

Handle filter posts in feed cursor

---

indexer/indexer.go

Changes:
- **Added** token in channel to indexer plugins (should've been there)
Need to abstract this away so we don't keep making this mistake but I am working on more important things right now so will do this after, maybe fix it week.

track tokens

---

service/recommend/koala/koala.go
service/recommend/koala/koala_common.go
service/recommend/koala/koala_norec.go
service/recommend/recommend.go
service/recommend/recommend_common.go
service/recommend/recommend_norec.go

This PR adds the `norec` build tag which builds the project with a stubbed-out recommender and koala algorithm. You can use it with the command below:
```
go run -tags debug_tools,norec cmd/server/main.go dev
```

Add norec build tag

---

cmd/farcaster_backfill/main.go
graphql/generated/generated.go
graphql/generated_test.go
graphql/model/models_gen.go
graphql/schema/schema.graphql
publicapi/user.go
secrets/dev/backend-env.yaml
secrets/dev/backend-sandbox-env.yaml
secrets/dev/local/app-dev-backend.yaml
secrets/local/local/app-local-backend.yaml
secrets/prod/backend-env.yaml
server/server.go
service/farcaster/neynar.go
service/persist/user.go

Changes:
- **Added** backfill script for farcaster
- **Added** types for new social account types (farcaster/lens)

types and backfill

---

secrets/dev/tokenprocessing-env.yaml

Changes:
- **Added** env vars for pubsub on dev tokenprocessing

dev env vars

---

cmd/refresh/refresh.go
service/notifications/notifications.go
tokenprocessing/tokenprocessing.go

Changes:
- **Added** set default for required pubsub env variable

set default env

---

docker/tokenprocessing/Dockerfile
event/event.go
service/notifications/notifications.go
service/rpc/rpc.go

Changes:
- **Added** handlers for the new action types for admiring and commenting on posts

track new notifications for admires and comments posts

---

Makefile
docker/tokenprocessing/Dockerfile

Changes:
- **Reverted** tokenprocessing docker image change since it did not affect rasterizing

back to bullseye

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.go
graphql/schema/schema.graphql
publicapi/user.go

This PR adds `isMemberOfCommunity` field to the GalleryUser type:
```graphql
type GalleryUser {
isMemberOfCommunity(communityID: DBID!): Boolean! @goField(forceResolver: true)
}
```

[GAL-3858] add isMemberOfCommunity

---

graphql/dataloader/dataloaders.go
graphql/dataloader/dataloaders.helpers.go
graphql/resolver/schema.resolvers.go

Modifies the batch settings for the tokens and contracts loader. Also adds options to configure the default dataloader settings.

Small dataloader changes for feed

---

service/recommend/userpref/personalize.go

Fix to actually update the cached data if it's stale.

Curated feed - fix update loop

---

indexer/metadatas.go
secrets/dev/local/app-dev-backend.yaml
service/eth/eth.go
tokenprocessing/media.go

Changes:
- **Removed** rasterizing from punks

no rasterize punks

---

Makefile
cmd/userpref/main.go
service/recommend/userpref/personalize.go

Adds a cloud job to run the curated update job. Merging this PR in so that GitHub can build the image. It's probably gonna take a few tries on dev to get it working.

Add curated job

---

Makefile
cmd/userpref/main.go
docker/userpref/Dockerfile
graphql/graphql_test.go
graphql/stub_test.go
secrets/dev/local/app-dev-userpref-upload.yaml
secrets/dev/makevars.yaml
secrets/dev/userpref-upload.yaml
secrets/prod/makevars.yaml
secrets/prod/userpref-upload.yaml
service/multichain/opensea/opensea.go

More fixes from testing on dev.

Fixes to curated job

---

cmd/farcaster_backfill/connections/main.go
db/gen/coredb/query.sql.go
db/migrations/core/000103_external_social_connections.up.sql
db/queries/core/query.sql

Changes:
- **Fixed** insert external connection query

modify query

---

db/gen/coredb/recommend.sql.go
db/queries/core/recommend.sql
publicapi/feed.go
service/recommend/userpref/personalize.go

Changes:
* Curated feed is now scored in two passes: first by popularity, then by relevance
* Adds farcaster external graph
* Modifies relevance score to use the square of the score

Curated Feed updates

---

publicapi/feed.go

Changes:
* Even shorter half-life
* Boost posts less than fours old

Add boost for new posts

---

server/inject.go
server/wire_gen.go
service/multichain/fallback.go
service/multichain/zora/zora.go

Changes:
- **Added** metadata fetching for zora and sync eval fallback providers

zora metadata, sync eval metadata

---

secrets/dev/tokenprocessing-env.yaml
secrets/prod/tokenprocessing-env.yaml
tokenprocessing/tokenprocessing.go

Changes:
- **Added** tez api url to `tokenprocessing`
- **Added** other necessary metadata fetching URLs to `tokenprocessing`

api url for tez

---

publicapi/feed.go
service/recommend/userpref/personalize.go

**Changes:**
Scoring now uses an ensemble approach:
1. The most personalized events are found for the user, and then ranked by engagement
2. The most engaged events are found, and then ranked by personalization for the user
3. The two lists are interleaved by taking the average rank of the event, resulting in events appearing in both lists to be boosted
**Misc changes**
* Uses the inverse of the path length so that users you already follow score higher than further edges
* Events less than 6 hours old have their engagement scores doubled
* Increase bfs search to 4 from 3

More curated feed changes

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
graphql/generated/generated.go
graphql/resolver/schema.resolvers.go
graphql/schema/schema.graphql
publicapi/feed.go

Changes:
Adds `includePosts` param to the personal feed
```graphql
type Viewer {
feed(
before: String
after: String
first: Int
last: Int
includePosts: Boolean! = false
): FeedConnection @goField(forceResolver: true)
}
```

Add includePosts to personal feed

---

graphql/resolver/schema.resolvers.helpers.go
publicapi/contract.go

Changes:
- **Added** shadowed variable to for loop for generating posts in a community page so that we can use pointer values safely

for loop post values

---

db/gen/coredb/gallery.sql.go
db/gen/coredb/query.sql.go
db/queries/core/gallery.sql
db/queries/core/query.sql
service/persist/postgres/contract_gallery.go

Changes:
- **Added** coalescing to thumbnail preview URLs so that images with no thumbnails can be used as well

coalesce thumbnail for image medias

---

db/gen/coredb/contract_gallery.sql.go
db/queries/core/contract_gallery.sql
server/inject.go
server/wire_gen.go
service/multichain/alchemy/alchemy.go
service/multichain/eth/eth.go
service/multichain/fallback.go
service/multichain/multichain.go
service/multichain/opensea/opensea.go
service/multichain/poap/poap.go
service/multichain/tezos/tezos.go
service/persist/postgres/contract_gallery.go

Changes:
- **Added** coalescing to contract upsert statements so that fields don't get replaced when empty
- **Added** more return fields to providers for contract metadata
- **Added** contract fetching to the refresh contract

coalesce contracts

---

server/inject.go
server/wire_gen.go
service/multichain/multichain.go
service/multichain/reservoir/reservoir.go

Changes:
- **Added** refresh before fetch metadata on base `reservoir` provider

refresh tokens on fetch metadata

---

service/multichain/reservoir/reservoir.go

Changes:
- **Added** query set for base reservoir requests

properly set query in req

---

publicapi/feed.go

Fixes the issue where deleted posts prevent retrieving the trending and curated feed. Deleted posts are possible because a post can be deleted in between refreshes of the materialized feed view. This PR refactors `loadFeedEntities` to handle deleted feed entities.

Handle feed deletes

---

graphql/generated/generated.go
graphql/model/models_gen.go
graphql/schema/schema.graphql
publicapi/feed.go

Fixes
* Adds `ErrCommunityNotFound` to `PostComposerDraftDetailsPayloadOrError`
* Shorter wait between retries for finding a user's token

Share to gallery fixes

---

graphql/generated/generated.go
graphql/generated_test.go
graphql/model/models_gen.go
graphql/schema/schema.graphql

Added `UpsellBanner` key to user experience for frontend PR: https://github.com/gallery-so/gallery/pull/1926

Add user experience for banner

---

db/gen/coredb/batch.go
db/queries/core/query.sql
graphql/dataloader/dataloaders.go
graphql/dataloader/dataloaders.helpers.go
graphql/resolver/schema.resolvers.go
publicapi/token.go

Removing the displayable criteria for posts so that tokens can still be viewed.

Remove displayable filter on posts

---

graphql/fixture_test.go
graphql/graphql_test.go
graphql/resolver/schema.resolvers.go
publicapi/feed.go

Always show posts and exclude feed events from the Trending and For You feeds

Always include posts on Trending and For You feeds

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
event/event.go
feedbot/feedbot.go
feedbot/handler.go
feedbot/server.go
publicapi/collection.go
publicapi/feed.go
publicapi/gallery.go
publicapi/interaction.go
publicapi/token.go
publicapi/user.go
secrets/dev/backend-env.yaml
secrets/dev/feedbot-env.yaml
secrets/dev/local/app-dev-backend.yaml
secrets/prod/backend-env.yaml
secrets/prod/feedbot-env.yaml
server/server.go
service/persist/event.go
service/persist/postgres/event.go
service/task/cloudtask.go
tokenprocessing/handler.go
tokenprocessing/process.go
tokenprocessing/tokenprocessing.go

**Changes**
* Updates feedbot to posts to Slack via a task queue
* Minor refactoring of `events`

Add slackbot

---

secrets/dev/tokenprocessing-env.yaml
secrets/prod/tokenprocessing-env.yaml
tokenprocessing/process.go
tokenprocessing/tokenprocessing.go

Changes:
- **Added** support for multiple optimistic sync chains (multiple webhooks)

secrets and handler

---

feedbot/server.go
graphql/resolver/schema.resolvers.go
service/eth/eth.go
tokenprocessing/process.go
util/retry/retry.go

**Changes**
* Slackbot now shows posts with no captions
* `potentialEnsProfileImage` field now returns `null` instead of an error if a user has no ENS domain or doesn't have an avatar record set
* Fixes Alchemy spam job by deduping contracts before insert

Fix it week part 2

---

graphql/dataloader/dataloaders.helpers.go
publicapi/feed.go
publicapi/pagination_test.go
service/multichain/opensea/opensea.go
service/persist/postgres/collection.go
service/tokenmanage/tokenmanage.go
tokenprocessing/handler.go
tokenprocessing/process.go

**Changes**
* Reduce non-prohibition retries to 4
* Deletes some dead code

Reduce tokenprocessing retries

---

db/gen/coredb/query.sql.go
db/gen/coredb/recommend.sql.go
db/queries/core/query.sql
db/queries/core/recommend.sql
publicapi/feed.go
publicapi/pagination.go

**Changes**
* Trending feed now has a week-long lookback (same as For You feed)
* Fixes bug where the Trending Feed would occasionally return no posts when logged out
* Removes waterfall that occurs from needing to score posts firsts and then fetching the high scored posts - made possible because we now only include posts in the Trending and For You feeds, allowing us to embed posts and data needed to score them in a single query

Fix it week part 3 - Feed refactoring

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
go.mod
go.sum
publicapi/feed.go
publicapi/user.go

**Changes**
* Add count to the User Feed
* Simplify the User Feed query since it only includes posts now

Add count to user feed

---

graphql/resolver/schema.resolvers.go

Changes:
- **Changed** order of mention source check

reorder checks so comment source returns

---

autosocial/handler.go
docker-compose.yml
publicapi/user.go
secrets/local/local/app-local-autosocial.yaml
secrets/local/local/app-local-backend.yaml
service/farcaster/neynar.go
service/socialauth/socialauth.go

Changes:
- **Changed** local neynar API key and task queue
- **Added** logs

fix local key/task queue, logs

---

graphql/resolver/schema.resolvers.go

I switched `MediaByTokenID` operations over to `MediaByMediaID` so we can benefit from caching media objects by their IDs. This inadvertently changed some behavior: when a media ID is empty, looking it up by tokenID would return `ErrMediaNotFound`, but looking it up by mediaID returns a validation error (because the mediaID is empty, and looking up media requires a non-empty ID).
This PR tweaks the lookups slightly, such that attempting to resolve the `Media` field of a token with an empty `mediaID` continues to return `ErrMediaNotFound` as it previously had.

Fix empty media ID validation errors

---

service/persist/postgres/event.go

Changes:
- **Changed** event dispatching for contract events to correctly insert with all the required fields (mentions of communities and posting other user's works)

contract event fill out

---

emails/emails.go
secrets/dev/autosocial-env.yaml
secrets/prod/autosocial-env.yaml

Changes:
- **Changed** sops int vars to string
- **Added** default cloud project to emails

fix failing deploys

---

cmd/main.go
service/multichain/zora/zora.go

Changes:
- **Added** correct query param to token query metadata in zora
- **Added** new fallback for zora that uses what they use for their thumbnails on their website

fix token query and add better fallback

---

cmd/refresh/refresh.go
server/inject.go
server/wire_gen.go
service/multichain/multichain.go
service/multichain/zora/zora.go

Changes:
- **Added** an implementation for descriptor fetching so token names and descriptions can be updated during a refresh and refreshes can more completely succeed

zora descriptors fetcher

---

cmd/refresh/refresh.go
service/multichain/zora/zora.go

Changes:
- **Added** a step to zora token conversion to put media URLs in metadata since they no longer exist there

find media urls from media carousel

---

db/gen/coredb/batch.go
db/gen/coredb/query.sql.go
db/queries/core/query.sql

PR removes spam contracts from "Also holds..." on a profile

Exclude spam from "Also holds..."

---

service/notifications/notifications.go

Because push notification errors aren't fatal, we've historically just logged them (but not returned them). This PR adds a little more context via error wrapping (so errors don't just show up in Sentry as `no result rows in set`) and reports them to Sentry.

Report more push notification errors to Sentry

---

graphql/resolver/schema.resolvers.helpers.go
service/multichain/alchemy/alchemy.go
service/multichain/eth/eth.go
service/multichain/multichain.go
service/multichain/opensea/opensea.go
service/multichain/reservoir/reservoir.go
service/multichain/tezos/objkt.go
service/multichain/tezos/tezos.go
service/multichain/zora/zora.go

Changes:
- **Added** more checks for finding the creator address of a contract, often coalescing multiple fields on API responses and DB results

more checks for including creator addresses

---

cmd/refresh/refresh.go
service/notifications/notifications.go

Changes:
- **Changed** push notification notif type checker to return true for mention notif types

true for push notifications for mentions

---

service/notifications/notifications.go

**Old**
you received a new [token] token.
**New**
You just collected [insert token]. Tap to share now.

Update token received notifications copy

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
service/notifications/notifications.go

Changes:
- **Added** a `DISTINCT` clause to the first post insert... not sure why but it works

add distinct clause to first post insert

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql

Changes:
- **Changed** the distinct clause for inserting first post notifs to ensure no duplicates per user

change distinct clause

---

db/gen/coredb/recommend.sql.go
db/queries/core/recommend.sql
publicapi/feed.go

This PR boost post made by Gallery by 1) bumping up the relevance of the post and 2) decreasing the rate of fall-off over time, which is easier to see with the visual below.
The combined effect of these two should make gallery posts stick around longer/seen by more people!

[GAL-4769] Boost Gallery posts

---

publicapi/feed.go

Only want what to show whats trending

Remove freshness boost from trending

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
service/notifications/notifications.go

Changes:
- **Added** row number to the query for first post notifs to ensure uniqueness per follower

use row numbers to ensure uniqueness

---

feedbot/server.go

Handle no name contracts on the slack channel

Handle no-named contracts

---

db/gen/coredb/batch.go
db/gen/coredb/query.sql.go
db/queries/core/query.sql
service/multichain/multichain.go
service/multichain/tezos/tezos.go
service/multichain/zora/zora.go

Changes:
- **Changed** creator sync to not error out when no contracts are returned for an address, other addresses might have creator tokens

don't error out for creator sync

---

db/gen/coredb/batch.go
db/gen/coredb/query.sql.go
db/queries/core/query.sql

Changes:
- **Changed** query to order by the unnest for first post notif insertion. According to chat GPT this should not be necessary at all and said we should check to make sure there isn't a bug in our postgres version lol but if it ain't broke.

order by row number

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql

Changes:
- **Removed** conflict

merge issue

---

service/notifications/notifications.go

This switches the handler for `ActionAdmiredToken` to use the `tokenIDGroupedNotificationHandler` instead of the more general `groupedNotificationHandler`.

Change handler to token grouped handler

---

db/gen/coredb/batch.go
db/queries/core/query.sql

Changes:
- **Changed** count replies query to match the query for replies

match count to query

---

db/gen/coredb/query.sql.go
db/gen/coredb/recommend.sql.go
db/queries/core/query.sql
db/queries/core/recommend.sql
publicapi/feed.go

This change lets posters see their own posts even if they are banned.

Feed shadowban

---

graphql/resolver/schema.resolvers.go

Fixes https://galleryso.slack.com/archives/C04E7KU1F2M/p1701148900979339

replytoComment - handle nil pointer dereference

---

service/media/media.go
service/rpc/ipfs/ipfs.go
service/rpc/rpc.go

Changes
* When predicting the media type, we now use all available HTTP gateways instead of only Infura
* When fetching data, we now use the public IPFS gateway along with the other nodes
* Fixes bug where a response's body is left open if a non-200 status is returned

Cleanup IPFS pipeline

---

db/gen/coredb/batch.go
db/gen/coredb/models_gen.go
db/gen/coredb/query.sql.go
db/gen/coredb/recommend.sql.go
db/migrations/core/000129_add_is_first_post.up.sql
db/migrations/core/000130_add_is_first_post.up.sql
db/queries/core/query.sql
graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.helpers.go
graphql/schema/schema.graphql

* Adds `isFirstPost` field to `Post` type
* Adds `is_first_post` to `posts` table
* `is_first_post` is populated when a post is added to the DB

Add first post flag

---

publicapi/interaction.go

Changes:
- **Changed** comment handler to only send a comment on notification when the reply to is either nil or it does not equal the user who posted to prevent a double notification situation. In the case the reply to is the poster, it just sends a reply notification and not a comment on

only comment notification when not reply to poster

---

activity_stats/astats.go
activity_stats/handler.go

Changes:
- **Added** a retool handler for the activity stats service for recalculating the badges manually

recalculate badges manually

---

cmd/announcement_push_resend/main.go
secrets/prod/local/app-prod-tokenprocessing.yaml
service/notifications/notifications.go
service/task/task.go

Changes:
- **Added** a script for resending push notifications to users in during the announcement period who have not seen their announcement notification

Announcement Push Resend

---

service/multichain/opensea/opensea.go
tokenprocessing/media.go

* Fixes issue in the OpenSea provider where a panic was caused because of a nil interface conversion
* Fixes issue thumbnail URLs pointed to non-imagelike assets

Fix OpenSea interface conversion and media thumbnails

---

service/multichain/alchemy/alchemy.go

Changes:
- **Changed** alchemy metadata processing to use the metadata they provide raw. They used to have a metadata format but since have started just passing along the raw metadata. Because we had expectations like "images are in the `image` json field of alchemy metadata" we would miss tokens with `image_url`'s now that they just pass along the raw metadata.

alchemy  metadata got better, we don't need manual checks

---

rasterizer/index.js

Changes:
- **Added** a fixed size to the svg rasterizer so that we don't get ridiculously small screenshots for svgs that have a small viewbox or large ones for really large viewboxes.

fixed rasterize size

---

publicapi/feed.go

New posts tend to get penalized more because they often come from new contracts

Skip personalize fresh posts

---

service/rpc/rpc.go

Changes:
- **Added** a check to determine whether to unescape raw SVGs in token processing ([example that unescaping ruins](https://openseauserdata.com/files/65e86dc99c6dee817e3de4455db2278d.svg))

check if needs unescaping

---

db/gen/coredb/batch.go
db/queries/core/community.sql

Paginating token-based subcommunities (e.g. Artblocks communities) has been slower than expected. This ended up being an issue with how the query was structured: it used a union of two sets of tokens (contract-based communities and token-based communities), that union caused indexing to break (since an index on a table doesn't apply when the results from that table are unioned with results from a different table).
This PR moves the union to the outer part of the query so indexing will work again.

Rework PaginateTokensByCommunityID so it can use existing indexes

---

service/multichain/reservoir/reservoir.go

* Uses Opensea to fetch parent contract data

Handle parent contracts in reservoir

---

Makefile
emails/digest.go
emails/handler.go

**Changes**
* Changes digest email to send every Monday at 11am EST
* Misc - Makefile formatting
* Parallelizes fetching to speed up collecting template values

Update digest schedule

---

emails/digest.go
emails/send.go

Fix email index error

---

server/inject.go
server/wire_gen.go
service/multichain/opensea/opensea.go

**Changes**
* OS provider now processes contract and token sequentially vs in parallel, otherwise `multichain` panics if a we failed to fetch a contract from OS but succeeded in getting the token
* Fixes bad wire config

Opensea provider fix

---

server/inject.go
server/wire_gen.go
service/multichain/config.go
service/multichain/multichain.go
service/multichain/opensea/opensea.go
service/multichain/reservoir/reservoir.go

**Changes**
* Turns out that although my fixed work, it is MUCH slower because it requires calling reservoir for every token, I'm reverting all my changes to use reservoir again until I can implement the improvement

Revert OS changes

---

db/gen/coredb/batch.go
db/gen/coredb/query.sql.go
db/queries/core/query.sql
graphql/dataloader/api_gen.go
graphql/dataloader/dataloaders_gen.go
graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.go
graphql/schema/schema.graphql
publicapi/token.go

Adds field `tokensBookmarked` to `GalleryUser` type which returns tokens bookmarked by the user.
```graphql
type GalleryUser {
tokensBookmarked(before: String, after: String, first: Int, last: Int): TokensConnection
}
```

Add paginate token admires

---

db/gen/coredb/batch.go
db/queries/core/query.sql
graphql/dataloader/api_gen.go
graphql/dataloader/dataloaders_gen.go
publicapi/token.go

Fixes bug where the token was embedded into the cursor instead of the admire for pagination.

Use correct bookmark cursor

---

service/multichain/opensea/opensea.go

**Changes**
* We can save reservoir credits and also speed up a few methods by skipping the fallback fetch

Skip fallback fetch from tokenprocessing

---

rasterizer/index.js

Changes:
- **Updated** dimensions on rasterizer script from 500-800 and will run script to reprocess punks with the new dimensions

increase rasterizer dimensions

---

db/gen/coredb/batch.go
db/queries/core/query.sql
go.mod
graphql/generated/generated.go
graphql/model/models_gen.go
graphql/resolver/schema.resolvers.go
graphql/schema/schema.graphql
publicapi/gallery.go
publicapi/pagination.go

- The `Community.galleries` query returns the logged-in user's galleries first, if any
- Added the 'Community.viewerIsMember` query, which returns true if the logged-in user is a member of the community, false if not, and null if no user is logged in.

Community v2 updates

---

emails/digest.go
emails/email.genqlient.go
emails/emails.go
emails/genqlient/digest.graphql
go.mod
go.sum
graphql/resolver/schema.resolvers.go
graphql/resolver/schema.resolvers.helpers.go

**Changes**
* Fixes how PFPs are resolved for the email digest
* Updates profile image resolver to only log an error if the user doesn't own the token set as the PFP record in ENS

Fix PFP values in digest

---

rasterizer/index.js
tokenprocessing/media.go

**Changes**
* Updates the rasterizer to add a bg color to punk thumbnails

Add bg color to punks

---

tokenprocessing/pipeline.go

Previously, the pipeline checked if new metadata was valid by checking its length. However, it's possible for the new metadata to have a length > 0, but have no media URLs. In that case, we want to use the starting metadata instead.

Check that metadata has media urls

---

opensea-streamer/main.go

We're seeing cases where we have open websockets, but it doesn't look like we're receiving any events. If this happens, we want to reconnect!

Reconnect if we're not receiving events

---

opensea-streamer/main.go

This PR adds a context deadline to websocket connection attempts to ensure that they never hang indefinitely when trying to open a new connection. It also fixes a bug with subscription timeouts, where a timed-out subscription should reconnect (bug didn't).

Additional timeout handling + subscription fix

---

graphql/resolver/schema.resolvers.go
graphql/resolver/schema.resolvers.helpers.go
publicapi/token.go
service/media/media.go

Fixes a bug where we would return an empty URL for ENS PFPs with certain metadata.

Fix ENS PFP

---

service/notifications/notifications.go

Changes:
- **Added** a check and retry for empty names of tokens received when creating user facing notification data for it. If all else fails, it will use a generic "token" or "tokens"

use generic name when token name not found

---

opensea-streamer/main.go
secrets/dev/backend-env.yaml
secrets/dev/backend-sandbox-env.yaml
secrets/dev/local/app-dev-backend.yaml
secrets/dev/local/app-dev-opensea-streamer.yaml
secrets/dev/local/app-dev-tokenprocessing.yaml
secrets/dev/opensea-streamer-env.yaml
secrets/dev/tokenprocessing-env.yaml
secrets/prod/backend-env.yaml
secrets/prod/indexer-env.yaml
secrets/prod/indexer-server-env.yaml
secrets/prod/local/app-prod-indexer-server.yaml
secrets/prod/local/app-prod-tokenprocessing.yaml
secrets/prod/opensea-streamer-env.yaml
secrets/prod/tokenprocessing-env.yaml
service/multichain/multichain.go

This PR updates our OpenSea API keys on dev and prod (again), and disables optimistic syncing for the time being.

OpenSea API key updates

---

service/multichain/multichain.go
service/multichain/opensea/opensea.go
util/response.go

Changes
* Fixes missing owner address field for contract

Multichain Fix - missing contract owner

---

service/eth/eth.go

Fixes https://galleryso.slack.com/archives/C04E7KU1F2M/p1708613085115449

Fix ENS TokenID conversion

---

service/multichain/multichain.go

This PR fixes a bug where syncing creator tokens for one contract could inadvertently delete creator tokens from other contracts. Additionally, we don't really want to delete creator tokens anymore, so this PR also updates creator token sync to use the `add` method instead of `replace`.

Fix creator token sync deletions

---

emails/digest.go

Fix bug where duplicate entities show up in the digest email.

Ensure no dupe email entities

---

service/multichain/custom_metadata.go
service/multichain/opensea/opensea.go

**Changes**
* Fixes Opensea contract name for shared contracts
* Uses ENS endpoint instead of the graph for resolving ENS metadata from tokenIDs

Correct Opensea contract name

---

publicapi/socials.go

Fixes bug when querying for a user socials where the method would return early if socials info doesn't exist for that user yet which is the majority of the time for a user that just joined.

Farcaster error handling fixup

---

platform/platform.go
service/multichain/objkt/objkt.go
service/multichain/tzkt/tzkt.go

**Changes**
* Change priority of keywords of hic et nunc token processing
* Update objkt fallback to not require matching owner when fetching metadata

Fix tezos providers

---

service/multichain/alchemy/alchemy.go

Alchemy token descriptions, at least on v2, can also be an array of strings. This PR handles this case.

Allow alchemy description as a slice

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
publicapi/user.go
service/persist/postgres/user.go
service/persist/user.go

**Changes**
* Send notifications to users that were followed during onboarding
* Removes extra method from user repo interface

Send notifications for follow all mutation

---

event/event.go
publicapi/socials.go
service/farcaster/neynar.go

**Changes**
* Fixes bug where Neynar is never called for new users in order to get the user's FID
* Adds more logging and error reporting to the "user joined from farcaster" notification

Fix farcaster user joined notification

---

secrets/dev/local/app-dev-tokenprocessing.yaml
secrets/dev/tokenprocessing-env.yaml
secrets/prod/tokenprocessing-env.yaml

Also update tokenprocessing env with new keys

Update tokenprocessing highlight env

---

publicapi/mint.go

Only check the minter's IP if all the other checks succeed.

Move IP check just prior to mint

---

service/multichain/multichain.go
tokenprocessing/process.go

**Changes**
Before, only new tokens were sent to tokenprocessing. This PR changes the behavior to include existing tokens that lack media. This PR also changes the context passed throughout optimistic syncing to the context with added logging fields.

Also submit existing tokens that don't have media when syncing

---

service/limiters/rate.go

There are race conditions when the registry's `DeleteExpired` method is called concurrently with `GetOrCreate`. This PR removes the registry of limiters from the key rate limiter and instead creates a new limiter object for each call. Unfortunately, this is slower because memory has to be allocated each time `ForKey` is called and triggers more GC collection. I'll keep an eye on memory usage after deployment.

Remove limiter backing registry

---

db/gen/coredb/batch.go
db/gen/coredb/models_gen.go
db/gen/coredb/query.sql.go
db/migrations/core/000158_add_pinned_notifications_column.up.sql
db/queries/core/query.sql
publicapi/notifications.go

This reverts commit 74a1a88a263789ad746f97dab3a78cdd933e3350.

Revert "Add pinned column (#1481)"

---

service/multichain/simplehash/simplehash.go

This PR updates fetching tokens by contract to paginate via tokens rather than owners if the contract is an ERC1155 or if there are less than 1000 distinct tokens in the collection. It also fixes a race condition incrementing the total token counter.

Add fast sync path for ERC-1155s

---

service/multichain/alchemy/alchemy.go
service/multichain/custom_metadata.go
service/multichain/multichain.go
service/multichain/reservoir/reservoir.go
service/multichain/simplehash/simplehash.go
service/persist/contract.go
service/persist/token.go
service/persist/token_gallery.go
service/persist/wallet.go
service/tokenmanage/tokenmanage.go
tokenprocessing/metadata.go
tokenprocessing/tokenprocessing.go

Updates logging and error messages to use the string representation of chain names.

Add human readable chain names

---

platform/platform.go
service/multichain/simplehash/simplehash.go
tokenprocessing/handler.go

**Changes**
* Remove `SpamScore` in the token response since Simplehash no longer includes it
* Update `IsFxhash` to handle Base contracts

Remove SpamScore field from simplehash schema and update IsFxhash helper

---

db/gen/coredb/query.sql.go
db/queries/core/query.sql
publicapi/user.go

This PR removes a few quick hack/fix items we added during the Radiance launch. They're no longer necessary!

Remove Radiance launch fixes

---

publicapi/community.go
publicapi/contract.go
publicapi/feed.go
publicapi/interaction.go
publicapi/notifications.go
publicapi/pagination.go
publicapi/token.go
publicapi/user.go

Exports `TimeIDPaginator` and `TimeIDPagingParams` for use in the go-moshi project.

Export TimeIDPaginator

---

publicapi/community.go
publicapi/contract.go
publicapi/feed.go
publicapi/interaction.go
publicapi/notifications.go
publicapi/pagination.go
publicapi/token.go
publicapi/user.go

Also export `paginate` method of `TimeIDPaginator`.

Export paginate method
