gallery-so/go-gallery

- glry_db/glry_collection.go
Changes:
- Small changes to collection struct as mentioned in https://github.com/gallery-so/go-gallery/issues/38
- bson tags can have an optional `,omitempty` such as `bson:"contract_name,omitempty"` that will make sure that empty falsy fields are not put into mongo when a struct field is it's 0 value. Which fields do we want to have omitempty? My vote is that most fields should have omitempty and only the required ones don't
> field adjustments to collection struct

- glry_db/glry_collection.go
- glry_db/glry_nft.go
Changes:
- Added fields and removed fields as mentioned in https://github.com/gallery-so/go-gallery/issues/38
- Externalized the contract struct so that each nft has a contract struct that has more details about the contract rather than putting all of those details in the nft struct and cluttering it up
- bson tags can have an optional `,omitempty` such as ``bson:"contract_name,omitempty"`` that will make sure that empty falsy fields are not put into mongo when a struct field is it's 0 value. Which fields do we want to have omitempty? My vote is that most fields should have omitempty and only the required ones don't
> add new fields and externalize contract fields

- glry_db/glry_auth.go
Changes:
- Small changes to collection struct as mentioned in https://github.com/gallery-so/go-gallery/issues/38
- bson tags can have an optional `,omitempty` such as `bson:"contract_name,omitempty"` that will make sure that empty falsy fields are not put into mongo when a struct field is it's 0 value. Which fields do we want to have omitempty? My vote is that most fields should have omitempty and only the required ones don't
> minor adjustments to user struct fields

- glry_db/glry_gallery.go
Changes:
- **Added** new gallery struct with some helper functions for getting (literally just the same functions as for collections but with some minor changes)
- bson tags can have an optional ,omitempty such as bson:"contract_name,omitempty" that will make sure that empty falsy fields are not put into mongo when a struct field is it's 0 value. Which fields do we want to have omitempty? My vote is that most fields should have omitempty and only the required ones don't
> add glry_gallery.go with structs 

- glry_core/glry_runtime.go
- glry_lib/glry_auth_http_handlers.go
- glry_lib/glry_auth_user.go
- glry_lib/glry_collections.go
- glry_lib/glry_http_handlers.go
- glry_lib/glry_http_middlewares.go
- go.mod
- go.sum
- server/glry_server.go
We have been talking about looking at different ways of handling http that give us more control over things like middlewares and return values. In the most recent commit I have experimented with gin, a very popular go web framework that is very clear and is especially easy to use with regards to middlewares and keeping our routes organized and clear in code. I wrote out some examples using our current code but using the gin web framework. You can check out gin at https://github.com/gin-gonic/gin.
It would take some adjustments to switch over to gin, nothing major, but I believe it will save us headaches and roadblocks in the future. If we believe it will be too much to change now or anyone has any other suggestions I would love to hear! The standard library also has a lot of the …
> http-framework

- glry_db/glry_nft.go
- glry_extern_services/glry_opensea.go
Changes:
- **Added** `openSeaApiResponse` struct to make json unmarshalling easy into our newly updated nft struct
- **Changed** fetch data from open sea func to return `GLRYnft`'s after unmarshalling them from the request response
- **Changed** persist func to no longer turn the old open sea struct into nft structs manually, because the fetch data func already returns nfts, yay!
- Currently the persisting func does not consider the fact that the user might already have persisted nfts from open sea and will create bulk without checking if the nfts already exist. We will have to handle this in the near future
> cleanup external services to reflect changes to structs

- persist/user.go
- server/auth.go
- server/user.go
Changes:
- **Added** parts of get func to handle getting by address or username
- **Changed** get user input to reflect possible query values
- **Added** db func for getting by username
- Currently there is no validation to ensure that the query only contained one of: username, wallet, user_id -- and instead will only handle once based on their priority. This priority is user_id, username, address (in order of least to most complex/time consuming query). That means the query could be something like /glry/v1/users/get?username=:username&addr=:walletAddress&user_id=:userId and it would still work. Do we want it to function this way, or do we want to ensure that only one query param is given?
> add get by username and get by wallet addr

- server/collection.go
- server/nft.go
Changes:
- **Changed** endpoints that have more ambiguous requirements such as get nfts or collections by user_id and return an empty array instead of an error
> return empty arrays when requests are ambiguous

- persist/auth.go
- persist/nft.go
- persist/user.go
- server/nft.go
- server/response.go
- server/t__main_test.go
- server/t__routes_health_test.go
- server/t__routes_nft_test.go
- server/t__routes_test.go
- server/test_utils.go
**Added**
- `ErrorResponse` struct for standardizing error responses
- `server/t__main_test.go` file for triggering setup/teardown once for all package tests
- integration test utils for detecting server error responses
- integration tests for getNftById
**Changed**
- remove `omitempty` from `DeletedBool` to ensure the field gets set as `false` when saving to DB
- minor bugfixes, cleanup
> Integration tests for Get NFT by ID route

- persist/collection.go
- persist/t__unassigned_test.go
- server/auth.go
- server/collection.go
- server/handler.go
- server/middleware.go
- server/nft.go
- server/user.go
Changes:
- **Added** separate endpoints for different update types
- **Changed** gin.H errors to ErrorResponse
- Currently doing /update/name and /update/hidden etc.. Is there a better way we want to do endpoint naming for these? We could also have one handler and do /update/:type and do a switch statement on the type to determine what they are trying to update. Possibly even a required query param. What do you think?
> separate handlers for hidden/name/nfts

- persist/nft.go
- persist/t__nft_test.go
- server/nft.go
Changes:
- **Changed** NftUpdate func to take in user id given that a user id must always be present for authenticated endpoints and use the user id in filter to make querying faster
> user id for nft update

- persist/auth.go
- persist/mongo.go
- server/auth.go
We get a duplicate key error when inserting a record into the db (and 1 record already exists in the db), because the `_id` field is getting set as an empty string. I encountered this when trying to generate a nonce more than once.
It looks like it's just an issue setting the ID field using an incorrect field name. We're using `IDstr` instead of `ID` which is what is set in the schema.
This PR changes `IDstr` to `ID` in our mongo Insert function so that the id gets persisted.
Empty ID before fix:
ID after fix:
@bennycio @fbrcsftnr  Do we prefer `ID` or `IDstr` ?  we can use `IDstr` if we want to be consistent with our other fields. But I don't feel strongly since this field has the type `DbId`, which is also a `string` so both are correct
> Rename ID field on auth schema to IDstr

- server/middleware.go
- server/server.go
- server/validate.go
The validator functions weren't being registered as expected on init, causing a panic when attempting to save to the user table.
The following code block didn't run because `v` and `ok` were `nil` and `false`, respectively.
```
if v, ok := binding.Validator.Engine().(*validator.Validate); ok {
v.RegisterValidation("short_string", shortStringValidator)
}
```
Specifying the validator version we use as `v10` solved the issue.
Separately, fixed `ethValidator` by swapping `HasSuffix` for `HasPrefix` to look for "0x" in the expected place.
> Fix Validation registration and ethValidator

- server/t__validate_test.go
This PR adds a test file for the validator functions defined in `validate.go`
This PR covers the `ethValidator` and `signatureValidator` functions. The rest are similar/simple length validations so we can add coverage for those later if necessary.
> Add tests for validator functions

- server/auth.go
- server/t__auth_user_test.go
- server/user.go
Changes:
- **Changed** `getUserWithNonce` to return what it has regardless of errors
- **Changed** auth preflight to not spend time making the extra round trip to the DB to grab nonce immediately after creating it in the case that a user did not exist
- **Changed** test to use global runtime and ensure nonce is not empty
> fix create user

- persist/nft.go
- server/nft.go
- server/opensea.go
- server/t__opensea_test.go
Changes:
- **Added** tests for opensea sync
- **Changed** funcs for upserting, checking difference, etc. to ensure all opensea nfts are reflected accurately on gallery
- Should we mark nfts that are not on opensea for a user but on gallery as 1. deleted, 2. remove their `owner_user_id` and `owner_address`, or 3. remove their `owner_user_id` and set their `owner_address` to what it is on opensea. Currently I have implemented 2 because deleting feels odd given that the nft's themselves can't really be deleted and later on someone else could come along with that same nft.
> sync test and fixes

- server/t__validate_test.go
- server/validate.go
The previous regex pattern was not returning true for valid usernames as expected.
I updated the pattern and added test cases for various valid and invalid usernames.
> Fix username validation regex and add tests

- server/gallery.go
Changes:
- **Changed** gallery create to take in a list of collections instead of user id
- UserID is already given by context which is why it was not necessary in post, it is also possible that collections are not necessary for create either but in this case it would be an empty post. It could also save a round trip just creating the gallery at the first time they set up their collections.
> create with collections

- persist/collection.go
- persist/gallery.go
- persist/nft.go
- persist/storage.go
- server/auth.go
- server/handler.go
- server/jwt.go
- server/t__routes_auth_test.go
- server/t__routes_collection_test.go
- server/t__test_utils_test.go
Changes:
- **Changed** push function to take in an array rather than an array of arrays so that it pushes collections into galleries correctly
- **Added** tests for preflight and collection creation
- **Added** owner username field to nft with just json tag and fills field upon retrieval
- **Changed** test user creation to create a nonce
Consirations:
- Made some minor adjustments to preflight func and test passes but not sure why @Robinnnnn 's issue with preflight showing no user existing is happening yet
> collections in gallery push, nft with username, possible preflight fix

- persist/collection.go
- persist/gallery.go
- persist/storage.go
- persist/user.go
- server/collection.go
Changes
- **Added** a pull operation to remove an array of items from an array field of queried documents
- **Added** an update nfts func that will first pull nfts from all other documents before adding it to the new one.
- **Changed** create coll func to also remove nfts from other colls that have the nfts it is being created with
- Needs tests still...
> pull operation to ensure no duplicate nfts

- persist/collection.go
- persist/gallery.go
- server/t__routes_collection_test.go
- server/t__routes_gallery_test.go
- server/t__test_utils_test.go
When retrieving a user's gallery via `galleries/user_get`, the collections were not populated in the correct order of the collection IDs from the gallery document.
It appears that the issue is that $lookup doesn't guarantee the order of the resulting documents, and uses any order it encounters the matched documents in the db in.
The recommended solution was to add a `indexOfArray` field which is the index of the collection in the gallery.collections array, and use that to sort the populated collection results. After sorting, the `indexOfArray` field is removed.
I also modified the `TestUpdateGalleryById_ReorderCollections_Success` test to validate this case. It looks like the test gave a false positive before because one of the collections was `hidden`, and `galleries/user_get` was called …
> Ensure a gallery's collections are returned in the correct order

- persist/collection.go
- persist/nft.go
- persist/storage.go
- server/nft.go
- server/opensea.go
- server/t__opensea_test.go
Changes:
- **Added** a func that will remove a set of NFTs from all other user's collections and remove any of your NFTs that are not a part of that set. In other words, ensure that only you and ONLY you can display only the NFTs passed into that function
- **Changed** opensea sync to use this func
> remove sync nfts from other collections

- persist/nft.go
- server/nft.go
- server/opensea.go
- server/t__opensea_test.go
- server/t__routes_collection_test.go
- server/t__routes_nft_test.go
Changes:
- **Added** steps to aggregation pipeline for NFTs to go get username from user collection
- **Added** `NftDB` struct and `Nft` struct that represent Nfts with or without aggregation additions
- **Added** check in nft get by ID test to make sure username is filled
> aggregate owner username for nft get

- scripts/migration.py
- server/opensea.go
Changes:
- Change the field that we get the NFT's external link from during the OpenSea -> Gallery NFT mapping
> Map OS asset's external_link to our NFT model

- server/auth.go
Ledger-produced signatures have v = 0 or 1, meaning they fail the existing signature validation which expects v to be 27 or 28.
Manually making an exception to allow v to be 0 or 1 seems to be an accepted solution for now.
The issue is documented in [this Github Issue](https://github.com/MetaMask/metamask-extension/issues/10240)
More info: https://ethereum.stackexchange.com/questions/103307/cannot-verifiy-a-signature-produced-by-ledger-in-solidity-using-ecrecover
> Support ledger-produced signature

- persist/collection.go
- persist/nft.go
- runtime/config.go
- server/nft.go
- server/opensea.go
- server/t__opensea_test.go
Changes:
- **Changed** opensea sync input to take a list of comma separated addresses
- **Changed** funcs that are involved in opensea sync to take multiple addresses such as getting all opensea assets for each address and pulling every nft from your account with the specified addresses that was not a part of the synced nfts
- **Removed** `NftRemoveDifference` because it does the same thing as in `CollClaimNFTs` but with more work
> multiple addresses for opensea request

- persist/collection.go
- persist/gallery.go
- server/collection.go
Changes:
- **Added** a check to ensure that the NFTs that a user is adding to their collection are their own
- **Added** a function to remove repeat NFTs from the list of NFTs being updated
> ensure user owns nfts for coll update

- persist/collection.go
- persist/nft.go
- persist/storage.go
- server/opensea.go
- server/t__opensea_test.go
- server/t__routes_collection_test.go
- server/t__routes_nft_test.go
- server/t__routes_user_test.go
- server/t__test_utils_test.go
Changes:
- **Changed** NFT struct to have `owner_addresses` instead of `owner_address`, have no `owner_user_id` field (because there isn't just one owner anymore), and have a `multiple_owners` field that will determine if updating a token should add users to the list of owners or replace the list of owners with the new owner
- **Changed** funcs that used to use `owner_user_id` field in queries to instead query for addresses and if the addresses are not available, first get the user and find their addresses
- **Changed** tests to reflect changes
- **Removed** pull from other user's collections when an NFT is being claimed
- Frontend will need to reflect the changes made to nft structs. Specifically, the frontend will have to handle `owner_addresses` and `multiple_owners` …
> support nfts having multiple owners

- persist/mongodb/nft.go
- persist/nft.go
- server/handler.go
- server/nft.go
- server/opensea.go
- server/t__opensea_test.go
Changes:
- **Added** separate endpoint for refreshing opensea cache
- **Changed** opensea endpoints to be `/nfts/opensea/get` and `/nfts/opensea/refresh`
> refresh opensea endpoint

- persist/collection_nft.go
- persist/collection_token.go
- server/collection_nft.go
- server/collection_token.go
Changes:
- **Added** a token layout object that for the time being just holds a column field representing the number of columns in a collection
- **Added** a function to validate layouts ensuring the column constraints are met as well as defaults are set
- **Changed** update and create collection functions to optionally take in a layout object that will have its defaults set if not included in the request
> columns with token layout in updates and creation of collections

- persist/mongodb/token.go
- scripts/get_all_users.py
- scripts/post-index-diff.py
Changes:
- **Added** script that will print diffs for the post indexer endpoints compared to current endpoints
- **Changed** get token persist funcs to only set limit if the limit is defined. (Learned that Mongo won't return anything if limit is not set for huge collections like we have)
- **Added** get users script for the csv that details users and their nfts/collection counts
> indexer diff script

- docker-compose.yml
- indexer/indexer.go
- persist/mongodb/contracts.go
- persist/mongodb/mongodb.go
- persist/mongodb/token.go
- persist/tokens.go
Changes:
- **Removed** all read operations from the indexing process to the mongo db token collection
- **Changed** bulk upsert funcs for tokens and mongodb wrapper to allow for multiple set documents with aggregations to use aggregation on the write operation to allow us to read on the fly when we are upserting
TODO:
> indexer only writes to token collection

- indexer/handler.go
- memstore/t__tasks_test.go
- memstore/tasks.go
- persist/collection_token.go
- persist/mongodb/access.go
- persist/mongodb/accounts.go
- persist/mongodb/collection_nft.go
- persist/mongodb/collection_token.go
- persist/mongodb/contracts.go
- persist/mongodb/features.go
- persist/mongodb/gallery_nft.go
- persist/mongodb/gallery_token.go
- persist/mongodb/membership.go
- persist/mongodb/mongodb.go
- persist/mongodb/nft.go
- persist/mongodb/token.go
- persist/mongodb/user.go
- persist/persist.go
- server/server.go
- server/t__routes_collection_test.go
- server/t__routes_gallery_test.go
- util/time.go
Changes:
- **Added** caching for galleries. Now galleries are always returned first from the cache and optimistically updated every time an update is made to the gallery or a collection
- The key for cached galleries in the cache is the user ID. Not all functions that update information that would potentially update the result of a `getGalleriesByUserID` call take in a user ID. Those functions have no way of telling the cache that there is something that needs to be updated. Currently I have set an hour long TTL on the cache. Do you have any ideas of how we can ensure the cache stays up to date? We could use what a function does give us to find an owner user ID (such as using the `owner_address` of an NFT) but for functions like `BulkUpsert` there might be a lot of users …
> cache galleries

- server/t__routes_auth_test.go
fixed TestUserLoginGnosis_Success
it looks like  `TestUserLoginGnosis_WrongNonce_Failure` and `TestUserLoginGnosis_WrongSig_Failure` expect 200s, but I think it should throw 400 for these cases?
> fix TestUserLoginGnosis_Success

- server/opensea.go
- server/server.go
- server/t__opensea_test.go
- service/memstore/tasks.go
- service/persist/mongodb/collection_nft.go
- service/persist/mongodb/gallery_nft.go
- service/persist/mongodb/gallery_token.go
- service/persist/mongodb/nft.go
- service/persist/nft.go
Changes:
- **Added** caching for getting nfts by user ID
- **Change** memory store task queue to ensure synchronous updates by key. This means that although many updates can be running asynchronously for different keys, no more than one update can be run at a time per key. This is to ensure that when updates come in for a given key, the most recent update will be the one that will be reflected in the cache.
> add caching for user nfts

- server/handler.go
- server/membership.go
- server/nft.go
- server/server.go
- server/t__opensea_test.go
- service/membership/membership.go
- service/opensea/opensea.go
- service/persist/membership.go
Changes:
- **Changed** update membership tiers background process to store more data for the potential user who owns a membership card such as:
1. Owner Address (will always be available)
2. Username
3. User ID
4. some preview URLs for NFTs they own
> return more user data if possible for membership tiers

- server/membership.go
- service/membership/membership.go
- service/persist/postgres/membership.go
Changes:
- **Added** a step to updating membership tiers that checks if there are owners currently stored for a tier and check if they are users in the database before going to opensea to update again.
- **Changed** upsert tier to also upsert `last_updated` so that we can not spam opensea with requests for tiers not being updated
- **Added** a force refresh query param that will forcibly go and update the tiers
> update current tiers with owners, update in order to reduce rate-limiting, insert last_updated

- server/handler.go
- server/t__routes_user_token_test.go
- server/user_token.go
- service/auth/auth.go
On the front end we are removing all JWT related code. This means that we are no longer storing the jwt in local storage which we used to quickly determine the user's 'authenticated' state upon page load.
This PR adds an endpoint that returns the currently authenticated user if a valid cookie is included in the request, which will allow the front end to continue to determine the user's logged in state.
- Added a new endpoint `users/get/current` to retrieve the currently authenticated user
- If a user is found for the auth cookie, return the user
- If there is no auth cookie or the provided auth cookie is invalid, return a 204 No Content
- If the auth cookie is valid but no corresponding user is found, return a 500
- Added related tests for the endpoint
- success: valid cookie return user …
> add endpoint to get current user and change logout to POST

- .circleci/config.yml
Adds a check after deployment that pings the server's health endpoint.
Testing:
* Tested by changing the trigger from main to my branch and verifying the job runs successfully in CircleCI: [build](https://app.circleci.com/pipelines/github/gallery-so/go-gallery/985/workflows/e17f37dc-c2fa-4106-8023-e42043570b3d/jobs/1501)
> Add post-deploy healthcheck

- .circleci/config.yml
- server/t__server_integration_test.go
Small tweak to read test-wallet.json from `_internal`, since that's where it ends up by default on a developer's machine
> Read test-wallet.json from _internal directory

- service/persist/postgres/gallery_nft.go
- service/persist/postgres/gallery_token.go
Description: 
This PR tries to fix a bug I saw when testing whitespace blocks.
After saving some collections with whitespaces in a collection, I tried to retrieve my Gallery and found that in the response, collections were getting their whitespace values combined with whitespace values from other collections.
it's easier to see with examples, so here are 2 cases:
2 collections (one with [0,0,0,1] and one with no whitespace)
db: 
response:
2 collections (one with [3,3,3,3,6,7,8] and one with [2,2,2,2,3])
db:
response:
The db query was fine and returning results as expected. It looks like the issue was with how we hold on to the `collection` value outside of the `rows.Scan` loop. We overwrite fields on `collection` with each iteration, but it looks like if there are any fields that aren't …
> instantiate collection in each iteration to reset previous values

- features/access.go
- features/updater.go
- indexer/core.go
- indexer/indexer.go
- indexer/server.go
- server/collection_token.go
- server/t__routes_collection_token_test.go
- server/t__routes_user_token_test.go
- service/persist/collection_token.go
- service/persist/feature.go
- service/persist/postgres/collection_token.go
- service/persist/postgres/user.go
Changes:
- **Added** side effect handling for ensuring that NFTs transferred away from a user leave their collections
- **Added** new indexer pipeline funcs for subscribed logs where we want to grab more data such as media content
- **Changed** the indexer file to be a bit more organized and separated out some common logic
- Right now media content (the media field on a token) is only retrieved in the "listening" stage of the indexer after the initial indexing process. This is because the initial indexing process is very expensive and would be very time consuming if it had to figure out for every NFT if there was a user associated with it and then subsequently grab media content for that NFT which could take anywhere from a few milliseconds to a few minutes (if the context …
> side effects, organization, handle subscribed logs differently

- admin/gallery.go
- admin/handler.go
- service/persist/postgres/gallery_nft.go
- service/persist/postgres/gallery_token.go
Changes:
- **Changed** get galleries by user ID to fallback to default data fetching when the cache data is invalid and will log invalid data so we can see what put it there
- **Added** endpoint to admin backend for busting cache
> fallback to normal data fetching when cache fails

- service/persist/persist.go
- service/persist/token.go
Changes:
- **Removed** clean string for `NullString` and `TokenMetadata` types so that non print characters can show up (such as new lines)
> do not clean strings

- service/persist/postgres/t__nft_test.go
Changes:
- **Changed** nft test to use a wacky collectors note to ensure that the sanitization rules do not break notes
> use wacky collectors note

- server/t__integration_utils_test.go
- server/t__routes_collection_token_test.go
- service/persist/postgres/backup.go
- service/persist/postgres/t__backup_test.go
- service/persist/postgres/t__utils_test.go
- util/random.go
Updated behavior:
- **Store up to 50 backups per gallery.** Will keep an eye on the size of this DB ballooning. Cool thing is if this is too frequent, we can simply update the pruning rules to slowly clear out the DB.
- **Reduce backup frequency from 12 hours to 5 mins**, if change was made in past 24h
New behavior:
- Backups in the past 7 days should be stored no more often than every 1 hour
- Backups beyond the past 7 days should be stored no more often than every 1 day
(See additional notes in files)
Initial state:
The latest backup inserted was at `03-29 06:11`. I made changes to my gallery at `06:12`, `06:13`, etc. and did not see any inserts to the DB. This was expected because the changes were within 5 minutes of the previous update ✅
I then made an update to a collection at …
> Update gallery backup logic

- graphql/dataloader/dataloaders.go
- graphql/generated/generated.go
- graphql/model/gqlidgen_gen.go
- graphql/model/models.go
- graphql/model/models_gen.go
- graphql/model/remapgen_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/collection.go
- publicapi/gallery.go
- publicapi/nft.go
- publicapi/user.go
Apologies for the annoying refactor, but we were talking about users having multiple galleries recently, and I figured this would be a good time to standardize in case we need a `GalleryCollection` in the future to represent a gallery in a collection.
- GalleryNft -> CollectionNft
- GalleryCollection -> Collection
- GalleryCollectionLayout -> CollectionLayout
- GalleryCollectionLayoutInput -> CollectionLayoutInput
- `nftById(id: DBID!)`
- `collectionNftById(nftId: DBID!, collectionId: DBID!)`
Added `GltfMedia` as a `MediaSubtype`. We'll use this media type when we see a `.glb` or `.gltf` extension.
Any public API function that writes to the database will now clear all dataloader caches to ensure that we return the latest data to the caller.
> GraphQL Updates

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/model/remapgen_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/collection.go
- publicapi/nft.go
- service/persist/nft_event.go
- updateNftInfo mutation allows modifying an NFT's collector's note
- creatorAddress and openseaCollectionName fields have been added to the GraphQL `Nft` type
- GraphQL resolvers handle remapping the Dead Ringers URL to a smaller resized version
- Fixed an issue in the Public API where collection names and descriptions couldn't be updated to an empty string
> GraphQL: updateNftInfo / extra NFT fields / Dead Ringers

- graphql/resolver/schema.resolvers.helpers.go
switch/case in golang [doesn't fall through](https://stackoverflow.com/a/40822747). this was causing `.glb` files to be returned as `UnknownMedia` types.
confirmed this fix works by testing on frontend
> Fallthrough on media type checking

- .vscode/settings.json
- graphql/generated/generated.go
- graphql/model/gqlidgen_gen.go
- graphql/model/models_gen.go
- graphql/model/remapgen_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/collection.go
- publicapi/user.go
- Added `communityByContractAddress` GraphQL query
- Robin added `updateCollectionHidden` GraphQL mutation
- Fixed a bug: trying to set the user's bio to an empty string via GraphQL would fail validation
> GraphQL: community query + hide collection mutation

- graphql/resolver/schema.resolvers.helpers.go
- service/persist/postgres/community.go
- [GraphQL only] `CommunityOwner.address` no longer returns the same address for every owner
- [GraphQL + REST] Users are omitted from the community results if they (a) can't be found in the database by their address, or (b) have an empty username
> Community endpoint fixes

- graphql/generated/generated.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- publicapi/nft.go
- server/handler.go
- server/nft.go
- service/nft/nft.go
GraphQL / Public API now calls the "get opensea NFTs" flow instead of the "refresh opensea NFTs" flow when refreshing a user's NFTs. This is consistent with how we use the REST API.
> Public API: Use the correct functionality to refresh Opensea NFTs

- graphql/generated/generated.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- publicapi/misc.go
- publicapi/publicapi.go
- Added a `generalAllowlist` root query to return allowlisted addresses via GraphQL
> Add GraphQL root query for general allowlist

- service/nft/nft.go
Refreshing Opensea assets via list of addresses would accidentally add the entire comma-separated list of addresses as a single "address" in the resulting output slice.
> Fix a bug when parsing address lists for Opensea refresh

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/handlers.go
- graphql/resolver/resolver.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- middleware/middleware.go
- publicapi/auth.go
- publicapi/publicapi.go
- publicapi/user.go
- server/handler.go
- service/auth/auth.go
- service/user/user.go
- Added a `logout` mutation
- Auth failures (e.g. ErrInvalidToken) will now clear the user's cookie
- Beginnings of some minor refactoring to move auth functionality into the public API instead of having GraphQL resolvers call the `auth` package directly
> GraphQL auth updates

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/handlers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- service/persist/postgres/user.go
- service/persist/user.go
- service/user/user.go
The GraphQL schema has been updated to include `ErrUserAlreadyExists` as a possible return type for the `UpdateUserInfo` mutation.
> UpdateUserInfo now returns ErrUserAlreadyExists when username is taken

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- publicapi/nft.go
By supplying a collectionId, we can generate appropriate feedbot links for NFT collector's note updates!
> Add an optional collectionId parameter when updating an NFT's info

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/nft.go
Since OpenSea refreshing can fail in myriad ways, we don't want/need to handle every case with an explicit GraphQL error type, but it _is_ nice to return a GraphQL error so the client can handle sync failures with the same fragment-based approach it uses for other errors.
> OpenSea refresh mutation now returns a catch-all error on failure

- service/event/cloudtask/cloudtask.go
- service/event/cloudtask/collection.go
- service/event/cloudtask/nft.go
- service/event/cloudtask/user.go
- service/persist/collection_event.go
- service/persist/nft_event.go
- service/persist/postgres/collection_event.go
- service/persist/postgres/nft_event.go
- service/persist/postgres/user_event.go
- service/persist/user_event.go
Tasks were run immediately because the scheduled time used was the zeroed-out time value. Fixed by using when the event was saved to the database (plus the buffer) as the scheduled time.
Also moved some feedbot-specific things into the wrapper function.
> Bugfix: Fix feedbot tasks being scheduled immediately

- service/persist/postgres/collection_nft.go
This is a fix for an issue one of our users was running into. When doing an Opensea refresh, it's possible for the user to have multiple copies of the same NFT spread throughout their wallets. Historically, we've tried to keep the old IDs (since they're potentially used in collections), but update them with the new owner_addresses. Unfortunately, this strategy can fail when working with multiple copies of an NFT distributed among different wallets, as we might attempt to map the same new address to multiple old versions of the NFT, and that violates a uniqueness constraint in our database.
As a fix, @bennycio and @Robinnnnn and I decided not to delete the old versions of the NFT at all. If the user brings in new copies of the same NFT, we'll keep the old ones and the new ones. This …
> Don't delete an NFT if the same user still owns the same NFT in a different wallet

- graphql/resolver/handlers.go
- middleware/middleware.go
- server/server.go
- service/auth/auth.go
- service/logger/logger.go
- service/memstore/redis/redis.go
- service/persist/postgres/postgres.go
- service/rpc/rpc.go
- service/sentry/sentry.go
- service/tracing/http.go
- service/tracing/redis.go
- service/tracing/tracing.go
- We require a Gallery membership card to sign up or log in, but we _also_ require a membership card for any action that requires membership. In the GraphQL era, we're checking a user's auth status as part of any logged-in request, which means we run the REQUIRE_NFTS check every time a logged-in user does anything on our site.
- REQUIRE_NFTS fires off a call to Alchemy to see whether a user has one of our membership NFTs. This means that every time a logged-in user does anything, they have to wait for a round trip HTTP request from our servers to Alchemy. This often takes some ~400-500ms to complete.
- This PR addresses the issue by caching the result of that Alchemy call in Redis with a 1-hour expiration time. As long as a user has one of our membership cards when we check with Alchemy, …
> [GAL-131] REQUIRE_NFTS speedup / Redis tracing / Tracing tweaks

- indexer/nfts.go
- service/media/media.go
- service/rpc/rpc.go
Changes:
- **Changed** update media to update all tokens with token identifiers if specified in the call rather than manually updating each token. Saves a lot of time for ERC-1155 tokens.
- **Changed** some components that commonly cancelled due to context cancellations
> prehandle refreshes for specific tokens

- service/event/cloudtask/cloudtask.go
- service/event/cloudtask/collection.go
- service/event/cloudtask/nft.go
- service/event/cloudtask/user.go
- service/event/collection.go
- service/event/nft.go
- service/event/user.go
- service/tracing/grpc.go
This PR adds gRPC tracing so that we can [trace requests to Cloud Tasks](https://sentry.io/organizations/usegallery/performance/gallery-backend:6ecaf0abafa94e19bfb9d995a5e98aa6/?environment=local&project=6262886&query=transaction.duration%3A%3C15m+http.method%3APOST&showTransactions=recent&statsPeriod=1h&transaction=POST+%2Fglry%2Fgraphql%2Fquery+%28useUpdateUserMutation%29&unselectedSeries=p100%28%29) and also helps pave the way for tracing requests in the feedbot.
One biggish change is that the event handlers no longer run in a separate goroutine, but I think it's a good tradeoff so that the trace is added to the current transaction. It'd require creating a new context since gin closes the context after the response is sent and being able to add the parent span to the new context. …
> Add gRPC tracing

- feedbot/post.go
**Fixes**
* Some strings include html entities, this PR fixes it so that they are unescaped:
`'"'&craz'y name <> '%'*` instead of ` '&#39;&#34;craz&amp;y name &lt;&gt;&#39;'`
> Unescape html symbols

- db/migrations/000010_multichain.up.sql
- db/queries/query.sql
- db/sqlc/batch.go
- db/sqlc/models_gen.go
- db/sqlc/query.sql.go
- docker/postgres/02_init.sql
- graphql/dataloader/dataloaders.go
Create a GIN index on `tokens.owned_by_wallets` and use array operations to query for tokens by wallet ID (because using non-array operations like `ANY` means we won't benefit from the index). Prior to this change, looking up tokens for a wallet took about 300ms. After indexing, it takes about 10ms.
> Use indexed query when looking up tokens by wallet ID

- db/migrations/000012_drop_collections_v2.down.sql
- db/migrations/000012_drop_collections_v2.up.sql
- publicapi/collection.go
- service/persist/postgres/collection_token.go
- service/persist/postgres/gallery_token.go
- service/persist/user.go
Most `tokens` queries were using the `collections_v2` table, but we're not actually using that for anything, so this commit drops it and uses `collections` in queries instead. Fixes all sorts of issues we were having with collections (since they were being created in one table and queried from another).
> Use collections table instead of collections_v2

- graphql/resolver/schema.resolvers.helpers.go
- service/persist/postgres/token_gallery.go
SQL queries for updating tokens expect `owner_user_id`, but the code paths using these queries were passing an array of wallets. Now they're passing a user ID, and updating collector's notes works again.
> Fix for updating token collector's notes

- cmd/migration/main.go
- db/migrations/000016_update_contract_column.down.sql
- db/migrations/000016_update_contract_column.up.sql
- db/sqlc/batch.go
- db/sqlc/models_gen.go
- db/sqlc/query.sql.go
- docker/postgres/02_init.sql
- graphql/generated/generated.go
- graphql/model/gqlidgen_gen.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/contract.go
- publicapi/publicapi.go
- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
- service/persist/contract_gallery.go
- service/persist/postgres/contract_gallery.go
- service/persist/postgres/token.go
- service/persist/postgres/token_gallery.go
- service/persist/token.go
- service/persist/token_gallery.go
- sqlc.yaml
Changes:
- **Changed** multichain provider functions to return contracts with tokens
- **Changed** refresh tokens to retrieve all tokens from all chains before running any updates
- **Changed** token struct and sql schema to use contract DBID instead of contract address
- **Changed** migration to grab from the contracts table
- **Added** `NormalizeAddress` function to chain that will normalize an address as string depending on what chain it is. Currently only supports ETH.
> contract by id and refresh logic

- db/migrations/000010_create_early_access_table.down.sql
- db/migrations/000010_create_early_access_table.up.sql
- graphql/resolver/handlers.go
- middleware/middleware.go
- publicapi/auth.go
- server/auth.go
- server/handler.go
- server/server.go
- service/auth/auth.go
- service/persist/early_access.go
- service/persist/persist.go
- service/persist/postgres/early_access.go
- Added an `early_access` database table to hold allowlisted EA addresses
- `HasAllowlistNFT()` is now `HasGalleryAccess()` and checks both membership NFTs and the `early_access` database
- We only check membership NFTs and early access addresses when _creating_ an account. We no longer confirm membership for continued access to the site (i.e. the `REQUIRE_NFTS` check was removed)
- At some point in the future, we still need to remove the REQUIRE_NFTS entry from the various environment config files in the encrypted deploy directory, but I'd rather hold off on that and avoid the possibility of merge conflicts with the multichain branch.
> Support early access allowlist

- db/queries/query.sql
In the pre-multichain world, we returned a list of NFTs per wallet without any explicit sorting, but the returned NFTs seemed to be mostly sorted anyway (probably due to the way Postgres stores rows). This is no longer the case in the post-multichain world, so this PR adds explicit sorting when querying for a wallet's tokens or a user's tokens.
> Sort by newest first when returning tokens for a user or wallet

- db/queries/query.sql
- db/sqlc/batch.go
- db/sqlc/query.sql.go
My previous token sorting PR sorted tokens by creation time. Upon testing that against dev, I found that it's not uncommon for several tokens from the same collection to have been created at the same time. Since it'd be cool to show tokens in a stable sort order by default, I've updated the criteria to sort by: `creationTime`, then `name`, then `tokenID`.
Soooo now we'll show the newest stuff first, and if tokens were created at the same time we'll sort them by name (since tokens created at the same time often have names like `My Cool Token #14`, `My Cool Token #15`, etc), and if they have identical names, we'll sort them by ID too.
> Stable sort order for tokens (again)

- db/queries/query.sql
- db/sqlc/batch.go
- db/sqlc/query.sql.go
Prior to this change, disconnecting a wallet from a user's account would still allow tokens from that wallet to be displayed in the user's collections. The tokens would only disappear after an Opensea refresh.
This PR updates the "tokens by collection ID" query to only include tokens in wallets owned by the collection owner. The upshot is that disconnecting a wallet will immediately remove the affected tokens from the user's collections, which is consistent with the way the sidebar works (sidebar tokens disappear immediately after a wallet is disconnected).
> Filter out disconnected wallets' tokens in collections

- service/mediamapper/mediamapper.go
There's no point in trying to build an imgix URL from an empty string. Rather than sending the frontend a broken URL (i.e. an imgix URL with an empty source), we should just send an empty string so the frontend's default "missing image URL" handling still works.
> Don't try to use imgix on empty URL strings

- cmd/migration/main.go
- service/multichain/multichain.go
- service/persist/persist.go
- service/persist/postgres/token.go
- service/persist/postgres/token_gallery.go
Change:
- **Removed** `GenerateID()` from the `(DBID).Value()` function so that it only returns the string version of the DBID rather than automatically generating a new ID when it is empty. Generating the ID when the current DBID is empty leads to some unexpected effects that are hard to track down because there is nothing explicit about the `driver.Valuer` interface that would require the DBID to not be empty.
- **Changed** token persist funcs to explicitly generate IDs instead of relying on auto-generation.
I went through each insert/create func in the persist package to make sure they all explicitly generated IDs and the only ones that I found that didn't were two of the unused token funcs in both `token` and `token_gallery`.
> no autogenerated IDs to prevent empty ID edge cases

- server/handler.go
This will disable GraphQL access during tonight's maintenance so we won't have to worry about anyone accidentally modifying data during migration.
> Disable GraphQL API during maintenance

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/model/remapgen_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- indexer/contracts.go
- indexer/handler.go
- indexer/indexer.go
- indexer/nfts.go
- publicapi/contract.go
- publicapi/token.go
- service/multichain/eth/eth.go
- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
- service/persist/contract.go
- service/persist/postgres/contract.go
- service/persist/token_gallery.go
- service/rpc/rpc.go
- util/response.go
Changes:
- **Added** endpoint to indexer for refreshing contracts manually
- **Added** two functions to the `ChainProvider` interface for refreshing individual tokens and contracts as well as implemented those functions for the opensea and indexer chain providers.
- We need the frontend to call these functions somewhere so they probably need to have their own graph QL endpoints, so we will follow this PR up with another PR for graph QL endpoints.
- Should the refreshing of tokens and contracts be combined into one `ChainProvider` function where the contract for a given token is refreshed when a token is refreshed. We could do this at the graphQL level as well if we wanted to and have one "refresh" endpoint that refreshes the contract for a token and the token. I also …
> refresh individual tokens and contracts

- feed/event.go
- feed/feed.go
- feed/handler.go
- feed/server.go
**Changes**
* Noticed half the response time for handling messages is spent creating a connection pool to the db because it is done per request, changed it so the connection is made once at startup (like we do in the backend)
> Init pgx client once

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
When debugging user issues, I usually log in as that user locally (via debug auth) and see if I can reproduce the issue. Historically, that means looking up their userID and their addresses in the database and then supplying those to a debug authenticator.
This PR adds the `asUsername` parameter as a convenience method to log in as a given user without needing to look up their ID and addresses manually.
> Add asUsername parameter to GraphQL debug auth

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/user.go
- service/persist/postgres/user.go
- service/persist/user.go
- service/user/user.go
- The `CreateUser` mutation now requires a username to be specified. Prior to this, we'd create an account and _then_ allow the user to pick a username, leading to all sorts of scenarios where a user can take actions on our site but doesn't have a username.
- `CreateUser` also takes an optional `bio` field, since we still ask for a bio during the initial sign-up flow. If omitted, the bio will be an empty string as usual.
- Bug fix: `CreateUser` now succeeds when using an address owned by a deleted wallet or a deleted user. Previously, user creation would fail if a previous (but now deleted) wallet or user had used the same address.
> [GAL-281] [GAL-271] Improved CreateUser flow

- validate/validate.go
**Changes**
* Validate that provided settings are only for tokens in the collection since it's easier for the frontend to construct the request
* Frontend guarantees that whenever a token does have a setting it will always be sent in the payload
> Update tokenSettings validation

- service/site/figure31.go
Use `CONTRACT_INTERACTION_URL` since we aren't using subscriptions anymore
> Use CONTRACT_INTERACTION_URL

- graphql/resolver/schema.resolvers.helpers.go
Gnosis auth was mistakenly using the Eoa.Nonce field instead of the GnosisSafe.Nonce field, causing a nil reference error that was reported via Sentry.
> Reference correct nonce field for Gnosis Safe auth

- db/migrations/000022_add_username_idempotent_index.down.sql
- db/migrations/000022_add_username_idempotent_index.up.sql
Now that we've removed all duplicate usernames from the database, we can enforce uniqueness on the `username_idempotent` column to make sure we don't end up with duplicates in the future.
> [GAL-284] Add unique index to users.username_idempotent

- indexer/core.go
- indexer/indexer.go
- indexer/nfts.go
**Changes**
* Ignores reporting errors because of a contract missing a metadata function to Sentry
* Enables sentry for the `nfts` and `contracts` handlers routine because it was missing before
> Indexer Sentry Followups

- indexer/core.go
- service/logger/logger.go
**Changes**
* Fixes bug where an error for the indexer-api is sent several times because of the sentry middleware, the error logger, and the sentry log hook
> Fix sending same errors multiple times to Sentry

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- service/multichain/tezos/tezos.go
- service/persist/token.go
Changes:
- **Added** `SyncingMedia` to the graphQL schema
- **Added** MediaTypeSyncing that will be returned when an NFT is still syncing
- **Added** resolvers for this media type
- **Updated** default case for graphQL media resolving to invalid instead of unknown. Unknown is a case we want to handle and expect to occur, invalid is a case where something is going wrong.
> syncing media

- indexer/indexer.go
Turns out the spam check adds a lot of latency to indexing and is a bottleneck in processing transfers (more than the actual downloading of the logs themselves), example trace from Sentry:
https://sentry.io/organizations/usegallery/performance/indexer:219bf50da08a41da8768fc97404bbf8c/?environment=local&project=6592179&query=&showTransactions=recent&statsPeriod=24h&transaction=indexer-main%3AstartPipeline&unselectedSeries=p100%28%29
I don't think the spam check should prevent new blocks from being indexed, so I'm removing it from the main path of the indexer. It probably makes sense to check for spam when a user syncs their tokens - around the time we fetch the media content and cache it. We can also prioritize refreshing media for tokens that aren't spam, then refresh tokens that are …
> Turn off spam

- service/multichain/poap/poap.go
There are only a few additional fields that we haven't been storing in the token metadata for POAPs. After speaking with the POAP team, it seems like we could come up with creative ways to showcase POAP-specific fields in the UI, so might as well store everything to future proof.
> Support all metadata for POAP

- service/persist/postgres/user.go
Communities were returning an extra set of empty results due to a slice initialization issue. Now they're not!
> Fix empty results in communities

- indexer/nfts.go
- service/multichain/multichain.go
- service/persist/token.go
Updates the dedupe logic when combining separate providers:
* Add `IsServable` method to the `Media` type. It seems that we can generalize on the fact that a token's media is servable if it has a media type and it has a media URL. Only types of `unknown` and `""` are missing a `media_url`
```
postgres=# select media->>'media_type' media_type, media->>'media_url' != '' has_url, count(*) count from tokens group by 1, 2;
media_type | has_url | count
------------+---------+--------
audio      | t       |   2953
json       | t       |      1
svg        | t       |  16431
animation  | t       |    901
unknown    | t       |  31228
html       | t       |  35120
video      | t       |  55509
text       | t       |    785
unknown    |         |   5673
gif        | t       |  34164
|         | …
```
> [GAL-422] Check if token's media is servable

- graphql/generated/generated.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- publicapi/token.go
Since the Admin UI is still down, we don't have an easy way to sync a user's tokens on their behalf. This PR adds a quick workaround for that: the `syncTokens` GraphQL mutation now has an optional `userID` field to specify whose tokens should be refreshed. I added a hacky "isAdminUser" function that just checks a hardcoded list of IDs to make sure the logged-in user is a Gallery admin before allowing them to sync someone else's tokens.
> [GAL-429] Allow Gallery admins to sync user tokens

- graphql/resolver/schema.resolvers.helpers.go
Small fix to resolve `Admirer` and `Commenter` users without hitting a nil pointer reference.
> Fill in Admirer and Commenter user IDs to prevent a nil pointer error

- publicapi/auth.go
- service/auth/auth.go
- We no longer check for a membership NFT or an entry in the `early_access` table when a user is signing up. Any address can create an account!
- This PR doesn't get rid of the `early_access` table or its associated access methods. @Robinnnnn made a comment about repurposing `early_access` for future stuff, and I think it's a good idea. We already have the table, a CLI app to add entries, methods to check it, etc. It'd be pretty easy to transform it into a general-purpose `allowlist` table with 2 columns: an address and some type to indicate what that address is allowlisted for. Let's leave the code for now and talk about whether it's worth evolving it into a new allowlist mechanism!
> [GAL-397] Stop checking early access / allowlist for signups

- service/multichain/multichain.go
Previously we would only replace `Media` if the incoming token is servable. Now we replace the entire token. This is because for new tokens the indexer, on first sync, will not have the other metadata fields available yet.
truth table for all the cases:
```
seen? | seen isServable? | incoming isServable? | outcome
-- | -- | -- | --
t | t | t | do nothing
t | t | f | do nothing
t | f | t | use incoming
t | f | f | do nothing
f | t | t | use incoming
f | t | f | use incoming
f | f | t | use incoming
f | f | f | use incoming
```
> Overwrite token if its servable

- indexer/core.go
Looks like the first arg is the executable being ran, so we actually want to parse the second and third args as the block range.
> Fix Indexer input arg indexing

- service/multichain/multichain.go
Changes:
- **Changed** `errWithPriority` to wrap error rather than assume the error is not nil and call its `Error()` func. This seems to be the cause of the panic at https://sentry.io/organizations/usegallery/issues/3534892888/?end=2022-08-27T03%3A59%3A59&project=6262886&query=is%3Aunresolved&start=2022-08-26T04%3A00%3A00
> wrap error correctly [GAL-431]

- .circleci/config.yml
- indexer/core.go
- indexer/indexer.go
- indexer/t__integration_test.go
- indexer/t__utils_test.go
**Changes**
* Added more tests (contracts, erc1155s, checking specific fields in db) and also refactored the tests a bit
* Refactored the indexer to make it easier to test, namely moving `rpcEnabled` to a global var and splitting the indexer `Start` method into `catchUp` and `waitForBlocks`  methods
> Add more indexer tests

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/collection.go
This PR adds a new `collectionsByIds` query to fetch multiple collections at a time. While putting this together, I realized that the automatic handling we use to map golang <-> GraphQL errors doesn't really work for resolvers that return a list of `SomethingOrError` types, so I've handled it manually here (and added comments about it).
It also adds `ErrInvalidInput` as an error type for `CollectionByIdOrError`, which was always a possible return type, but now it'll be handled appropriately.
> Add collectionsByIds query

- indexer/core.go
- mediaprocessing/mediaprocessing.go
- mediaprocessing/process.go
- middleware/middleware.go
- service/media/media.go
- service/rpc/rpc.go
- service/tracing/http.go
**Changes**
* Adds sentry error handling and tracing to mediaprocessing
* Figured out a way to patch GCP HTTP calls in Sentry so now we can also trace reads/writes from storage too
* Uses this gcp client in the indexer as well
Sample trace: https://sentry.io/organizations/usegallery/performance/mediaprocessing:7de37786f4054995a263339a5b12ca64/?environment=local&project=6771759&query=&statsPeriod=24h&transaction=processMedia&unselectedSeries=p100%28%29
> Add Sentry to mediaprocessing

- service/multichain/multichain.go
- service/persist/token.go
- service/persist/token_gallery.go
**Changes**
* Fixes tezos wallet sync. Before, if we already had a token with media in the db, we would replace the provider token with the token we had in the db. This was an issue because the token still references wallets that have since been deleted. Now we only replace the `media`.
> [GAL-467] Fix tezos wallet refresh sync

- service/media/media.go
- service/rpc/rpc.go
- util/helpers.go
Changes:
- **Changed** media grabbing to use the correctly mapped ipfs URLs for gateways so that we don't run into broken gateways. For example, `ipfs.infura.io` does not work anymore but some NFTs still use it. We should not rely on those API's being up when we can use the IPFS path with our own gateway and better guarantee success
> fixes for dave corp [GAL-485]

- service/persist/token.go
We were receiving token metadata with the value (shortened for example): `\x05\x02\\u0000\\u0000\\u0000l\a\x04\x01`. Note that the null char is escaped: `\\u0000` which is a totally valid string.
Converting to json, this turns into: `\\x05\\x02\\\\u0000\\\\u0000\\\\u0000l\\a\\x04\\x01`. Before, we removed null chars by checking for `\\u0000`, which results in: `\\x05\\x02\\\\\\l\\a\\x04\\x01` which is no longer valid because the `\l` char is not a valid escaped string in go (in non-JSON: `\x05\x02\\\l\x04\x01`). Now we first check for `\\\\u0000` then for `\\u0000`.
> [GAL-486] Replace escaped null chars

- docker-compose.yml
- docker/tokenprocessing/Dockerfile
There is a bug in `ffmpeg v4.1.x`, which is the latest available version on the buster distro, upgrading to bullseye fixed the issue.
> [GAL-484] Update tokenprocessing base to bullseye

- indexer/indexer.go
- indexer/nfts.go
Fixes edge case where the Indexer would get blocked when there are no logs because the transfers channel is never closed. Also removes the `batchTransfers` method because each plugin buffers its own messages
> Indexer - Always close channel

- indexer/indexer.go
Indexer was running into an issue where it would save logs it didn't have yet to GCP but not return it. Also removing saving errors to GCP because we have Sentry now
> Indexer - Use already assigned logsTo

- service/sentry/sentry.go
Updates the sentry logger to use our own custom grouping vs their own grouping.
> Use type for sentry error grouping

- service/sentry/sentry.go
**Changes**
* Updates the sentry logger to properly handle the generic `errors.errorString` so that they are grouped separately
> Sentry error reporting tweaks

- service/user/user.go
- validate/validate.go
For some historical reason, we've been using our own custom function to validate string lengths instead of using go-validator's built-in `max` tag. Our custom function was checking the number of _bytes_ in a string, not the number of _characters_. As a result, a 598-character collector's note was rejected by the server because it contained 622 bytes, even though our limit should be 600 characters, not 600 bytes.
This PR gets rid of our "max string length" validator and uses the built-in `max` tag in its place. I also got rid of a couple of validation tags we no longer use, and a related struct that we also don't use.
> Use "max" validation instead of a custom string length validator

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/interaction.go
- service/persist/admire.go
- Replaced `hasViewerAdmiredEvent` with `viewerAdmire`, the latter of which returns an `Admire` type instead of a bool. As it turns out, having the `admire` is more useful than just knowing it exists.
- `hasViewerAdmiredEvent` is still present -- for now -- so we don't break existing clients. It always returns false and should be removed once a new frontend without it has been deployed for a while.
- Adding/removing comments and admires will now return appropriate error types for handled errors: `ErrAdmireNotFound`, `ErrAdmireAlreadyExists`, and `ErrCommentNotFound`. These previously returned unhandled errors that weren't in our schema.
- The `removeAdmire`mutation takes an admireID again, instead of a userID + feedEventID (which I switched it to briefly before we settled on this latest …
> More comment/admire tweaks

- graphql/resolver/handlers.go
The `viewerAdmire` field returns nil (without an error) for users who haven't admired an event. That's intentional, but it's not something that ever happened when I implemented tracing for GraphQL. I had been assuming anything that _didn't_ return an error would return a non-nil result. Since that's not the case with `viewerAdmire`, we run into a nil dereference error when trying to add the resulting node ID to our trace span.
This PR fixes that issue, and also reorders the `if` statement to close spans regardless of whether there was an error, which should have been the case all along.
> Don't add trace data for nil result pointers

- service/multichain/eth/eth.go
Changes:
- **Changed** the conversion from indexer contracts to agnostic contracts to use capacity instead of length because otherwise `append` does nothing causing contracts to get updated with empty data
> append with capacity set not length

- graphql/resolver/handlers.go
I thought I had fixed this issue previously, but I was wrong: an interface in golang can be non-nil and still point to a nil value. In this case, the interface is "an interface that points to a pointer to an Admire," where the interface itself is not nil, but the pointer to an Admire is. I've added reflect methods to handle this case, and have verified locally that the panic is gone.
> Fix panic when adding nil viewerAdmire to trace data (again)

- graphql/resolver/schema.resolvers.helpers.go
- service/persist/collection.go
- Default 0-column layouts to 3 columns
- Old collections that predate multi-column have been returning `0` columns instead of the original default of `3`. This leads to a confusing situation when editing a gallery: the column count is set to 0 and none of the tokens show up. Viewing a collection works better; the frontend appears to enforce a minimum of at least 1 column, so these collections are visible, but they're using a 1-column layout when they had previously been using a 3-column layout.
- `maxTokensPerSection` is now 1000 instead of 500
- A few collections that predate multi-section have more than 500 tokens in them. When trying to convert those collections to sectional layouts, we encounter an error because a 641-token collection can't fit into a 500-token section. I've bumped …
> [GAL-563] Layout default + limit tweaks

- publicapi/pagination.go
- publicapi/token.go
- service/media/media.go
- tokenprocessing/process.go
Changes:
- **Changed** time marshaling to use JSON instead of binary (binary was causing some bad utf8 characters to appear but JSON will always be valid utf8)
- **Changed** token processing to also update name and description because previously the tokens would just keep the name and description they have when being updated which is often empty.
> use different time marshalling

- publicapi/pagination.go
- Since we expect to have more cursor types in the future, I thought it might be helpful to make encoding/decoding them more modular. This PR adds `cursorEncoder` and `cursorDecoder` helper structs that work with all of our existing cursor component types (bool, time, DBID). They handle length-prefixed encodings automatically so cursor implementations don't need to worry about those details anymore.
> Add cursor encode/decode helper methods

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- event/event.go
- publicapi/interaction.go
- service/notifications/notifications.go
- service/persist/event.go
- service/persist/postgres/event.go
Noticed while getting the Feed Caption branch up to date that foreign key errors popped up as I was commenting and admiring stuff. This also removes the `ResourceTypeFeedEvent` type since it doesn't seem to be needed anymore.
> Comment and Admire Notification Fixups

- Makefile
- README.md
- docker/postgres/circle/DOCKERFILE
Addresses https://github.com/gallery-so/go-gallery/issues/609 and https://github.com/gallery-so/go-gallery/issues/608
* Removes the old circleci postgres image since we create a new instance per test suite
* Removes some inaccurate README stuff
> Remove circle image and update README

- service/multichain/multichain.go
- tokenprocessing/tokenprocessing.go
Changes:
- **Changed** cache and throttle times related to communities to 30 minutes
> reduce cache and throttle time for communities

- service/multichain/multichain.go
Changes:
- **Added** one extremely short little check at the end of the sync step to try to get name and description fields from the metadata if they are not set for a token. 
- When a token has valid media in the indexer server or token processing server, it will not get processed regardless of whether it has a name or description. We used to have a check for this but got rid of it. I think it would be best to add a separate check on these services for other metadata fields that are required like `name` and `description`, and it will be a separate check so we don't need to do a full media refresh just for a missing name. I can work on this tomorrow or this can be a part of the `token_metadata` table addition we are planning to add.
> get name and desc in sync if not set

- cmd/update/main.go
- indexer/core.go
- indexer/indexer.go
- indexer/nfts.go
- service/multichain/eth/eth.go
- service/multichain/multichain.go
- service/persist/postgres/token.go
- service/persist/postgres/token_gallery.go
- service/persist/token_gallery.go
- tokenprocessing/process.go
Changes:
- **Added** another check at the indexer level for tokens with valid media and metadata but without a name or description so that those fields can get updated even when the media is all good
- **Changed** some naming as well as started using a consistent shorthand function for getting metadata fields from the metadata `media.FindNameAndDescription`
> name and description nets

- service/auth/auth.go
Panic occurring on login due to the wrong variable being used and this variable was a pointer that was always nil at the time it was being called.
> pointer panic caused by wrong variable

- cmd/notifications_prepop/main.go
Changes:
- **Added** a new script for prepopulating ~10 notifications based on a viewer ID and uses random data from the DB to fill the rest.
```bash
go run cmd/notifications_prepop/main.go ${some_viewer_id}
```
> script for prepopulating notifications

- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
**Changes**
Tokens returned by the OpenSea provider would occasionally return tokens with no owner. The fix is to use the address returned by the OpenSea API versus using the input `address` as the owner.
Tested by refreshing a few communities and verifying that the `owned_by_wallets` field is not null and also owned by the expected wallet.
> Fix owned_by_wallets null constraint error

- feed/merge.go
- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
Realized that we can simplify the grouping logic a bit. If a create event exists, then we can just classify the grouped event as a CollectionCreatedEvent instead of a CollectionUpdatedEvent.
In other words, the CollectionUpdatedEvent is only shown when you add tokens AND a new note to an existing collection.
> Remove isNewCollection from schema

- emails/emails.go
- indexer/core.go
- indexer/t__integration_test.go
- service/logger/logger.go
- service/sentry/sentry.go
- tokenprocessing/tokenprocessing.go
Removes `configureRootContext` and adds the sentry logger for the Indexer after `InitWithGCPDefaults` is called.
> Remove configureRootContext

- cmd/notifications_prepop/main.go
- db/gen/coredb/models_gen.go
- db/gen/coredb/query.sql.go
- db/migrations/core/000040_drop_events_actor_id_non_null_constraint.down.sql
- db/migrations/core/000040_drop_events_actor_id_non_null_constraint.up.sql
- event/event.go
- feed/event.go
- publicapi/collection.go
- publicapi/gallery.go
- publicapi/interaction.go
- publicapi/publicapi.go
- publicapi/token.go
- publicapi/user.go
- service/notifications/notifications.go
- service/persist/event.go
- sqlc.yaml
**Changes**
* Drops the non-nullable constrain from the `actor_id` column of `events` since its possible to have events not initiated by a gallery user (like viewing a gallery when unauthenticated)
* Fixed a bug that popped up after fixing that issue where the wrong notification event was being queried, resulting in no rows returned
* Changed the `caption` go backed typed from our `persist.NullString` to the builtin `database/sql.NullString` (sidenote: I was having issues having our `persist.NullString` type insert `NULL` values into the db, but didn't dig in too deeply)
> Fix actor_id foreign key error

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- service/persist/postgres/token_gallery.go
- Instead of outright dropping the `tokens.token_uri` column, this PR is a minimally invasive way to avoid the performance impact of large token URIs. It changes the 3 places where we write values to `token_uri` to write an empty string instead, and removes the `tokenURI` field from our GraphQL schema. Once this PR is merged, we should also run a SQL statement to set all existing `token_uri` values to the empty string.
- Why not drop the column entirely?
- We'll drop the column soon enough, but dropping it right now would involve updating a bunch of places in the codebase that I'm about to refactor anyway. I'll start removing uses on a case-by-case basis, and eventually we won't use the column anymore.
> Stop using tokens.token_uri column

- event/event.go
Skips notifying the user if they're interacting with a resource they own themselves.
> [GAL-637] Skip notifying self events

- publicapi/gallery.go
Before we were using `gc.RemoteIP()` as the value in the hash to generate the `externalD`, but this IP is of the final proxy's IP address. This PR updates the generation to use the forwarded IP from the `X-Forwarded-For` header which is luckily already being delivered to the backend.
Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
> Use forwarded client IP for externalID

- service/media/media.go
Changes:
- **Changed** deleting of medias to happen after the medias are cached or not cached so that we don't accidentally delete something that the other caching process needs
- **Changed** thumb-nailing to be synchronous because otherwise it might try to thumbnail a video that does not exist on GCP yet
> move deleting and thumbnailing [GAL-664]

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- feed/event.go
- service/persist/postgres/event.go
Events from different collections were grouped together. This PR adds a `include_subject` flag to the query to indicate if the query should only group events having the same subject.
> [GAL-692] Fix grouping of update events

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
Email-related mutations send tokens and email addresses that should be scrubbed. This PR adds the `@scrub` directive where necessary.
Our scrubber only handles GraphQL `Input` types, so I also updated `verifyEmail` and `preverifyEmail` to use input types. **This is a breaking change in the schema!**
> Scrub email and token values from email mutations

- emails/send.go
Changes:
- **Changed** email send to not include ASM group ID so that sendgrid does not automatically send a second unsub button
> no asm causing double unsub button

- server/server.go
- service/media/media.go
- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
- service/multichain/poap/poap.go
- service/multichain/tezos/objkt.go
- service/multichain/tezos/tezos.go
- service/multichain/tezos/tzkt.go
**Changes**
This PR adds the `ObjktProvider` to Tezos and also some refactoring along the way:
I broke up the multichain `ChainProvider` interface into several, smaller interfaces. This should make it easier to add new providers and also makes it easier to test specific functionality of our providers. 
I also added a generic `FallbackProvider` which calls a "backup" provider for token responses that contain no metadata, which happens semi-frequently for the tzkt API. Tezos is configured with tzkt as the main provider, and objkt as the backup. I went this route because objkt has pretty strict usage requirements and was a little worried that we'd hit their usage limits if we were to call it for each tezos sync as we do for OpenSea. Note this means that this provider only replaces tokens, it …
> [GAL-480] Add Objkt Provider

- service/media/media.go
Changes:
- **Changed** hic et nunc keywords to prioritize artifact which is normally the only URI that exists for a token but is sometimes overridden by a lower quality display URI
> artifact is better for hic et nunc [GAL-743]

- middleware/middleware.go
`OPTIONS` requests make up a lot of our Sentry traces, but they don't contain any useful data because there's nothing to trace. This PR filters them out so they won't count against our quota.
> Don't send traces for OPTIONS requests

- docker/indexer_api/Dockerfile
We always want RPC enabled for the indexer server, even on `dev`.
> Add --enable-rpc flag to entrypoint

- indexer/metadatas.go
Changes:
- **Changed** ens handler to use `Helvetica Neue` which we seem to use on the frontend and does not require any fancy font hosting because it is default in most browsers.
> use one of the fonts we use for ens

- publicapi/collection.go
This PR trims leading and trailing whitespace chars from the collection name input.
> Trim collection names

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- go.mod
- go.sum
- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/model/remapgen_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- publicapi/feed.go
Two new mutations with `@retoolAuth`
- `syncTokensForUsername`: Same inputs as `syncTokens` except we take a `username` because we're not logged in
- `banUserFromFeed` to insert a user into the blocked table.
I left some comments in the PR w/ some questions / uncertainty.
> Retool mutations

- service/multichain/multichain.go
Tezos syncs were silently skipped because the provider for Tezos, `FallbackProvider` didn't implement the `tokensfetcher` interface which is required to run syncs. This PR adds `GetTokensByContractAddressAndOwner` so that it conforms to the interface.
Will follow up with a PR to validate our multichain configuration so that it fails if we don't have at least one valid `tokensfetcher` to use.
> Add GetTokensByContractAddressAndOwner to fallback provider

- graphql/generated/generated.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- publicapi/token.go
Since we're moving to Retool for admin-esque things. I've separated out the logic for syncing tokens based on the use case.
1. Syncing tokens as an admin (from Retool). Takes a username and is assumed to be authenticated by the time you're in that context.
2. Syncing tokens as a user. This mutation should not take a `userId`. Totally made sense before when we didn't have Retool.
This is technically a breaking change (removing a parameter from a mutation) but we're not actually using it on the frontend so I'm not super concerned.
> Fix syncTokensForUsername for Retool and deprecate old admin behavior

- tokenprocessing/process.go
- tokenprocessing/tokenprocessing.go
Realized after digging through the logs and the db tokens get stuck in `syncing` when a user tries to sync shortly after the first sync (they add a new wallet for example). There are two locks involved in syncs: one managed by the backend that has a 5 minute TTL, and the other managed by tokenprocessing that has a 30 minute TTL which only gets released after it expires.
what was happening:
```
* user syncs
* backend acquires lock (ttl 5 min)
* new tokens found and set to `syncing`
* backend sends message to tokenprocessing
* backend releases lock
* tokenprocessing gets lock for user (ttl 30 min)
* tokens get proccesed
```
then 10 minutes later the user tries to sync again:
```
* backend acquires lock (ttl 5 min)
* new tokens found and set to `syncing`
* backend sends message to …
```
> Unlock throttler after syncs

- service/media/media.go
- service/rpc/rpc.go
Changes:
- **Added** a space trim to the final media URLs because the browser freaks out when there is trailing space on an image url
- **Added** an unescape to SVGs because often times svgs will be query escaped in the token URI (have to test that this does not affect the already unescaped svgs before merging)
> trim space and un escape svg

- publicapi/merch.go
- server/server.go
Changes:
- **Changed** redeem token to not use secret manager but use env instead because cloud run will now be using secret manager to put the key into the env
> have gcp manage secret access by pushing into env

- service/multichain/multichain.go
Changes:
- **Changed** the `GetTokensOfContractForWallet` multichain function to not upsert tokens if there is no gallery user that owns the tokens (because the token requires an `owner_user_id` field)
The purpose of the upsert was just to take advantage of the fact that we are receiving up to date information from a provider and we might as well update our version of the token to optimistically keep it up to date, but it is not a necessary step in this function.
> no upsert if user does not exist

- service/notifications/notifications.go
- service/pubsub/gcp/pubsub.go
Background:
Whenever a backend instance starts, it creates a new subscription to the notification pubsub topics so that it can receive notifications published by other instances. However, there is a quota limit of 10,000 subscriptions per project: https://cloud.google.com/pubsub/quotas. I noticed that the dev backend was failing to start because we had already exceeded the quota for that project. 
This PR reduces the expiration of a subscription from 31 days to 3 days. This means that if a subscriber hasn't consumed from that subscription in 3 days, that subscription will be deleted. In the future, I think we can look into re-using subscriptions or cleaning up the subscription when the server spins down.
> Change subscription expiration from 31 days to 3 days

- .github/workflows/tests.yml
- .vscode/extensions.json
- .vscode/settings.json
- Makefile
- graphql/schema/schema.graphql
- package.json
This PR aims to remove the formatting pain we have with the GraphQL Schema file.
- Ensures the schema is formatted before landing a diff on the `main` branch.
- Formatting is aligned with the frontend repo standards.
- I'm willing to make an exception in the frontend config if y'all want to make some changes.
- Using `prettier` since we already had a `package.json` file.
- Added a new `make format-graphql` in the root which does the following.
- Does a `yarn install` this is instant if you're already up to date
- Formats your `graphql/schema/schema.graphql` to spec.
- If you're not happy with the formatting settings, let's discuss in the eng gm
- Are there any alternatives we can rely on w/o `node`?  Something more native to Golang maybe?
1.Make sure you have the `Prettier` (bundled) …
> Automate schema formatting

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- go.mod
- go.sum
- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/gallery.go
- publicapi/publicapi.go
Changes:
- **Changed** schema typo for `updatedCollections` field on update gallery input
- **Changed** sql var names in query for updating gallery to not use two versions of the gallery id (`id` and `gallery_id` were the same thing but only one was being set correctly)
- **Changed** sql query for updating gallery to use conditional logic for updating fields to only update the field if the field passed in was not null
- **Changed** `resolveGalleryByGalleryID` to actually resolve the new fields that are not resolved by other resolvers, fixing the bug where an update might occur correctly but the payload response for the update would not include the updated fields simply because they were not being included in the resolver
> conditional update, correct resolver, correct sql var names [GAL-1693]

- db/migrations/core/000044_multi_gallery.up.sql
On my local database, reworking this SQL migration statement takes it from ~40 seconds to ~300ms, which is fast enough to run without scheduling downtime! The second `gallery_id` migration statement takes about 3s still, but I think that's fine for our purposes.
> Use CTE and skip "is null" check to speed up gallery_id migration

- publicapi/gallery.go
This PR removes some copy and pasted code to check if an IP is private, in favor of the `ip.IsPrivate` method that's available on the `net/http` package. It also simplifies the `getExternalID` function to use the gin context's `ClientIP` method that I just found out about which will also try to find the forwarded client IP.
> Refactor external ID

- db/migrations/core/000046_multi_gallery_adjustments.down.sql
- db/migrations/core/000046_multi_gallery_adjustments.up.sql
Changes:
- **Added** a constraint and dropped the position index on the galleries table so that we can update with deferred mode
- **Added** a migration step setting the featured gallery of every user
- I just removed the index altogether, do we still want the index even though we won't be using it to query or validate any constraints?
> adjust schema for updates and featured gallery

- db/migrations/core/000048_multi_gallery_adjustments.up.sql
Changes:
- **Removed** position, owner_user_id index on galleries because the constraint on those fields already creates an index
> no index on position

- .github/actions/build-deps/action.yml
- .github/workflows/deployer.yml
- .github/workflows/sandbox.yml
- .github/workflows/tests.yml
- Makefile
- secrets/dev/backend-env.yaml
- secrets/dev/backend-sandbox-env.yaml
- secrets/prod/backend-env.yaml
This PR brings back up [api.sandbox.gallery.so](https://api.sandbox.gallery.so) for the sandbox.
**Changes**
* Added a `sandbox.yml` workflow which currently only deploys the backend to the sandbox env. This workflow can be adhoc and a branch can be provided to deploy that specific branch.
* Moved the CI build dependencies (sentry, sops, gcloud) to a separate action `build-deps` which gets called in our workflows
* Added `ETH_PRIVATE_KEY` to our secret vars to replace the secrets managed by Secrets Manager
* Updates `backend-sandbox-env.yaml` which values from `backend-env.yaml`
**Post Merge Tasks** 
*  [ ] When deploying to `dev` and `prod` a new revision on Cloud Run will first need to be manually added thats removes the Secrets Manager connection. Cloud Run will complain that the env …
> Add sandbox env

- README.md
- db/gen/coredb/models_gen.go
- db/gen/coredb/query.sql.go
- db/migrations/core/000051_add_legacy_views.down.sql
- db/migrations/core/000051_add_legacy_views.up.sql
- db/queries/core/query.sql
Adds a table of views from Mixpanel and Google Analytics with data prior to when we started tracking external IDs to include in the all time trending users report.
**Post Merge Tasks**
> Add legacy views

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
The old query was double counting legacy views because the granularity of the legacy views table is lower than the rollup CTE. In this case, we should use `min` or `max` or `avg` instead of `sum`.
> Use correct agg function in trending query

- emails/jwt.go
- middleware/middleware.go
- secrets/dev/backend-env.yaml
- secrets/dev/backend-sandbox-env.yaml
- secrets/dev/emails-server-env.yaml
- secrets/dev/local/app-dev-emails.yaml
- secrets/local/local/app-local-emails.yaml
- secrets/prod/backend-env.yaml
- secrets/prod/emails-server-env.yaml
It's time to rotate the JWTs we use for auth tokens! Since invalidating them immediately would log users out, this PR uses a transitional approach that checks for a JWT_SECRET_ROTATING_OUT variable, too.
How it works:
- new tokens are issued with JWT_SECRET
- existing tokens are validated with JWT_SECRET
- if validation fails, existing tokens are validated with JWT_SECRET_ROTATING_OUT
We can remove all of the rotation stuff next week. Our JWT TTL on prod was set to 3 days (again, somehow!), so it won't take long for all the old tokens to expire.
Follow-ups: the rotation code I added for email JWTs is a little messy, but I'd like to see if we can clean everything up with generics and consolidate our JWT functions (as per the comment at the top of the emails JWT file!)
> Rotate auth JWTs

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- go.mod
- go.sum
- graphql/generated/generated.go
- graphql/generated_test.go
- graphql/graphql_test.go
- graphql/testdata/operations.graphql
- publicapi/pagination.go
Changes order of the hot feed connection so that the most popular feed item now appears last. For example, the query `trendingFeed(last: 5)`:
will return:
```
[
eventA -- fifth most popular event
eventB
eventC
eventD
eventE -- most popular event
]
```
and the query `trendingFeed(last: 1, before: <cursor of eventE>)` will return:
```
[
eventD -- second most popular event
]
```
> Change pagination order of hot feed

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- emails/t__utils_test.go
- graphql/generated/generated.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/token.go
This PR updates resolvers that return `[CollectionToken]` to return even if some tokens have been `deleted`. For example, if a request is made for a collection updated event with tokens: `tokenA`, `tokenB`, and `tokenC`, but `tokenB` is deleted, the reply will be:
```
{
"newTokens": [
{
"token": {
"name": "tokenA"
}
...other fields
}
null, -- tokenB is missing!
{
"token": {
"name": "tokenC"
}
...other fields
}
]
}
```
A request for a feed event with one new token that is deleted:
```
{
"newTokens": [
null
]
}
```
A request for a feed event with no new tokens:
```
{
"newTokens": []
}
```
This PR also changes the `collection` field of `CollectionToken` to a forced resolver so that we don't fetch a collection where it isn't needed.
> Allow missing tokens in resolver

- db/gen/coredb/query.sql.go
- db/migrations/core/000054_add_events_gallery_edit_index.down.sql
- db/migrations/core/000054_add_events_gallery_edit_index.up.sql
- db/queries/core/query.sql
- graphql/generated/generated.go
- graphql/graphql_test.go
- graphql/model/models.go
- graphql/schema/schema.graphql
- publicapi/feed.go
This PR updates the trending user report to only consider users that made edits to their galleries during the reporting window and also to use unique viewers as the criteria instead of views. This should help decorrelate weekly trending users from all time users and have more variety of users because each report uses a different set of criteria.
**Post Merge TODOs**
> Update User Trending Report

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- publicapi/feed.go
This PR adds an [exponential decay](https://en.wikipedia.org/wiki/Exponential_decay) term to the trending feed calculation to penalize events that are older in age. This decay rate can be tuned using the `lambda` parameter which controls how quickly values decrease over time.
> Add time factor to trending feed

- secrets/local/local/app-local-tokenprocessing.yaml
- service/media/media.go
- service/rpc/rpc.go
- tokenprocessing/process.go
This PR fixes the unauthenticated error which was preventing media for tokens to be cached. This PR also adds additional logger fields to help make tracing individual tokens in Cloud Logs easier.
> Fix GCP storage client error

- service/multichain/eth/eth.go
- service/multichain/multichain.go
- service/rpc/rpc.go
**Changes**
* Always try to remove the BOM when reading JSON data of token URIs
* If an individual token is refreshed, we now will always try to have tokenprocessing cache the new media
> Tokenprocessing fixups

- graphql/graphql_test.go
Using a server client instead of a handler client to make tests less flakey.
> Use server client for test

- publicapi/feed.go
This PR increase the refresh rate so that scores are calculated more frequently. This also increases the decay rate so that older events falls off steeply.
> Increase decay and refresh rate of trending feed

- emails/jwt.go
- middleware/middleware.go
- secrets/dev/backend-env.yaml
- secrets/dev/backend-sandbox-env.yaml
- secrets/dev/emails-server-env.yaml
- secrets/dev/local/app-dev-emails.yaml
- secrets/local/local/app-local-emails.yaml
- secrets/prod/backend-env.yaml
- secrets/prod/emails-server-env.yaml
- Bump JWT expiration to 4 weeks
- Remove the JWT migration path I added a few weeks ago. The goal was to start issuing tokens with a new key while allowing tokens issued with the old key to remain valid. At this point, all JWTs issued with the old key should be expired, so we can drop support for it.
> Bump JWT expiration + remove migration path

- gqlgen.yml
- graphql/genqlient.yaml
- graphql/graphql_test.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/federation.graphql
`genqlclient` and `gqlgen` aren't playing nice together. Since we added federation support, `gqlgen` automatically injects some schema stuff for us that `genqlclient` doesn't know about. 
I've fixed this by vendoring the federation schema and telling `genqlclient` about it explicitly.
I also fixed the issue with the missing go dep by adding `go get xxx` to `go:generate` as recommended by this thread https://github.com/99designs/gqlgen/issues/1483#issuecomment-949023482
> Fix `go generate`

- service/media/media.go
- service/rpc/rpc.go
**Background**:
I noticed for MakersPlace that media is served from their IPFS gateway:
https://ipfsgateway.makersplace.com/ipfs/QmV7Zk9joyNpoi8Q8ZPZL6ywoTyRhbXevYUYvWEXLcovCt
The raw IPFS URI would be:
ipfs://QmV7Zk9joyNpoi8Q8ZPZL6ywoTyRhbXevYUYvWEXLcovCt
And mapped to our gateway would be:
https://gallery.infura-ipfs.io/ipfs/QmV7Zk9joyNpoi8Q8ZPZL6ywoTyRhbXevYUYvWEXLcovCt
Only the MakersPlace URL loads, but the IPFS URI and our gateway times out. I think it's safe to assume that if media doesn't load from the original gateway then its unlikely to load from our gateway unless their gateway is actually down. I think in those cases we would want to actually use our own gateway, but we don't have a mechanism to retry yet since we only have a single timeout per token.
> Skip remap for IPFS gateways

- publicapi/token.go
This fixes an issue where tokens would otherwise be loaded twice as part of the `newTokens` resolve in a feed event.
> Use dataloaders when getting tokens by IDs

- indexer/nfts.go
- secrets/dev/local/app-dev-tokenprocessing.yaml
- secrets/prod/local/app-prod-tokenprocessing.yaml
- service/media/media.go
- service/multichain/eth/eth.go
- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
- service/rpc/rpc.go
- tokenprocessing/handler.go
- tokenprocessing/process.go
Changes:
- **Added** token metadata fetcher to opensea provider
- **Added** manual index step to indexer API metadata fetcher
- **Changed** indexer API metadata fetcher to not return when a token is not found, and instead continue the process of finding metadata using the blockchain
> find metadata anyway on indexer, fallback to opensea

- indexer/nfts.go
- indexer/refresh/refresh.go
- service/media/media.go
- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
- util/response.go
There's an issue with the OpenSea API where it doesn't seem to return all tokens if only the owner address is used in the query. Including the owner address and the contract address seems to get around this issue. This PR also wraps calls to OpenSea with retries so that requests retry and backoff if we get rate-limited. It also refactors the pagination to use a loop vs recursion which makes it a little simpler to read (at least for me!)
> Fix missing OS tokens bug

- db/migrations/core/000067_add_schedule_search_relevance.up.sql
Now that pg_cron is up and running, it's time to keep our search relevance tables up to date. Thanks @jarrel-b!
This PR refreshes the `user_relevance`, `contract_relevance`, and `gallery_relevance` tables every hour, and staggers the start times (:05, :10, :15) to avoid running a bunch of operations at the same time.
> Use pg_cron to refresh search relevance tables

- db/gen/coredb/batch.go
- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- publicapi/pagination.go
- publicapi/user.go
This PR changes the sort order of shared followers and shared communities to descending when paging forward, and ascending when paging in reverse.
> Change sort order of shared followers and communities order 

- indexer/indexer.go
- service/media/media.go
- service/multichain/eth/eth.go
- service/multichain/multichain.go
- service/persist/postgres/token.go
- service/persist/token.go
- service/task/cloudtask.go
Changes:
- **Added** a check at the end of the indexer pipelines that will go through every Ethereum log and ensure that there is a token for the log in the database, logging if not
- **Changed** media processing to not delete videos if thumbnailing fails
- **Changed** wallet hook to match the correct interface definition
- **Changed** polling process in a few ways to simplify things and make everything easier to reason about (and remove chances for race conditions because we were editing a shared struct field from within a goroutine without a mutex): 
1. Only poll in groupings of 50 blocks, just like the indexer does during the catchup process
2. Don't send to transfer processing in groupings of 4, send all together like the indexer does during the catchup process
> indexer checks at the end of each pipeline that tokens exist for each log

- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
* Removes including the contract_address in the query param to OS
* Doesn't return if we get an unsupported token type from OS
* Tries to get the first valid metadata from the providers
> Revert OS changes

- db/gen/coredb/models_gen.go
- db/migrations/core/000069_add_scrubbed_pii_views.up.sql
- db/migrations/core/000070_update_owned_contracts_view.up.sql
The `owned_contracts` view now contains additional columns for `user_created_at` and `displayed_count`. I kept the `displayed` bool because I think it's more convenient for indexing, and there's no danger of it getting out of sync with the `displayed_count` column since this is a materialized view and can't be edited manually.
@jarrel-b I had previously mentioned getting rid of the `tokens.is_user_marked_spam` check, but honestly, I don't think it'd make a meaningful difference for my purposes, so I left it in!
> Add additional details to owned_contracts view

- graphql/graphql_test.go
- graphql/schema/schema.graphql
I originally had the idea to refactor the event dispatcher so that we could patch it so that it will store events immediately for tests. This mostly worked, but it caused issues with the Update -> Publish Gallery flow because it would save each update of that edit group as a feed event which is bad because `group_id` has a unique constraint on the `feed_events` table, and we only want a feed event saved at publish time. Rather than going down that rabbit hole that, I just decided to add sleep to the flaky tests 🤷‍♂️
> Add sleep to tests

- indexer/indexer.go
- indexer/plugin.go
- service/rpc/rpc.go
Changes:
- **Changed** indexer to get owner directly from the blockchain for ERC-721 tokens just like we do with balances for ERC-1155 tokens
- More calls from alchemy. Given that we tend to use about 5%-15% of our current prepaid units I don't anticipate this being an issue
> get owner reliably from the blockchain

- service/multichain/multichain.go
Changes:
- **Added** check to ensure that we only replace valid thumbnails for media types that need thumbnails
> only use valid thumbnail for animation like media

- indexer/core.go
- service/multichain/multichain.go
- tokenprocessing/process.go
This PR changes tokenprocessing to reply with a `429` status code when a sync is already in progress for a user. Replying with a non-200 status code will re-queue the message for retry so that tokens that are syncing will eventually get processed again.
This PR also ensures that only newly synced tokens are sent to tokenprocessing so that consecutive syncs don't send the same faulty tokens to tokenprocessing each time.
> Fix syncing bug and only process new tokens on syncs

- service/multichain/opensea/opensea.go
Request from OS we're failing since `ownerAddress` can occasionally be empty.
[Cloud run logs](https://console.cloud.google.com/logs/query;query=resource.type%20%3D%20%22cloud_run_revision%22%0Aresource.labels.service_name%20%3D%20%22tokenprocessing-v2%22%0Aresource.labels.location%20%3D%20%22us-east1%22%0A%20severity%3E%3DDEFAULT%0A%22Address%20like%20string%22;timeRange=2023-03-28T22:29:09.435Z%2F2023-03-28T22:29:09.435Z--PT24H;cursorTimestamp=2023-03-28T21:47:57.513559420Z?project=gallery-prod-325303)
> Fix OpenSea fetch metadata

- indexer/core.go
- indexer/hook.go
- indexer/indexer.go
- indexer/plugin.go
- indexer/t__utils_test.go
- secrets/local/local/app-local-indexer-server.yaml
- secrets/local/local/app-local-indexer.yaml
- secrets/prod/app-prod-indexer.yaml
- secrets/prod/local/app-prod-indexer-server.yaml
- secrets/prod/local/app-prod-indexer.yaml
Changes:
- **Added** a batch call for contract metadata to only use a few compute units per pipeline
> get contract metadata using batch api

- service/media/media.go
Changes:
- **Added** wait for deletion of media to prevent concurrency from allowing media URLs to be valid when requested but invalid for the end user
> wait for delete because url could be in use

- indexer/core.go
- secrets/dev/app-dev-indexer.yaml
- secrets/dev/backend-env.yaml
- secrets/dev/local/app-dev-backend.yaml
- secrets/dev/local/app-dev-tokenprocessing.yaml
- secrets/dev/tokenprocessing-env.yaml
- secrets/local/local/app-local-backend.yaml
- secrets/prod/backend-env.yaml
- secrets/prod/local/app-prod-tokenprocessing.yaml
- server/server.go
- service/multichain/tezos/t__utils_test.go
- service/rpc/rpc.go
Changes:
- **Added** an IPFS gateway fallback
Created a cloud run service called `ipfs` that has low specs but can handle cases where our primary gateway fails.
> fallback for ipfs gateway

- service/multichain/alchemy/alchemy.go
These params were in the wrong order, which was causing some lookups to fail
> Swap order of owner / contract address parameters

- db/gen/indexerdb/models_gen.go
- db/gen/indexerdb/query.sql.go
- db/migrations/indexer/000003_stats.up.sql
- db/queries/indexer/query.sql
- indexer/core.go
- indexer/hook.go
- indexer/indexer.go
- indexer/t__utils_test.go
- sqlc.yaml
Changes:
- **Added** `blockchain_statistics` with information on each pipeline the indexer processes
- **Added** queries for updating and inserting statistical information
What we keep track of:
- Total logs processed
- Total transfers processed
- Total contracts found
- What methods we use for finding contract owner
- Success of pipeline
- Total time taken for pipeline in seconds
> keep track of indexer stats each pipeline

- adminapi/admin.go
- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- emails/t__utils_test.go
- publicapi/user.go
- service/multichain/multichain.go
- service/persist/postgres/postgres.go
- service/persist/postgres/user.go
- service/user/user.go
Changes:
- **Changed** the user creation pipeline to use an sqlc queries with an attached transaction so that the user cannot be created in a broken state if any other error occurs down the pipeline.
> create user inside tx

- cmd/optimization_backfill/main.go
- indexer/nfts.go
- service/media/media.go
- service/multichain/multichain.go
- service/rpc/rpc.go
- tokenprocessing/process.go
- util/retry/retry.go
Changes:
- **Changed** storage writer to use a smaller chunk size and retry with the retry mechanism specified by [this doc on GCP](https://cloud.google.com/storage/docs/json_api/v1/status-codes)
- **Changed** RPC http client to use no timeout (this client is always used and should always be used with requests that hold contexts, the request context should be used for timing out, not the http timeout e.g. `http.NewRequestWithContext` then `defaultHTTPClient.Do`) 
- **Changed** some workerpools into the more efficient and reliable `sourcegraph/conc` pools.
> increase reliability of storage upload

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
Changes:
- **Added** fallback media to all media types
- New Feature: Added `fallbackMedia` field to all media types in the GraphQL schema.
> "Fallback media for all,  
> No more media fallbacks that fall.  
> With this new feature,  
> Our code is now a creature,  
> That's robust and stands tall."
> fallback on everything

- tokenprocessing/tokenprocessing.go
Release Notes:
- Bug fix: Group Sentry errors by chain and contract address for all media processing errors in `tokenprocessing/tokenprocessing.go`. Removed an unnecessary check that was previously in place.
> "Errors grouped by chain and contract, unnecessary checks now effaced. Codebase improved, bugs erased."
> Try to group by chain and contract for all Sentry errors from tokenprocessing

- debugtools/debugtools_common.go
- debugtools/debugtools_enabled.go
- docker/backend/dev/Dockerfile
- graphql/generated/generated.go
- graphql/generated_test.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/auth.go
- secrets/dev/backend-env.yaml
- secrets/dev/backend-sandbox-env.yaml
Per @Robinnnnn's request, this PR enables debug tools on dev.
Some considerations:
- our dev environment doesn't contain sensitive information, but it's still public-facing and accessible by anyone on the internet. In the interest of not having strangers mess around with accounts while we're testing stuff on dev, I've added password protection to debug tools on dev.
- local environments technically use a password now, too, but the password is empty and can be omitted.
- prod is still several layers of isolation away from any of this: compile-time and runtime safeguards continue to ensure that debug logins do not work in production environments.
- @Robinnnnn The debug login popup seems pretty broken right now, so we may want to clean that up! We'll also need to add a field for "debug tools …
> Enable debug tools on dev

- Makefile
- docker/backend/dev/Dockerfile
- docker/backend/prod/Dockerfile
- docker/indexer/Dockerfile
- docker/indexer_api/Dockerfile
- docker/tokenprocessing/Dockerfile
Release Notes:
- Chore: Upgraded the version of ffmpeg to 4.3.6 by using an argument for the version number instead of hardcoding it in various Dockerfiles.
> "Upgrading ffmpeg,  
> Dockerizing with ease.  
> Code quality improved,  
> Celebrate with some 🧁!"
> Upgrade ffmpeg to 4.3.6

- service/media/media.go
Changes:
- **Added** quick fix for svgs needing `image/svg+xml` to render inline as opposed to `image/svg` which requires a content dispostion header to render (which we never provide)
> xml with content type

- db/migrations/core/000081_add_retool_role.up.sql
Adding retool postgres user
Release Notes:
- New Feature: Adds a new PostgreSQL role for the `gallery_retool` user with read-write access to the database.
> "A new role is born,
> With read-write access adorned.
> Database now secure,
> Thanks to this PR."
> Add retool postgres role

- Makefile
This PR adds support for base64-encoded auth and `attempt deadline` flags when deploying cron jobs.
I wasn't sure if there's a more correct way to set optional flags in make recipes. I added a callable function that appends to a variable if a value exists, but if there's something else I should be doing instead, I'm all for it!
Release Notes:
- New Feature: Added support for base64-encoded auth and `attempt deadline` flags when deploying cron jobs.
- New Feature: Introduced a helper function to add optional flags to a command and a callable function that appends to a variable if a value exists.
> "Flags and deadlines, oh my!
> Cron jobs now deploy with ease,
> Thanks to this PR's new features."
> Add optional flags to cloud scheduler deployments

- service/media/media.go
Small bug where if we find an animation object, we break out of the `switch` statement but not the outer `for` loop causing the primary object to get overridden with images and svgs
> Fix finding primary media

- emails/emails.go
- emails/handlers.go
- indexer/core.go
- middleware/middleware.go
- middleware/rate.go
- publicapi/auth.go
- publicapi/publicapi.go
- server/server.go
- service/auth/auth.go
- service/redis/redis.go
- tokenprocessing/tokenprocessing.go
- Our redis `Cache` abstraction now allows namespacing within a redis database via key prefix
- We always use `Caches` instead of `Clients` to make sure that namespacing is consistent and enforced
- Existing uses of `redis.Client` have been updated to use the `Cache` type instead
- These include distributed locks via `redislock` and rate limiters
- Fixed a bug where the email service `/verification` and `/preverify` handlers were sharing the same rate limiters
- Refactored rate limiters to make it easier to understand how they work
- OneTimeLogin (e.g. QR code login) now uses redis to consume a token so it can't be used to log in twice
Also of note: I moved our notification locks into a different redis DB and gave them a prefix. We don't necessarily _have_ to do this right now, but it …
> Redis refactor

- db/gen/coredb/models_gen.go
- db/gen/coredb/query.sql.go
- db/migrations/core/000082_add_push_ticket_status.up.sql
- db/queries/core/query.sql
- graphql/generated/generated.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- pushnotifications/expo/handler.go
- server/handler.go
- service/notifications/notifications.go
- Admires, comments, and follows now trigger push notifications (if the user has any devices registered to receive push notifications)
- The `push_notification_tickets` table now has a status column so we know whether a notification was ultimately delivered or not
- The `logout` mutation takes an optional `pushTokenToUnregister` parameter to allow logging out and disabling push notifications in a single mutation
> Send push notifications

- service/persist/token_processing_jobs.go
- tokenprocessing/handler.go
- tokenprocessing/media.go
- tokenprocessing/pipeline.go
- tokenprocessing/process.go
This PR adds performance tracing to the pipeline: [example trace](https://usegallery.sentry.io/performance/tokenprocessing:a5bfc7adf1a74c4cb73fe95f99fb5a8a/?environment=local&project=6771759&query=http.method%3APOST&referrer=performance-transaction-summary&showTransactions=recent&statsPeriod=24h&transaction=POST+%2Fmedia%2Fprocess%2Ftoken&unselectedSeries=p100%28%29)
> Add sentry pipeline tracing

- db/migrations/core/000083_add_tablefunc_ext.up.sql
Adding the [tablefunc](https://www.postgresql.org/docs/current/tablefunc.html) extension to our db to use some funcs helpful in the dashboard and perhaps other things
> Add tablefunc ext

- middleware/middleware.go
Add support for the new platform headers. Tested this locally and all runs smoothly.
> allow new platform headers to come through

- service/metric/metric.go
- tokenprocessing/pipeline.go
- tokenprocessing/tokenprocessing.go
* Adds `metric` package. The metrics reporter used should be easy to switch out if/when we want to record metrics in some other way like custom metrics
* Adds log-based metrics to the pipeline, to start it will track:
* `pipeline_completed`: pipeline completed
* `pipeline_duration`: how long it took to run the pipeline
* `pipeline_failed`: error in executing the pipeline
* `pipeline_timedout`: pipeline either timed out or was canceled
* Metrics are tagged by media type and chain so that we can plot different time series
> Add metrics to token pipeline

- tokenprocessing/media.go
Changes:
- **Added** objects to the return of any errors for html media types not being cacheable so that the thumbnails can still be used if there are any
> return objects cached anyway

- tokenprocessing/pipeline.go
Think it'd be interesting to see which runs are a result of syncs vs refreshes
> Add cause as a metric pipeline tag

- emails/handlers.go
- middleware/middleware.go
- service/limiters/rate.go
- service/notifications/notifications.go
- service/redis/redis.go
This PR uses our existing Redis-based rate limiters to limit the number of push notifications a user can receive. The current limits are:
1 admire per `sender:receiver:feedEvent` every 10 minutes
1 follow per `sender:receiver` every 10 minutes
5 comments per `sender:receiver:feedEvent` every minute
In practical terms, this means you'll get notifications every time someone admires one of your feed events, but you won't get a notification if they un-admire and re-admire the same event (unless 10 minutes has passed since the last time they admired it). Same with follows: you won't get spammed by someone unfollowing and reflowing you, though you could get notified once every 10 minutes.
Comments are more spammable: the limit is 5 per feed event every minute, and in practice, I find it …
> Rate limit push notifications

- service/media/media.go
Fixes the error: https://console.cloud.google.com/errors/detail/CJqn4_GK1YrjTQ;service=tokenprocessing-v3;version=tokenprocessing-v3-b0ab09d6b7;time=P1D?project=gallery-prod-325303
It's unlikely, but occasionally does occur where the mimeType isn't of the format `type/subtype`, this change checks the length before indexing.
> Handle tokenprocessing index error

- service/auth/auth.go
TODO: Come up with a scheme to distinguish user-facing error messages from developer-friendly error messages.
> [GAL-3100] Better copy for user-facing magic link error

- service/multichain/multichain.go
- service/persist/token_processing_jobs.go
- service/task/cloudtask.go
- tokenprocessing/media.go
- tokenprocessing/process.go
Changes:
- **Added** opensea token processing fallback step to more top level failure points in the caching of objects
> use opensea at further up errors as well

- cmd/reprocess/main.go
- cmd/reprocess/orchestrator/main.go
- tokenprocessing/pipeline.go
Changes:
- **Changed** persist token processing step to use its own context just in case the rest of the job failed with a timeout
> new context just for persist

- service/multichain/multichain.go
- service/task/cloudtask.go
- tokenprocessing/pipeline.go
- tokenprocessing/process.go
Changes:
- **Added** chains to throttle lock on token processor
This was previously not causing any obvious issues in v2 because tokens would just end up not getting reprocessed, it is a lot more obvious in v3 when a new token would not receive a token media ID.
What would happen is a user would sync tokens of one chain, then do another right after, and because we throttled on user ID, all of the second chain's tokens would get throttled and not get processed by the token processor.
> use chains in lock

- tokenprocessing/media.go
- tokenprocessing/pipeline.go
Refreshing a token that is not cacheable would show an error to the user, even though the refresh worked.
> Fix error that is shown when refreshing a token that is not cacheable

- service/rpc/rpc.go
Changes:
- **Changed** get token URI to replace the `{id}` with the token ID per the ERC-1155 spec
> replace {id}

- tokenprocessing/media.go
Changes:
- **Changed** priorities for determining which cached objects to use in the media
> prioritize specific token fields before manual thumbnail

- .github/workflows/deployer.yml
- Makefile
- graphql/resolver/schema.resolvers.go
- graphql/stub_test.go
- publicapi/token.go
- secrets/dev/backend-env.yaml
- secrets/dev/local/app-dev-backend.yaml
- secrets/prod/backend-env.yaml
- server/server.go
- service/multichain/alchemy/alchemy.go
- service/multichain/eth/eth.go
- service/multichain/fallback.go
- service/multichain/infura/infura.go
- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
- service/task/cloudtask.go
- tokenprocessing/pipeline.go
- tokenprocessing/process.go
**Changes**
* Removes sending messages to v2 tokenprocessing
* Moves v3 deployment from `make deploy-prod-tokenprocessingV3` to just `make deploy-prod-tokenprocessing`
* Removes owner as a dependency for refreshing tokens
* Improves multichain validation so the error is more human readable
> Turn off V2 tokenprocessing

- server/server.go
- service/multichain/multichain.go
**Changes**
* Fixes checks for filling out token descriptors
* The order of providers passed to multichain matter: the fallback eth provider was first meaning that its results are prioritized. The fallback provider was returning an inaccurate token name, and wasn't being replaced with later providers data
In the future, we can make the priority of providers more explicit
> Fix token name

- service/multichain/multichain.go
- tokenprocessing/media.go
- util/response.go
**Changes**
* Add new error for when storing objects to GCP fails
* Lowers the log levels for a few more log lines from error to warn
* Adds Unwrap method to custom errors that have reference to the original error
* Less logging when getting failed readers
> Add storage error

- cmd/reprocess/main.go
- graphql/fixture_test.go
- graphql/graphql_test.go
- server/inject.go
- server/server.go
- server/wire_gen.go
- tokenprocessing/tokenprocessing.go
tokenprocessing was failing to start because it was using the backend's `SetDefault` func which requires `IMGIX_SECRET` to be set which tokenprocessing doesn't use. Fixed by adding an arg to the multichain func to provide which environment setting function to use.
> Add setEnv param to multichain init

- cmd/reprocess/main.go
- service/metric/metric.go
- service/multichain/multichain.go
- tokenprocessing/media.go
- tokenprocessing/pipeline.go
**Changes**
* Adds better error message for when failing to get dimensions
* Pipeline now logs an error when reporting an error metric
* Removes `mediaURL` arg for caching from OpenSea since its not used
> More random pipeline improvements

- graphql/graphql_test.go
- publicapi/user.go
Always return connected social accounts as we'll no longer allow users to toggle this off
> Always resolve connected social info despite preference setting

- db/gen/coredb/token_gallery.sql.go
- db/queries/core/token_gallery.sql
- service/persist/postgres/token_gallery.go
This PR removes upserting `is_user_marked_spam` for the token bulk upsert step. Ideally the caller could still update `is_user_marked_spam`, but handling null types would require a change to the sqlc config to set `emit_pointers_for_null_types: true` which requires a larger refactor. For now I'm just removing the param so that the field is always initially set to null.
> Remove user marked spam from bulk insert

- db/gen/coredb/batch.go
- db/queries/core/query.sql
We accidentally omitted this constraint when changing GetOwnersByContractIdBatchPaginate. It's back now!
> Add owner constraint back to GetOwnersByContractIdBatchPaginate

- service/multichain/multichain.go
- service/persist/postgres/contract_gallery.go
- tokenprocessing/media.go
- tokenprocessing/pipeline.go
- tokenprocessing/process.go
- util/helpers.go
- util/response.go
* Fixes pipeline bug where the fetched metadata is not used in downloading the media
* Cleans up some error handling
* Returns `404` instead of `500` from tokenprocessing if a token or contract is missing
* Adds `util.ErrorAs` helper function
> Fix metadata pipeline bug

- server/inject.go
- server/wire_gen.go
- service/multichain/multichain.go
Changes:
- **Added** `WalletOverrides` which is a mapping of chain to many other chains that will be used to allow wallets to be reused across chains they are shared (EVM chains all share same wallet address)
- **Removed** current `ChainOverrides`, it was being used in two places, one in place of the where the new wallet overrides is and another in a place that did not functionally do anything. When syncing contracts it would check whether the contract addresses had overrides, looked like this:
```
// let's say Arbitrum and ETH are chains here
for _, chain := range chains {
// if chain was Arbitrum this would return ETH
// no override for ETH though
override := p.ChainAddressOverrides[chain]
for _, contract := range contracts {
// because the override is ETH for arbitrum, the ETH …
```
> just wallet overrides

- db/gen/coredb/contract_gallery.sql.go
- db/queries/core/contract_gallery.sql
- service/multichain/multichain.go
- service/persist/contract_gallery.go
- service/persist/postgres/contract_gallery.go
This PR changes our contract upsert methods to preserve existing `owner_address` fields by default, with an optional `canOverwriteOwnerAddress` parameter that allows the upsert to modify a non-empty `owner_address`.
**Old behavior**: every contract upsert would overwrite `owner_address` with a new value
**New behavior**: every contract upsert will overwrite `owner_address` if the existing value is null or empty. Otherwise, the existing value will only be overwritten if the new value is not null/empty _and_ the `canOverwriteOwnerAddress` flag is specified.
The practical implications of this change: syncing/refreshing tokens will update contracts, but won't change an existing contract's owner address unless the existing contract has an empty owner address. Syncing creator tokens, however, …
> Don't overwrite existing contract owner addresses by default

- adminapi/admin.go
- cmd/contract_owners/main.go
- graphql/dataloader/dataloaders.go
- publicapi/collection.go
- publicapi/contract.go
- publicapi/feed.go
- publicapi/gallery.go
- publicapi/interaction.go
- publicapi/merch.go
- publicapi/notifications.go
- publicapi/pagination.go
- publicapi/search.go
- publicapi/socials.go
- publicapi/token.go
- publicapi/user.go
- publicapi/wallet.go
- validate/validate.go
My editor allows me to jump to the next error in a file, but it would jump to these lines because of the warning: "composite literal uses unkeyed fields". I could've updated my config, but I thought I'd just update it in the codebase.
This also lets us run `go vet ./...` with no more errors!
> Chore: Fix "composite literal uses unkeyed fields"

- service/multichain/zora/zora.go
Changes:
- **Changed** token mapping in zora provider to use known wallet if there is one and the wallet returned for a token is null or empty
> use known wallet if exists

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
We were missing a condition in the `CountOwnersByContractId` query, causing community load times to be significantly longer than necessary (and returning an inaccurate count, too!).
Adding the appropriate constraint takes query time from ~5 seconds to ~50ms.
> Add missing condition to CountOwnersByContractId where clause

- server/inject.go
- server/wire_gen.go
- service/multichain/alchemy/alchemy.go
- service/multichain/opensea/opensea.go
- service/persist/token.go
Changes:
- **Added** `opensea.Provider` to Polygon, Optimism, and Arbitrum chains
- **Added** chain parameters to the opensea provider
- **Removed** unused persist code that was sort of being used uselessly by the opensea provider
- **Removed** alchemy fallback media because it is not correct fallback format and would override what is correctly being returned by opensea. Given that ETH doesn't use it, neither should the other chains
> opensea fallback supports multiple chains

- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
Changes:
- **Added** a check for empty address display names when creating universal users, these will collide with each other causing some users not to get added and tokens to then be left without an owner.
> don't use empty address display names

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- publicapi/feed.go
- publicapi/pagination.go
- secrets/dev/local/app-dev-backend.yaml
- service/persist/feed.go
- service/redis/redis.go
- sqlc.yaml
**Changes**
This PR makes a change to the feed cursor to also encode the type of the feed entity alongside the DBID. This means we can skip the query that finds what type the entity is, which should save a few hundred milliseconds. 
The cursor is now encoded as:
```
<current position of cursor><length of ids><dbid type><dbid><dbid type><dbid>....
```
Going to test on dev a bit more to make sure it actually is faster, before deploying on prod.
> Trending feed optimization by encoding entity type in cursor

- publicapi/token.go
- service/rpc/rpc.go
Changes:
- **Added** a check for `data:` before looking for where the data starts for an SVG so that we don't accidentally start parsing an SVG at some further index because it "looks" like the start of the data (follows a comma)
> check prefix for data before indexing comma

- secrets/dev/local/app-dev-tokenprocessing.yaml
- secrets/dev/tokenprocessing-env.yaml
- secrets/prod/local/app-prod-tokenprocessing.yaml
- secrets/prod/tokenprocessing-env.yaml
- service/pubsub/gcp/pubsub.go
Adds the google cloud project to prod secrets and panics if project id isn't set in client init.
> Add gcp project to prod

- publicapi/user.go
Changes:
- **Removed** error check for assigning socials so new socials cannot error out the whole resolver
> do not error when social provider does not exist

- graphql/graphql_test.go
- secrets/dev/backend-env.yaml
- secrets/dev/backend-sandbox-env.yaml
- secrets/dev/local/app-dev-backend.yaml
- secrets/local/local/app-local-backend.yaml
- secrets/prod/backend-env.yaml
- server/server.go
- service/recommend/userpref/personalize.go
- service/redis/redis.go
- service/store/cloudstorage.go
This PR changes the algorithm's database from Redis to Cloud Storage instead. I also added a new package, `store`, and a wrapper around the cloud storage client, `BucketStorer`, to make reading and writing to Cloud Storage easier. At some point, I'll refactor tokenprocessing to use the package since they share much of the same logic.
I also tried to address the flaky test, it should run more reliably 🤞
> Save matrices to cloud storage

- go.mod
- graphql/generated/generated.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
Changes:
- **Added** a separate resolver for resolving spam set by providers for tokens that utilizes the contract's spam field as well as the token's spam field
> resolve spam separately

- pushnotifications/expo/expo.go
- pushnotifications/expo/handler.go
An unmarshaling error has stopped us from seeing some push notification errors. This PR fixes that issue (changes a struct field from `map[string]string` to `map[string]any` and adds some additional logging. It also fixes an issue where errors weren't being propagated through push notification batches.
I don't think this will fix the reliability issues we've been seeing with push notifications, but hopefully it'll let us see actual errors explaining what's wrong.
> Push notification error handling

- db/gen/coredb/models_gen.go
- db/gen/coredb/recommend.sql.go
- db/migrations/core/000101_add_feed_entity_scores.up.sql
- db/migrations/core/000102_add_posts_created_at_idx.up.sql
- db/queries/core/recommend.sql
- publicapi/feed.go
- service/recommend/userpref/personalize.go
- service/store/cloudstorage.go
This PR adds a materialized view, `feed_entity_scores`, containing the last week of feed entities plus data needed for the koala algo. It's refreshed half-hourly with the help of a regular view `feed_entity_score_view`. When a request is made for a user's feed, the query unions both views to get the cached feed entities plus the most recent entities that haven't been cached yet.
> Curated caching

- db/gen/coredb/recommend.sql.go
- db/queries/core/recommend.sql
- publicapi/feed.go
- service/recommend/userpref/personalize.go
Fixes:
* Correctly excludes specific actions from curated query
* Removes saturation penalty of interactions
* Removes indexing of relevance score
* Adds `+1` to engagement and personalization factors so zero-valued scores don't completely penalize the total score
> Curated fixes

- service/multichain/alchemy/alchemy.go
- service/multichain/eth/eth.go
- service/multichain/fallback.go
- service/multichain/infura/infura.go
- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
- service/multichain/poap/poap.go
- service/multichain/reservoir/reservoir.go
- service/multichain/tezos/objkt.go
- service/multichain/tezos/tezos.go
- service/multichain/zora/zora.go
Changes:
- **Added** `ProviderID` to `BlockchainInfo` so that each provider can get a unique hard coded ID we can dedupe on.
- **Changed** `providersMatchingInterface` to perform the two checks listed below
1. Check if we have already seen a provider with the given provider ID
2. If a provider is a `ProviderSupplier` and matches the interface we are checking, add that provider's sub provider IDs to the duplicate checking map so that we don't add the individual sub providers later
> seen provider

- publicapi/feed.go
- service/recommend/userpref/personalize.go
Changes:
* Reduce half life of interactions from 24 hours to 12 hours
* Adjust scoring of interactions to use `sqrt` instead of `ln` so that large numbers are penalized more
> Adjust curated feed scoring

- publicapi/feed.go
- service/recommend/recommend.go
Changes:
* Personalization scores may now be boosted and also are subject to time decay
* Events are now shuffled within partitions
> Add decay to personalization scores

- cmd/refresh/refresh.go
- server/inject.go
- server/wire_gen.go
- service/multichain/alchemy/alchemy.go
- service/redis/redis.go
Changes:
- **Added** metadata fetcher to alchemy provider but only works for l2s. Added caching so that metadata can be shared from the initial sync call to the fetching of metadata by the token processing service
> l2 providers gaina ccess to metadata

- .github/workflows/tests.yml
- publicapi/feed.go
- publicapi/pagination.go
- publicapi/pagination_test.go
Changes:
* This PR adds the pagination helper, `pageFrom`, and other helper functions to determine the set of edges to return for a page and the pageInfo for that page
* The keyset paginator now uses `pageFrom` to get the final set of edges and pageInfo instead
* The feed paginator now uses `pageFrom` instead of the keyset paginator
* Simplifies logic in getting the curated and trending feed
* Adds test related to pagination
> Refactor pagination

- db/gen/coredb/recommend.sql.go
- db/queries/core/recommend.sql
- publicapi/feed.go
Excludes events from the curated feed if posts are enabled for the user, but will still display events if posts are not enabled. The trending feed will continue to show events, @kaitoo1 should we start excluding events from the trending feed too? We revert to the trending feed if the user isn't logged in.
> [GAL-4030] Exclude events for curated feed

- service/multichain/multichain.go
Changes:
- **Added** a blacklist of contract names so that we don't get `Unidentified Contract` as the name
- **Added** a fetch after refresh to ensure the contract refresh doesn't just do nothing as far as the gallery db is concerned
> fetch on refresh, don't use unidentified contract names

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- service/notifications/notifications.go
Changes:
- **Added** new push notifications for `ActionNewTokensReceived`, `ActionCommentedOnPost`, and `ActionAdmiredPost`
> optimsitic and new comment/admire push notifications

- graphql/resolver/schema.resolvers.helpers.go
- publicapi/contract.go
Post captions were showing up null on the community page (as reported by @kaitoo1). This fixes the issue! And updates a couple of copy/pasted variable names.
> Fix for null post captions

- db/gen/coredb/batch.go
- db/gen/coredb/gallery.sql.go
- db/queries/core/query.sql
- graphql/dataloader/dataloaders.go
- graphql/resolver/schema.resolvers.go
- publicapi/user.go
- secrets/dev/local/app-dev-backend.yaml
- secrets/local/local/app-local-backend.yaml
- service/multichain/zora/zora.go
- service/rpc/ipfs/ipfs.go
**Changes**
* Media resolver now differentiates between missing media and broken media
* Media resolver now defines a grace period for how long a token can't have media before assuming that media is invalid
* Media resolver now rewrites fallback IPFS and Arweave URLs to HTTP so that browsers can render them
* Media resolver now returns fallback media even when fetching media fails instead of returning no fallback
> Handle token loading

- service/multichain/reservoir/reservoir.go
Fixes runtime error caused by assignment to a nil map by creating a copy of the map. Tested by refreshing a base coin before and after the change.
> Make copy of metadata map

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/model/remapgen_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- publicapi/auth.go
- publicapi/user.go
- validate/validate.go
This PR adds the `optInForRoles` and `optOutForRoles` mutations, which allow users to add and remove roles from themselves (but only for a set of defined "opt-in" roles -- currently limited to just the `BETA_TESTER` role).
I copied/pasted from the admin role management stuff a bit more than I'd have liked, but I think we can refactor into role helper methods at some point in the future.
> Allow opt-in roles

- graphql/graphql_test.go
- graphql/stub_test.go
- server/inject.go
- server/wire_gen.go
- service/multichain/multichain.go
- service/task/cloudtask.go
- service/tokenmanage/tokenmanage.go
Removes `chain` from the tokenprocessing messages. We used to require this to figure out which keywords to collect media from depending on the chain, but it isn't needed anymore.
> Chore: Remove chain from tokenprocessing message

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- publicapi/contract.go
This PR adds the `tmpPostsWithProjectID` field to our GraphQL community type, allowing the Prohibition community's posts to be filtered by Project Id, too. This is a one-off that can/should be removed in the future, hence the "tmp" in the name and comments about code being temporary!
> Add temporary functionality to filter posts by Prohibition project ID

- service/persist/token.go
This PR updates the base metadata keywords to include `imageOriginal` and `mediaOriginal`. The former is the second most used key for Base metadata, and the latter is used sparingly but is used in the collection with Duane King's broken token. I'm not sure if these are specific to the Reservoir provider or for Base because we only use Reservoir for Base, but I made them Base specific for now.
> Update base keywords

- publicapi/pagination.go
Fixes EOF panic when an empty cursor string is passed
> Handle empty cursor

- secrets/dev/local/app-dev-tokenprocessing.yaml
- secrets/dev/tokenprocessing-env.yaml
- secrets/prod/tokenprocessing-env.yaml
Fixes a bug where push notifications weren't sent from tokenprocessing because of a few missing env vars.
> Add push service vars to tokenprocessing

- service/recommend/userpref/personalize.go
- service/store/cloudstorage.go
Fixes issue where the backend fails to start because it can't read the data needed for the For You Feed because access isn't granted to the file yet.
> Retry reading user matrices on 401

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- event/event.go
- feed/server.go
- graphql/generated/generated.go
- graphql/graphql_test.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/feed.go
- publicapi/user.go
- secrets/dev/feedbot-env.yaml
- service/eth/eth.go
- service/task/cloudtask.go
**Changes**
* Posts and feed events are always shown on Global Feed
* Posts and feed events are always shown on Following Feed
* Posts are now only shown on Activity Feed
* Adds `deprecated` directive to `includePosts` param wherever it appears
* Maps ENS PFP errors to GraphQL error type to reduce noise in Sentry
* Removes `authRequired` directive from `sharedCommunities` and `sharedFollowers` fields on `GalleryUser` - now returns no results if the user isn't authenticated, to reduce noise in Sentry
* Dev posts are no longer posted to Slack
* Changes `withScheduleOn` option to `withDelay` in `cloudtask.go`
> Various fix it week fixes

- db/gen/coredb/recommend.sql.go
- db/queries/core/recommend.sql
- graphql/resolver/schema.resolvers.go
- publicapi/feed.go
- service/recommend/userpref/personalize.go
**Changes**
* Viewer is now included in the For You Feed
* Viewer posts are only ranked using the post's engagement instead of the post's engagement and relevance to the user
* Normalizes personalization scores to 1.0
* Reduces the shuffle window size from 8 to 4
> Include viewer in feed

- graphql/resolver/schema.resolvers.helpers.go
I realized that the sanitization policy we use internally uses the go HTML standard lib package to escape strings: 
https://github.com/microcosm-cc/bluemonday/blob/main/sanitize.go#L443
https://cs.opensource.google/go/x/net/+/refs/tags/v0.15.0:html/escape.go;l=279
The API doesn't expose a way to change this so I decided to unescape the strings at the resolver level for fields that get sanitized.
> Unescape html strings

- server/inject.go
- server/wire_gen.go
- service/multichain/eth/eth.go
- service/multichain/multichain.go
- service/multichain/poap/poap.go
- service/multichain/tezos/objkt.go
- service/multichain/tezos/tezos.go
- tokenprocessing/pipeline.go
**Changes**
* Replaces Opensea as a provider with Reservoir for Polygon
* Refactors `inject.go`:
* Providers now share the same client instance of the token metadata cache instead of keeping separate clients
* Removes throwaway inject functions
* Cleans up each chain's provider sets so it's easier to see which providers are used per chain
* Moves provider de-duplication logic to multichain initialization
* Minor refactor in `pipeline.go` to remove the need of a channel when processing media
> Add reservoir to polygon

- publicapi/feed.go
- publicapi/interaction.go
Put `CommentID` where `ContractID` was expected.
> mention typo

- service/persist/postgres/user.go
User was failing to sync because one of their wallets was deleted, changed to not return on a missing wallet.
> Don't return on missing wallet

- graphql/resolver/schema.resolvers.helpers.go
There is a small bug in the pipeline where ENS profile images that are SVGs are saved as a thumbnail object instead of a PFP object. The bug also results in thumbnails of ENS tokens with SVG pfps to show the profile image as the thumbnail instead of the typical ENS i.e. "vitalik.eth" thumbnail.
The workaround is to serve the SVG from its data URL instead of a rasterized image that we would've saved from the pipeline.
> ENS pfp svg workaround

- db/gen/coredb/batch.go
- db/gen/coredb/contract_gallery.sql.go
- db/gen/coredb/models_gen.go
- db/gen/coredb/query.sql.go
- db/gen/coredb/search.sql.go
- db/migrations/core/000112_contract_l1.up.sql
- db/queries/core/contract_gallery.sql
- db/queries/core/query.sql
- service/multichain/multichain.go
- service/persist/contract_gallery.go
- service/persist/postgres/contract_gallery.go
- service/recommend/userpref/personalize.go
Changes:
- **Added** `L1Chain` to the contracts table
- **Changed** `contract_creators` view to use the `L1Chain` of the `wallets` and `contracts` table
TODO:
> Contract L1 Chain

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- event/event.go
- publicapi/feed.go
- service/notifications/notifications.go
- service/persist/event.go
- service/persist/notification.go
Changes:
- **Added** a new notification for when someone posts tokens from a contract that a user owns
- **Changed** post handlers to attempt to find a contract creator user and dispatch events accordingly
> someone posted your work notification

- graphql/generated/generated.go
- graphql/model/gqlidgen_gen.go
- graphql/model/models.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- service/multichain/multichain.go
- service/multichain/zora/zora.go
- service/persist/wallet.go
Changes:
- **Added** new notification type for the posted your work notification
- **Changed** zora token ID parsing to always split on `-` and use the number following the `-`
- **Changed** `is_creator_token` determination to use L1 chain
> zora prefixed token ID, notif type, creator token l1 lookup

- cmd/dataloaders/generator/template.go
- graphql/dataloader/dataloaders_gen.go
Generated dataloader code was doing this:
```
dataloader := generator.NewDataloader(ctx, maxBatchSize, batchTimeout, cacheResults, publishResults, fetchWithHooks)
d.Dataloader = *dataloader
```
That counts as copying a mutex (because there's a mutex in the underlying sync.Map), though AFAIK it's okay to copy a zero-value mutex prior to locking it. All the same, `go vet` flags this as a problem, so now the generated code does this instead:
```
d.Dataloader = *generator.NewDataloader(ctx, maxBatchSize, batchTimeout, cacheResults, publishResults, fetchWithHooks)
```
and that makes `go vet` happy.
> Make go vet happy

- service/notifications/notifications.go
Changes:
- **Changed** admire notification text generation to only use a collection for feed event admires because posts are not related to adding to collections
> only get collection for feed events

- service/notifications/notifications.go
Changes:
- **Removed** error check for comment notification text generation for feed events given they might not exist for a post event
> no error out for comment feed event

- service/multichain/multichain.go
- service/multichain/zora/zora.go
Changes:
- **Changed** wallet search in multichain to use the correct chain L1Group so that addresses like tezos addresses aren't used for providers they should not be used for
> fix wallet override group check

- graphql/dataloader/notfound.go
- graphql/resolver/schema.resolvers.go
- service/persist/token_gallery.go
I fixed a previous error re: contract creators, but forgot to update `notfound.go` with an appropriate alternative to `pgx.ErrNoRows`. This PR returns the correct error, and uses that error to return `nil` to the frontend if a contract creator isn't found (instead of throwing an unsupported error type).
We could return the `ErrContractCreatorNotFound` directly to the frontend, but historically haven't done that for backwards compatibility reasons, and I don't think it's worth doing at this point!
> Re-add missing contract creators error

- rasterizer/index.js
- secrets/dev/local/app-dev-backend.yaml
- service/multichain/multichain.go
- service/multichain/zora/zora.go
Changes:
- **Added** a log to check for fallback 200's
- **Added** a fixed dimension to the SVG rasterizer to ensure that large SVGs are scaled down and we take more uniformly sized PNG thumbnails (svgs with 3000x3000 for example were timing out because the PNG was too big, given that SVGs are scalable we might as well scale it down)
- **Changed** SVG dimension searching to check in a few more spots
> better rasterizing and log fallback failures

- db/gen/coredb/batch.go
- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
A few queries are failing because they reference the wrong column names. This PR fixes those queries, though it _doesn't_ fix `GetSVGTokensWithContractsByIDs`, which is only used by the `cmd/reprocess` executable. If/when we run that in the future, we should update that statement to reference token definitions appropriately!
> Fix sql column references

- service/notifications/notifications.go
Noticed when I mentioned Figure31 that this sentry error popped up: https://usegallery.sentry.io/issues/4612178636/?referrer=slack&notification_uuid=68366714-4e34-4a68-80df-c9d14a7e1041&alert_rule_id=13000544&alert_type=issue
The notification was sent, but it fell through and hit the error because it was missing a `return`.
> Add return to ActionUserPostedYourWork

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- event/event.go
- graphql/generated/generated.go
- graphql/model/gqlidgen_gen.go
- graphql/model/models.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/feed.go
- service/notifications/notifications.go
- service/persist/event.go
Changes:
- **Added** a new action `UserPostedFirstPost`
- **Added** a new type of event notification handler for "follower" events that don't have a single owner and are going to be associated with the followers of the event actor
- **Added** a new type of notification handler for "follower" notifications that will fan out notifications to the followers of the determined actor based on the notification type (e.g. a user posted first notification will fan out to the followers of the poster user)
- **Added** new GQL type `SomeoneYouFollowPostedTheirFirstPostNotification` to the schema
How it works:
1. A user posts, we check if this is their first post (posts.count == 1). If it is, we send a single event saying this user posted their first work
2. A new event handler picks up that event and …
> notification handling for posting first post [GAL-4716]

- db/gen/coredb/batch.go
- db/queries/core/query.sql
Fixes gallery token preview. 
Before:
After:
> Fix gallery token previews

- service/persist/token_processing_jobs.go
- tokenprocessing/handler.go
- tokenprocessing/media.go
- tokenprocessing/pipeline.go
- tokenprocessing/process.go
* Added a new job option `requireImage` which requires an image to be processed if an image keyword is in the metadata. `requireImage` is enabled for jobs started by the `processPostPreflight` endpoint to help ensure that preview images are available for posts.
* Refactored how the Opensea fallback is used. Before, when processing an animation, if the pipeline failed to download content from the animation URL, OS was used to download any asset type (even a non-animation asset). The same was true for images. Now, we try to fetch specific assets from OS. The fallback is now only used at the top-level of the pipeline and only if the pipeline requirements aren't met yet (e.g. if the job has `requireImage` enabled and an image wasn't cached yet)
* Non `2xx` HTTP codes are now categorized as …
> Tokenprocessing pipeline updates

- graphql/resolver/schema.resolvers.helpers.go
This fixes the broken image that is briefly shown for fallback media using IPFS. Turns out IPFS CIDs are case-sensitive and shouldn't be lower-cased.
| Before | After |
| --- | ----------- |
| <img width="680" alt="Screen Shot 2023-11-13 at 2 42 54 PM" src="https://github.com/gallery-so/go-gallery/assets/20363846/60868bf0-8fb1-4d92-92ad-672d7a6021ff"> |  <img width="680" alt="Screen Shot 2023-11-13 at 2 44 45 PM" src="https://github.com/gallery-so/go-gallery/assets/20363846/4bcddefd-4a25-4b91-a3aa-9cb2bcae02d0"> |
> Fix IPFS fallback previews

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- service/notifications/notifications.go
Changes:
1. **Changed** insert of user posted first notification to take in an array of IDs generated up front
> generate many ids for user post first post

- db/gen/coredb/admire.sql.go
- db/gen/coredb/query.sql.go
- db/queries/core/admire.sql
- db/queries/core/query.sql
- event/event.go
- service/notifications/notifications.go
- service/persist/postgres/admire.go
- service/persist/postgres/event.go
- service/sentry/sentry.go
Was able to get `SomeoneAdmiredYourTokenNotification` working! Tested with the query:
```graphql
query {
viewer {
...on Error {
message
__typename
}
...on Viewer {
notifications(last:4) {
edges {
node {
id
__typename
creationTime
...on SomeoneAdmiredYourTokenNotification {
id
dbid
token {
dbid
name
tokenId
description
media {
__typename
...on Media {
mediaURL
mediaType
}
}
}
admirers(first: 4) {
edges {
node {
username
}
}
}
}
}
}
}
}
}
}
```
The frontend doesn't support displaying this notification type yet, but should be ready to integrate now.
> Fix token admire notifications

- tokenprocessing/pipeline.go
- util/helpers.go
Fixes
* Don't save metadata if the job errored fetching new metadata
* Don't fail on `bufio.ErrBufferFull` if file size is less than 512 bytes
> Pipeline bug fixes

- tokenprocessing/pipeline.go
This was causing false alarms in alerting because an error wasn't categorized correctly.
> Correctly categorize bad token errors

- server/server.go
- service/persist/postgres/postgres.go
- util/retry/retry.go
After adding retries for Postgres clients created by the main backend server, I saw tests continuing to fail (without retries!) for clients created by other services (e.g. `pushnotifications`). In general, it seems to me that we want to retry connections before giving up, so this PR makes it the default behavior whenever we create a Postgres client, and adds a `WithNoRetries` option to disable the behavior.
> Use retries by default for all Postgres clients

- db/gen/coredb/batch.go
- db/gen/coredb/models_gen.go
- db/gen/coredb/query.sql.go
- db/migrations/core/000125_reply_ancestors.up.sql
- db/migrations/core/000125_top_level_comment.up.sql
- db/queries/core/query.sql
- publicapi/interaction.go
- service/persist/postgres/comment.go
- service/persist/postgres/postgres.go
- service/recommend/userpref/personalize.go
Changes:
- **Added** a new column to the `comments` table called `reply_ancestors` that is an array of all of the reply ancestors (including the most recently replied to comment in `reply_to`) so that when we ask for the replies to a comment we can return any comment where the ancestors contains this comment we are querying for. 
I experimented with a few paths before arriving here:
- My first instinct was to just have the get replies query traverse the reply tree until it reaches the comment we are querying for. SQLC hated this approach and no matter how much experimentation I did with the query and chatGPT and copilot I could not get a recursive reply pagination query to work so I went looking for other answers.
- My second instinct was to just have a new column that stores the "top …
> show nested comments as a flat list

- service/notifications/notifications.go
- service/rpc/ipfs/ipfs.go
Fixes issue:
Also does some unrelated cleanup in the IPFS module by removing unused interfaces.
> HTML unescape push notification comments

- graphql/resolver/schema.resolvers.helpers.go
- service/rpc/ipfs/ipfs.go
**Changes**
* Sets default gateway from `gallery.infura-ipfs.io` to `ipfs.io`
* Adds additional IPFS gateways to query from ipfs.io, Pinata, CloudFlare and nftstorage.link and removes Infura
> Remove infura gateway

- secrets/dev/local/app-dev-backend.yaml
- service/rpc/ipfs/ipfs.go
Turns out we were stripping query params from the IPFS query URL! Renamed an arg to reflect what it does.
> Fxhash IPFS fix

- graphql/resolver/schema.resolvers.helpers.go
- secrets/dev/local/app-dev-backend.yaml
- service/rpc/ipfs/ipfs.go
- tokenprocessing/media.go
Fxhash has a gateway that caches their content locally, so we can use that to retrieve fxhash-specific assets faster.
> Add fxhash specific gateway

- emails/emails.go
- emails/send.go
Changes:
- **Changed** email send logic to not wait for lock, instead instantly ack the message
- **Changed** error handling for email send to not `Nack()` on failure, still `Ack()`. Better to log error and know for next week that some emails may not have gone out then try to resend all of them on a redelivery.
This will help to ensure no-reduplicates, and will also ensure that on any failures, we do not attempt to retry sending messages.
> don't wait for lock, just end

- db/gen/coredb/batch.go
- db/gen/coredb/models_gen.go
- db/gen/coredb/query.sql.go
- db/gen/coredb/recommend.sql.go
- db/migrations/core/000131_add_post_mint_url.up.sql
- db/queries/core/query.sql
- graphql/generated/generated.go
- graphql/generated_test.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/feed.go
- secrets/dev/local/app-dev-backend.yaml
- util/helpers.go
Schema changes:
Adds `userAddedMintURL` to the `Post` type and `mintURL` as an input to the post creation mutations. Note: the backend only checks if the URL is valid, it doesn't check if the URL is from an allow-listed domain. cc @Robinnnnn 
```graphql
type Post {
...
userAddedMintURL: String
}
input ReferralPostTokenInput {
token: ChainAddressTokenInput!
caption: String
mintURL: String  # new field
}
input PostTokensInput {
tokenIds: [DBID!]
caption: String
mentions: [MentionInput!]
mintURL: String. # new field
}
type Contract {
mintURL: String  # should be used if `post.userAddedMintURL` does not exist
}
```
> Add mint link to posts

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- publicapi/interaction.go
Changes:
- **Added** `totalComments` to the `Post` and `FeedEvent` types. This represents total comments and their replies count, different than what the `comments.pageTotal.total` would return (that is just top level comments).
I considered adding it to the `CommentsConnection` type but it just didn't end up feeling right that a type that was meant to represent a page in pagination would uniquely have this extraneous field that didn't have to do with pagination. It also would require the frontend to dig into at least 1 comment which is fair but seems safer to have the field just exist on the type with the comments and replies
> comment total on feed entities

- graphql/resolver/schema.resolvers.helpers.go
- indexer/metadatas.go
- publicapi/contract.go
- publicapi/token.go
- server/inject.go
- server/server.go
- server/wire_gen.go
- service/membership/membership.go
- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
- service/multichain/tezos/objkt.go
- service/multichain/tezos/tezos.go
- service/rpc/ipfs/ipfs.go
- service/task/task.go
- tokenprocessing/handler.go
- tokenprocessing/pipeline.go
- tokenprocessing/process.go
* Updates OpenSea provider to v2 API
* Deprecates refresh tokens in contract operations - universal users are no longer created
* Removes the `ChildContractFetcher` interface and references to it
* Deletes a bunch of dead code - Fetching membership cards via OS
TODOs
* Deploy tokenprocessing, backend, indexer, and indexer-api after merge
> Move to OS V2

- db/gen/coredb/batch.go
- db/queries/core/query.sql
Changes:
- **Changed** the paginate replies query to use case statements instead of an or statement. I honestly don't know why this fixes pagination, neither jarrel or I could figure it out, but something in my gut told me to switch it to case statements and that it would solve the problem. If it ain't broke don't fix it I guess.
> rewrite paginate replies to use cases... fixes pagination idk why

- graphql/generated/generated.go
- graphql/model/gqlidgen_gen.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
Introduce a new notification type that we can arbitrarily send out to clients (first one will be the holiday NFT collab announcement next week)
```graphql
type GalleryAnnouncementNotification implements Notification & Node {
id: ID!
dbid: DBID!
seen: Boolean
creationTime: Time
updatedTime: Time
platform: Platform!
internalId: String!
imageUrl: String
title: String
description: String
ctaText: String
ctaLink: String
pushNotificationText: String
}
```
> introduce announcement notification type

- db/gen/coredb/batch.go
- db/gen/coredb/models_gen.go
- db/gen/coredb/query.sql.go
- db/migrations/core/000136_owned_communities_view.up.sql
- db/queries/core/query.sql
- graphql/dataloader/api_gen.go
- graphql/dataloader/dataloaders_gen.go
- graphql/resolver/schema.resolvers.go
- publicapi/pagination.go
- publicapi/user.go
This PR creates the `owned_communities` materialized view, which is almost identical to the existing `owned_contracts` materialized view, except that also includes communities.
The "get shared communities" resolver is also updated to use this view instead of the contracts view, so users can see which subcommunities they have in common with others.
> Use actual communities in the sharedCommunities resolver

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
Adds `mintUrl` to the `TokenDefinition` type. This differs from the `Contract` and `Community` mint URLs by providing a token-specific URL when applicable.
```graphql
type TokenDefinition {
mintUrl: String @goField(forceResolver: true)
}
```
> Add mintUrl to TokenDefinitionType

- graphql/graphql_test.go
- graphql/stub_test.go
- service/multichain/alchemy/alchemy.go
- service/multichain/multichain.go
**Changes**
* Change holder syncs to append only instead of replacing holder tokens for now
* Fix race condition in `receiveSyncedTokensForUser` where the error returned from a provider may not get checked
* Minor changes to the Alchemy provider: fix bug where the error from marshalling wasn't returned and also remove extra print statement
* Remove `logFallbackFailure` - this could create an uncapped number of goroutines, so I removed it for now
* Add a test that checks that tokens aren't deleted from a failing provider
* Remove multiErr from syncs and instead returns the latest error so that it can get wrapped properly to the correct graphQL error type
> Change holder syncs to append only

- publicapi/publicapi.go
- server/handler.go
- server/inject.go
- server/server.go
- server/wire_gen.go
- service/multichain/multichain.go
- service/tokenmanage/tokenmanage.go
- tokenprocessing/handler.go
- tokenprocessing/tokenprocessing.go
**Changes**
* Fixes how contracts and tokens are received for creator syncs
* Fixes bug where a new tokenmanage redis cache was created per request, now the cache is initialized once and shared
* Fixes bug where the OpenSea provider wasn't used for Ethereum!
* Renamed `errWithPriority` to `errWithProvider` - also added the name of the provider in the error message
> Fix creator sync

- server/inject.go
- server/wire_gen.go
- service/multichain/fallback.go
- service/multichain/tezos/tezos.go
- service/tokenmanage/tokenmanage.go
- tokenprocessing/handler.go
- tokenprocessing/pipeline.go
- tokenprocessing/process.go
Changes:
* FxHash tokens are automatically retried on syncs if not signed, up to 24 times
* Prohibition tokens are automatically retried on syncs if unable to process an image, up to 24 times. This was only enabled for Share-to-Gallery previously.
> Add fxhash retries

- graphql/resolver/schema.resolvers.go
The token definition media resolver was erroring early because no media exists yet, preventing the syncing state from being returned.
> Fix broken tokens shown on sync

- db/gen/coredb/batch.go
- db/gen/coredb/community.sql.go
- db/gen/coredb/models_gen.go
- db/gen/coredb/query.sql.go
- db/gen/coredb/token_gallery.sql.go
- db/migrations/core/000141_add_is_fxhash.up.sql
- db/queries/core/token_gallery.sql
- emails/send.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- indexer/core.go
- indexer/t__utils_test.go
- platform/platform.go
- publicapi/pagination_test.go
- publicapi/user.go
- server/inject.go
- server/server.go
- server/wire_gen.go
- service/media/media.go
- service/multichain/multichain.go
- service/multichain/operation/operation.go
- service/multichain/tezos/tezos.go
- service/rpc/arweave/arweave.go
- service/rpc/ipfs/ipfs.go
- service/rpc/onchfs/onchfs.go
- service/rpc/rpc.go
- tokenprocessing/media.go
- tokenprocessing/pipeline.go
- tokenprocessing/process.go
**Changes**
* Adds `is_fxhash` to `token_definitions` table
* Adds support for `onchfs://` in media pipeline and in fallbacks
* Better support in pipeline for fxhash assets and in fallbacks
* Pipeline supports configuration at runtime which fields from metadata to download from
* Pipeline now re-maps all URIs of `ar://`, `ipfs://` and `onchfs://` to `https://` to simplify processing
> Tokenprocessing fxhash updates

- graphql/resolver/schema.resolvers.go
This fixes a bug where the mentionSource of a SomeoneMentionedYourCommunity notification was incorrectly returning `Post` in cases where the mention is a comment on a post.
> Check CommentID before PostID when determining mentionSource

- service/auth/auth.go
Safari won't allow secure cookies over regular HTTP, so if we use secure cookies in a local environment, logins won't work.
> Don't set secure cookies when ENV is local

- graphql/resolver/handlers.go
- middleware/middleware.go
- server/handler.go
- server/server.go
- service/logger/logger.go
This PR:
- Reports GraphQL errors (even validation errors, which previously went unreported)
- Includes a trace ID in logs so we can group logs from the same operation together more easily
- Wraps gin request logs with logrus so we can include things like the trace ID in gin logging, too
> Improved logging and error reporting

- db/gen/coredb/batch.go
- db/gen/coredb/community.sql.go
- db/queries/core/community.sql
This is (another) reworked version of the "tokens for community" query, featuring even less clever code reuse, more copy/pasting of boilerplate, and better performance when looking up the tokens in a contract-based community.
> Speed up community tokens query for contract communities

- service/rpc/rpc.go
We were using the errored string because of a flipped error check.
> Fix query escape

- platform/platform.go
- service/multichain/reservoir/reservoir.go
Grails season contracts don't follow the parent contract naming convention in reservoir, so we need to handle them differently.
> Catch Grails contracts in reservoir

- db/gen/coredb/batch.go
- db/queries/core/query.sql
This PR includes media with `MediaTypeGIF` in the set of tokens that can be used for a Gallery preview when `thumbnail_url` is missing but `media_url` is present. Prior to this, only `MediaTypeImage` was included.
> Allow GIFs for Gallery preview images

- graphql/graphql_test.go
- service/multichain/multichain.go
Add new tokens on a user token sync, but don't delete existing holder tokens even if we think they're no longer owned.
> Keep holder status on tokens

- gqlgen.yml
- graphql/generated/generated.go
- graphql/model/models.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- service/mediamapper/mediamapper.go
- service/persist/persist.go
GIFs support transparency, but MP4s don't. Up to this point, the GIFs we've converted to MP4 would default to a black background, but that looks odd outside of dark mode. This PR defaults converted MP4s to an off-white background, and optionally allows a `DarkMode` flag to choose a black background where applicable.
> Add a background color to GIF -> MP4 conversions

- server/inject.go
- server/wire_gen.go
- service/multichain/config.go
- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
- service/multichain/reservoir/reservoir.go
**Changes**
* Uses opensea as the primary source for EVM chains except zora
* Opensea provider calls reservoir provider to get fallback media
* Wraps rate limit errors from Opensea and reports to Sentry
> Use opensea as source

- db/migrations/core/000144_change_gallery_positions_collate.up.sql
This change will enable sorting by fracdex positions, but is backwards compatible with the index positions.
> Change galleries.position collate

- server/inject.go
- server/wire_gen.go
- service/multichain/config.go
- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
- service/multichain/reservoir/reservoir.go
- service/rpc/rpc.go
- util/helpers.go
- util/retry/retry.go
**Changes**
* Configures chains to use the Opensea provider where possible
* Improves the Opensea provider to better take advantage of incremental syncing:
* Send channels are buffered so slow pages and slow writes to the DB don't block other pages
* Each page is now sent to the received channel instead of a single message of all pages
* Adds `ErrOpenseaRateLimited`, which is an error that gets logged and reported to Sentry when a request fails after too many retries
* Adds `GetFallbackMediaBatch` to the Reservoir provider - the Opensea provider calls this method to get fallback media for a list of tokens
* Adds logging to `retry.go` that logs what host is doing the rate limiting, and how long the sleep duration is
> Opensea multichain

- db/gen/coredb/batch.go
- db/queries/core/community.sql
- db/queries/core/query.sql
- go.mod
- go.sum
- graphql/dataloader/api_gen.go
- graphql/dataloader/dataloaders_gen.go
- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- publicapi/community.go
The existing methods for paginating tokens from a community can be slow, almost entirely because they enforce a stable ordering. I have plans to make those methods faster, but in the short term, this is a temporary resolver and database query that will fetch N tokens from a community very quickly and without ordering.
> Add query for retrieving unordered tokens from a community quickly

- publicapi/feed.go
- service/recommend/userpref/personalize.go
**Changes**
* Decreases boost of new posts
* Decreases new post window
* Increases post half-life
* Only the fresh boost or the first post boost is applied rather than both
* Weighs posts based on the number of earlier posts made by the uses
* Fixes bug in personalization where a user has no followers and no tokens in a gallery
> Handle post streaks in feed

- db/gen/coredb/recommend.sql.go
- db/queries/core/recommend.sql
- publicapi/feed.go
**Changes**
Before, if posts were submitted closely together in time, the older ones were unfairly disadvantaged, despite being posted nearly simultaneously. Now, posts created within a minute of each other are grouped. Within these groups, the order of posts is randomized, ensuring every post has an equal opportunity to be noticed.
> Add post groups

- db/gen/coredb/recommend.sql.go
- db/queries/core/recommend.sql
- publicapi/feed.go
Fixes index error because a post could be present in `topNByEngagement` but not `topNByPersonalization`.
> Fix feed index error

- service/notifications/notifications.go
Changes:
- **Added** custom window settings to certain notification types (in this case the 24 hour admire rollup window) for grouping notifications, defaulting to the default 10 min
> custom windows for admires

- service/multichain/opensea/opensea.go
Fixes bug where the `GetTokenByTokenIdentifiersAndOwner` would returns tokens of the same tokenID instead of the expected same tokenID and contract address.
> Fix bug in Opensea provider

- opensea-streamer/main.go
This fixes an infrequent panic where we'd try to pick a random number with an invalid argument (0)
> Don't try to disconnect a random connection if nothing is connected

- service/multichain/alchemy/alchemy.go
- service/multichain/multichain.go
- service/multichain/opensea/opensea.go
- service/multichain/wrapper/wrapper.go
Fixes bug where creator syncs would fail because OS doesn't have a contract but Alchemy does. Rather than exiting on the first error from OS, multichain now checks if the contract is available from one other provider.
> Multichain - Handle OS missing contracts

- service/tokenmanage/tokenmanage.go
- tokenprocessing/media.go
- tokenprocessing/pipeline.go
- tokenprocessing/process.go
- tokenprocessing/tokenprocessing.go
**Changes**
* `tokenmanage` now keeps track of bad token errors and pauses additional runs of contracts that exceed 100 failed runs in 3 hours. Contracts are paused for 3 hours until they can run again. Contracts that get paused are reported to Sentry.
* `tokenmanage.StartProcessing` now returns `ErrContractPaused` if a contract is paused.
* Moves pipeline reporting metrics to `tokenmanage`.
* Adds a new metric for `pipeline_contract_paused`.
> Tokenprocessing - Add pausing contracts

- service/multichain/multichain.go
- service/multichain/wrapper/wrapper.go
We were running into an issue where a goroutine could return while a provider's result channel was still open. Without a goroutine reading from that channel, any writes to the channel would block the sender, which meant we'd only return one page of token results.
This PR updates the `fanIn` function to ensure it only returns when all results channels are closed.
> Stop providers from getting blocked on an abandoned channel

- emails/handler.go
- emails/subscriptions.go
- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/user.go
- service/emails/emails.go
Changes:
- **Added** a new get handler for the email service that will query sendgrid for what a user it is currently unsubscribed to. It will also sync what we have stored in the database for that user, using SendGrid as the source of truth. This is better than using us as the source of truth because unsubscribe links in emails do not connect to gallery. If a user clicks that link it will unsubscribe them on sendgrid but not in our database. By syncing with sendgrid first we ensure accuracy.
Note:
- It was in my TODO that there needs to be a gql mutation for updating subscription statuses. That already exists and has for a while: 
```
updateEmailNotificationSettings(
input: UpdateEmailNotificationSettingsInput!
): UpdateEmailNotificationSettingsPayloadOrError @authRequired
```
> get sendgrid unsubscriptions to sync

- service/multichain/wrapper/wrapper.go
- service/tokenmanage/tokenmanage.go
The `FillInWrapper` cache func was returning the entire token, but we only want to use select fields instead of the entire token.
> Fix wrapper cache func

- db/gen/coredb/models_gen.go
- db/gen/coredb/query.sql.go
- db/migrations/core/000149_add_privy_users.up.sql
- db/queries/core/query.sql
- graphql/generated/generated.go
- graphql/generated_test.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/auth.go
- publicapi/publicapi.go
- publicapi/user.go
- secrets/dev/backend-env.yaml
- secrets/dev/backend-sandbox-env.yaml
- secrets/dev/local/app-dev-backend.yaml
- secrets/local/local/app-local-backend.yaml
- secrets/prod/backend-env.yaml
- service/auth/auth.go
- service/auth/privy/privy.go
- service/persist/postgres/user.go
- service/persist/user.go
- Added `Privy` as an available auth type in the GraphQL schema
- Added backend support for Privy via a `PrivyAuthenticator` type
- Frontend:
- Interacts with the Privy SDK and gets a Privy auth token representing the user's Privy-verified status
- Backend:
- Receives the token, verifies it via public key, and extracts the user's Privy DID
- Calls the Privy REST API to get the user's email address and embedded wallet address
- Uses our existing `Authenticator` architecture to output verified email and wallet addresses
- Now Privy can be used for anything that requires an authenticated email or wallet address!
- When a user is created via `PrivyAuthenticator`, they also get added to a new `privy_users` SQL table that stores their Privy DID, at which point the `PrivyAuthenticator` can also …
> Add support for Privy auth

- db/gen/coredb/batch.go
- db/gen/coredb/community.sql.go
- db/gen/coredb/models_gen.go
- db/gen/coredb/search.sql.go
- db/migrations/core/000151_community_mint_url.up.sql
- graphql/resolver/schema.resolvers.go
- The `communities` table now has `mint_url` and `override_mint_url` fields.
- `mint_url` would be populated by a provider, though none currently use it
- `override_mint_url` lets us manually set a mint URL for a community
- `Community.mintURL` and `TokenDefinition.mintURL` fields now check the `communities` table columns before guessing a chain-based mint URL
> Add community-based mint links and overrides

- server/inject.go
- server/wire_gen.go
- service/media/media.go
- service/multichain/alchemy/alchemy.go
- service/multichain/custom_metadata.go
- service/multichain/multichain.go
- service/multichain/reservoir/reservoir.go
- service/multichain/wrapper/wrapper.go
- service/multichain/zora/zora.go
- tokenprocessing/metadata.go
Changes
* Ensures custom metadata handlers are called for tokens pulled from a sync
* Adds workaround for fetching ENS metadata for tokenIDs stored in decimal in the DB
* Adds custom metadata handler for Opensea shared storefront NFTs that increases the width of the image asset
* `FillInWrapper` now caches already valid tokens so that the same tokens received from a separate provider can re-use its data
> Ensure custom handlers are used

- server/inject.go
- server/wire_gen.go
- service/multichain/custom_metadata.go
Uses Alchemy instead of Opensea for EVM chains (except Zora because Alchemy doesn't support Zora) because of Opensea's low rate limits.
> Use Alchemy as the provider for custom metadata

- db/gen/coredb/query.sql.go
- db/migrations/core/000152_add_farcaster_fid_idx.up.sql
- db/queries/core/query.sql
- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- publicapi/socials.go
- publicapi/user.go
- secrets/dev/local/app-dev-backend.yaml
- server/server.go
- service/farcaster/neynar.go
**Changes**
* Adds a new field, `suggestedUsersFarcaster`, to the `Viewer` type that returns users you follow on Farcaster that you don't follow on Gallery:
```graphql
type Viewer {
suggestedUsersFarcaster(before: String, after: String, first: Int, last: Int): UsersConnection
}
```
* The order of users is based on the  average rank of the their tokens displayed and the number of posts they made
* Adds pagination to `neynar.FollowingByUserID` - previously only returned the first 25 users
* Adds index to `pii.for_users` to find a user by Farcaster FID quickly
> Add Farcaster friend finder

- emails/emails.go
- emails/subscriptions.go
- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- service/persist/email.go
Changes:
- **Added** the other unsubscription groups to the email handlers and graphQL resolvers
Like the previous time we added new unsub groups, I left the fields nullable in gql for backwards compat, once the frontend starts using the new fields directly we should make them non-nullable
> add the other unsub types

- emails/digest.go
- emails/send.go
Changes:
- **Added** a new digest value and override for setting the subject line of the digest email
> custom subject in digest values overrides

- publicapi/feed.go
- secrets/local/local/app-local-indexer-server.yaml
- server/inject.go
- server/server.go
- server/wire_gen.go
- service/multichain/alchemy/alchemy.go
- service/multichain/custom_metadata.go
- service/multichain/opensea/opensea.go
- service/multichain/reservoir/reservoir.go
- service/multichain/wrapper/wrapper.go
- service/notifications/notifications.go
- service/persist/postgres/postgres.go
- service/rpc/rpc.go
- util/retry/retry.go
**Changes**
* Adds a `Retryer` class which buffers requests to an external API to avoid rate limits and handles retries in cases where the limit is exceeded
* It is currently used in front of calls to Reservoir and Opensea 
* Alchemy is now the primary provider for EVM chains (except Zora which continues to use OS as the primary), with a fallback to OS if Alchemy is missing data
* Both Alchemy and OS are still used in syncs for EVM chains (except Zora which uses Zora and OS)
* Fixes URL encoding bug in Alchemy provider
* The Opensea custom metadata handler now accepts an optional metadata arg to avoid an extra request to a provider to fetch metadata
> Add improved rate limiter and set Alchemy as the primary

- server/inject.go
- server/wire_gen.go
- service/limiters/rate.go
- service/multichain/opensea/opensea.go
- service/multichain/reservoir/reservoir.go
- service/multichain/wrapper/wrapper.go
- util/retry/retry.go
Errors arise when trying to obtain a lock on a Redis key with several instances of a limiter (even though all point to the same redis cache and try to obtain the same key) during a many-chain sync. Passing a limiter to the constructor instead of instantiating a limiter in the constructor fixed the issue. I'm not sure why this is the case, though.
> Make underlying retry limiter a singleton

- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
Mint.fun is pivoting to meme.market, and Zora's cross-chain indexing has improved. We should default to suggesting Zora.
Example working URLs per chain:
- ETH mainnet (long token ID): https://zora.co/collect/eth:0x7a15b36cb834aea88553de69077d3777460d73ac/5280336779268220421569573059971679349075200194886069432279714075018412552596
- Base: https://zora.co/collect/base:0xa25aed810f763e1d0dfc13f463bb55e4ad2f4653/1
- Optimism: https://zora.co/collect/oeth:0x76af3c60f83f4b03f532d8af6daa6d75b0b985c8/8
In the future, we should enable minting within our own app through something like Reservoir.
> Deprecate mint links to mint dot fun

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- publicapi/user.go
This PR fixes an issue where users were being "followed back" instead of being "followed," and also updates the original query to use `generate_subscripts` to ensure that result rows are returned in the same order as supplied parameters.
> Change UserFollowsUsers to UsersFollowUser and enforce ordering

- db/gen/coredb/community.sql.go
- db/gen/coredb/token_gallery.sql.go
- db/migrations/core/000155_fix_token_community_memberships_indexes.up.sql
- db/queries/core/community.sql
- db/queries/core/token_gallery.sql
This PR fixes an issue I created yesterday, where dropping an index on the `token_community_memberships` table and replacing it with a new one inadvertently broke a few `on conflict` clauses that referenced the old constraint.
> Fix missing unique constraint for "on conflict" check

- server/handler.go
Disable GraphQL handlers for downtime purposes. Do not merge until it's migration time!
> [DO NOT MERGE] Disable GraphQL handlers temporarily

- emails/digest.go
- emails/send.go
Changes:
- **Added** subject in the dynamic template data directly.
Looks like the manual subject adds in the sendgrid API are not working, saw some complaints in github issues on their docs. By using `{{{subject}}}` in the dynamic template settings on sendgrid and then filling it with the subject field, it works correctly.
Also, the value was not correctly setting on retool, now it is.
> subject in the dynamic template data

- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/schema/schema.graphql
- service/multichain/highlight/highlight.go
- tokenprocessing/process.go
**Changes:**
* Renames `ClaimStatusTokenSynced` from `TOKEN_SYNCED` to `MEDIA_PROCESSING`
* Adds new status `ClaimStatusMediaFailed` to indicate that the media pipeline failed after too many tries
* Updates resolver to still return data when status is `ClaimStatusMediaFailed`
> Highlight - catch media processing errors

- emails/emails.go
- emails/verify.go
- secrets/dev/emails-server-env.yaml
- secrets/dev/local/app-dev-emails.yaml
- secrets/local/local/app-local-emails.yaml
- secrets/prod/emails-server-env.yaml
This PR auto-adds verified email addresses to the marketing list so they don't need to be added manually.
> Add verified email addresses to the SendGrid marketing list

- autosocial/handler.go
- service/farcaster/neynar.go
ActiveStatus doesn't actually mean what we thought it did, and it's no longer being used. This fixes an issue where we intentionally didn't associate a user's Farcaster account if they were "inactive"
> Get rid of the ActiveStatus property on NeynarUser

- graphql/generated/generated.go
- graphql/schema/schema.graphql
Adds `@restrictEnvironment` directive so test tokens aren't created on prod.
> Add restrictEnvironment to mint mutation

- service/auth/privy/privy.go
This PR adds an extra user lookup step during Privy login. If we can't find an existing Gallery user via Privy DID, now we'll also try to find an existing Gallery user by verified email address.
> Try to look up a user by email address when using Privy login

- service/notifications/notifications.go
Removes quantity from the message and renames "token" to "NFT" if there isn't a token name.
> Update copy of new token notification

- graphql/generated/generated.go
- graphql/model/models_gen.go
- graphql/resolver/schema.resolvers.go
- graphql/resolver/schema.resolvers.helpers.go
- graphql/schema/schema.graphql
- publicapi/user.go
Prior to this PR, the `updateEmail` mutation would send a verification email to the user whenever it was called. This PR adds an optional authenticator to the `updateEmail` mutation. If the authenticator can verify the supplied email address, no manual verification email will be sent.
> Add optional authenticator when updating an email address

- db/gen/coredb/batch.go
- db/gen/coredb/query.sql.go
- db/queries/core/query.sql
- graphql/dataloader/api_gen.go
- service/multichain/multichain.go
- tokenprocessing/pipeline.go
- tokenprocessing/process.go
Changes
* Updates the `last_updated` column of `token_definition` when media is updated
* Removes requirement for media to exist for queries that fetch a token
* Adds more logging around syncing and token processing
* Fixes bug where no media is saved if a contract is paused
> Add more logging to processing

- service/persist/postgres/user.go
- service/persist/user.go
This PR fixes a longstanding bug where updating a user's info would set their `last_updated` time to zero. We were accidentally passing in an empty `time.Time` for the `LastUpdatedTime` parameter, but in reality, there shouldn't be a `LastUpdatedTime` parameter at all -- we should just be using `now()` as part of the SQL statement. Now we are!
> Set last_updated when updating user info

- db/gen/coredb/query.sql.go
- db/gen/coredb/token_gallery.sql.go
- db/queries/core/query.sql
- db/queries/core/token_gallery.sql
- go.mod
- go.sum
- graphql/graphql_test.go
- graphql/stub_test.go
- opensea-streamer/main.go
- publicapi/merch.go
- secrets/dev/local/app-dev-opensea-streamer.yaml
- server/inject.go
- server/wire_gen.go
- service/multichain/config.go
- service/multichain/multichain.go
- service/multichain/operation/operation.go
- service/multichain/simplehash/simplehash.go
- service/multichain/wrapper/wrapper.go
- service/persist/postgres/contract_gallery.go
- tokenprocessing/process.go
- util/retry/retry.go
**Changes**
This PR refactors the upsert of definitions, token community memberships, and token instances into separate queries. Rows are also sorted before inserting into the DB. These changes should prevent deadlocks since each transaction would hold fewer row locks and ensure a consistent insertion order.
Fetching metadata now uses the `SyncPipeline` wrapper instead of calling the Simplehash provider directly so that our custom metadata handlers are applied to a token.
Finding new tokens previously required accumulating an in-memory map of added tokens. New tokens are now instead found by joining the inserted rows with the state of the table at the beginning of the transaction. These tokens are also submitted to tokenprocessing for media processing.
The streamer now uses the recipient …
> Simplehash fast follows and sync improvements

- graphql/graphql_test.go
- server/inject.go
- server/wire_gen.go
- service/multichain/config.go
- service/multichain/multichain.go
- service/multichain/simplehash/simplehash.go
- service/persist/postgres/user.go
- service/tracing/http.go
- tokenprocessing/tokenprocessing.go
This PR uses Simplehash for Tezos and enables creator support for Tezos. Creator support is only available for contracts you deployed, shared contracts like fxhash aren't supported. This PR also fixes a bug in the wallet repo query where the L1 chain of the wallet wasn't returned, resulting in a default L1 Chain of 0 (which corresponds to Ethereum).
Misc
* Increases wait time for syncing tests
* Submits the whole page of tokens to tokenprocessing instead of batching in groups of 50
* Turns off idle connections in tokenprocessing to reduce the number of open file sockets
> Use simplehash for tezos

- db/gen/coredb/batch.go
- db/gen/coredb/models_gen.go
- db/gen/coredb/query.sql.go
- db/gen/coredb/token_gallery.sql.go
- db/migrations/core/000159_add_token_columns_to_media.up.sql
- db/queries/core/query.sql
- db/queries/core/token_gallery.sql
- service/multichain/multichain.go
- service/multichain/operation/operation.go
- sqlc.yaml
- tokenprocessing/pipeline.go
Changes
* Adds chain, contract, and token ID to the token media table so that we can trace if we ever processed media for a token
* Changes heuristic that determines if a definition is new by comparing when the definition was created to when it was last updated
* Adds more logging to around when a definition is dispatched
> Add more tracing to token media dispatch

- db/gen/coredb/token_gallery.sql.go
- db/queries/core/token_gallery.sql
- graphql/fixture_test.go
- graphql/graphql_test.go
- graphql/stub_test.go
- opensea-streamer/main.go
- publicapi/mint.go
- server/inject.go
- server/wire_gen.go
- service/multichain/multichain.go
- service/multichain/operation/operation.go
- service/persist/token_processing_jobs.go
- service/task/task.go
- service/tokenmanage/tokenmanage.go
- tokenprocessing/handler.go
- tokenprocessing/process.go
**Changes**
* Fixes bug where minting would prevent future synced tokens from being submitted to tokenprocessing
* Finds new tokens using the past heuristic of comparing a snapshot of the definitions table before and after insertion
* Refactors submission to tokenprocessing to use the new `Submitter` interface
* Tests should also fail less often
* Renames tokenprocessing task functions for clarity:
* `CreateTaskForTokenProcessing` -> `CreateTaskTokenProcessingSyncBatch`
* `CreateTaskForTokenTokenProcessing` -> `CreateTaskTokenProcessingRetryToken`
* `CreateTaskForOpenseaStreamerTokenProcessing` -> `CreateTaskTokenProcessingForOpenseaStreamer`
* Various minor tweaks
> Add submitter interface for submitting tokens to tokenprocessing

- cmd/dataloaders/generator/dataloader.go
- util/batch/batch.go
I occasionally find myself wanting a reusable batcher that can do what dataloaders do: open a batch with a max size and timeout, wait for requests to come in, submit all the queued up requests when the batch closes, etc. I've reused this pattern in our push notifications handling, and wanted to use it again for Kafka event handling.
This PR refactors the `Dataloader[TKey, TResult]` type to be a thin wrapper around a reusable `batch.Batcher[TParam, TResult]` class that can be reused in any other context where we want batching.
The most notable change is that the `Load` functions have been renamed to `Do`, since we don't really know if a generic batch is "loading" things or just executing commands and receiving a result status. The `Dataloader` wrapper maintains the existing `Load` function …
> Refactor dataloaders into a general-purpose batching struct

- kafka-streamer/batcher.go
- kafka-streamer/main.go
This PR adds a worker pool to each message batcher, allowing all message processing to happen in parallel across multiple workers. The resulting messages are still submitted as a batch in the order they were initially read in. As a result, we can now scale our message processing up considerably by increasing the number of vCPUs per container instance. Even without changing the number of vCPUs, we'll likely see something like a 5x increase in processing throughput.
> Process Kafka messages in parallel

- service/tokenmanage/tokenmanage.go
**Changes**
* Reports paused runs to Sentry so we know when and how often the runs occur
* Reduce the pause time from 3 hours to 1 hour because 3 hours seemed too long
> Report paused contract runs to Sentry

- tokenprocessing/handler.go
- tokenprocessing/process.go
Increase the number of retries waiting for a non-empty metadata response from Highlight from `15` to `30` and increase the overall number of retries from `10` to `20` if that step fails.
> Double highlight retries

- service/multichain/simplehash/simplehash.go
- service/persist/token.go
This PR includes the `artifactUri` field in the metadata so that we can process animation URLs for Tezos tokens.
> Include artifactUri in metadata for Tezos
